### ISSUE TITLE
Lanzador Shotcut

### ISSUE THREAD

**Issue by dgonzalezarroyo** [max-linux/max-desktop#1002]
Parece ser que el ejecutable de shotcut está en /usr/lib/shotcut/shotcut ,que no está en $PATH, y por eso no lo encuentra. J. M. Sancho propone que el instalador del paquete cree un enlace simbólico en /usr/bin a /usr/lib/shotcut/shotcut y modificar el lanzador del menú.

**Comment by mariodebian** [comment]
![image](https://user-images.githubusercontent.com/522472/117290603-4b6cf700-ae6e-11eb-9e59-2eb1696c80fa.png)
