### ISSUE TITLE
MAX 10.5 y 9.5: Incluir Fotowall RETRO en repositorios y +Aplicaciones

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1005]
Propuesto por Daniel.

Fotowall 1.0 RETRO es un programa  que permite realizar collages de 
imágenes y texto de manera muy rápida y sencilla.

Se trata de incluirlo en los repos de MAX 9 y 10 para que sea instalable facílmente.

El fuente está en [https://github.com/enricoros/fotowall](https://github.com/enricoros/fotowall)

**Comment by DaniMAdridlinuX** [comment]
Ya se incluye por defecto a partir de MAX 11.5.1
