### ISSUE TITLE
MAX 10.5: Incluir en repos y en +Aplicaciones draw.io

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1014]
Esta webapp, draw.io es un potente editor de diagramas, esquemas, circuitos,... Han sacado versión de escritorio cuyas fuentes están en:

[https://github.com/jgraph/drawio](https://github.com/jgraph/drawio)

y 

[https://github.com/jgraph/drawio-desktop/releases/tag/v12.3.2](https://github.com/jgraph/drawio-desktop/releases/tag/v12.3.2)

debe incluirse en **+Aplicaciones en el menú Graficos**

**Comment by maxezek** [comment]
Ahora es  jgraph/drawio-desktop  y en la web está como [https://www.diagrams.net/](https://www.diagrams.net/)

**Comment by DaniMAdridlinuX** [comment]
incluido de serie en MAX 11.5.2
