### ISSUE TITLE
Ver viabilidad y posible actualización de la aplicación Qgis

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#1017]
Si se puede y es viable, creo que sería necesaria una actualización si no interfiere al resto.

Reportado por David, procedente del foro de MAX:

Escribo al foro para saber si es posible que se actualice la versión de Qgis que está en el repositorio. Actualmente esta la versión 2.8 y la última LTR es la 3.14. Sería interesante que se pudieran instalar una o os versiones porque en las últimas los plugins no están desarrollados del todo. Una versión estable y con todos lo plugins funcionando sería la 2.18. Supongo que no es una aplicación muy utilizada peo en Geografía es de gran importancia y en mi IES la usamos bastante para muchas cosas. Gracias

**Comment by DaniMAdridlinuX** [comment]
En MAX11 ya tenemos la 3.10.4 y en en MAX 10 la estable que comenta David 2.18
