### ISSUE TITLE
MAX 9.5 y siguientes: sustituir jitsi desktop  por jitsi-meet-electron

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1018]
Fundamental para la formación disponer de una herramienta de videoconferencia con opciones de identificación con EducaMadrid. Aunque jitsi desktop está declarado como legacy siguen actualizándola.

Incluir de serie Jitsi permite tener lo mismo que **Pidgin** pero con videoconferencia.

La última versión estable es de noviembre de 2019 lo que indica que no han abandonado su desarrollo. 

En la web ponen:

To use our debian/ubuntu stable repository:

install the Jitsi repository key onto your system

 _wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -_

create sources.list.d file with the repository

 _sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"_

update your package list

 _sudo apt-get -y update_

nstall Jitsi_

 _sudo apt-get -y install jitsi_

**Comment by maxezek** [comment]
### Olvidar el anterior post.

Fundamental para la formación disponer de una herramienta de videoconferencia con opciones de identificación con EducaMadrid. Han cambiado jitsi-desktop y la han metido nueva con electron.

**Jitsi Meet Electron**

https://github.com/jitsi/jitsi-meet-electron

**Comment by DaniMAdridlinuX** [comment]
Ahora ya tenemos jitsi integrado en EdcaMadrid por lo que no es necesario instalar nada en local.
