### ISSUE TITLE
Ver viabilidad de cambio de paquetes openclipart-png y openclipart-svg por otros que no requieran registro.

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#1021]
Reportado por Miguel Mayoral.

Buenos y festivos días

Revisando los paquetes de Max que más ocupan para agilizar el portátil, me he encontrado con los paquetes openclipart-png y openclipart-svg, que para mí nunca fueron muy necesarios. Yo necesito gráficos SVG de forma muy puntual, y normalmente visitaba la página openclipart.org, que entiendo que era de donde recopilaban los gráficos de ambos paquetes ¿no?. Pero ahora esta página parece ser gestionada por una empresa que no ofrece búsquedas y que para subir contenido pide estar registrado (pero no ofrece enlace de registro), etc. Todo muy problemático. Eso sí, el botón de donaciones es gigante.

¿Cómo afectará esto a futuros desarrollos de Max? ¿Se podrán incluir de serie los gráficos que anteriormente podíamos utilizar libremente? ¿O nos podemos ir olvidando de los gráficos vectoriales?

**Comment by mariodebian** [comment]
No entiendo nada en este issue.

El botón de registrarse es bastante visible, y lo más parecido a donar es que te piden que para registarte tienes que donar una imagen a su base de datos.

El buscador gunciona sin registrarse y más visible no puede ser....

He navegado desactivando addblok por si acaso... ¿seguro que https://openclipart.org es la web a la que entró el usuario?

Otro tema es el espacio usado pero se usa desde libreoffice como base de datos para la realización de documentos,
