### ISSUE TITLE
MAX 9 A 11: Incluir Scratux o Scracht para linux

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1022]
Scratux no es otra cosa que Scratch desktop para linux.

[https://scratux.org/index.html](https://scratux.org/index.html)

Los fuentes están en [https://github.com/scratux/scratux](https://github.com/scratux/scratux)

Para llevar a +Aplicaciones, en la personalización de Infantil y Primaria, o ¿por defecto?

**Comment by jrodriguezpascua** [comment]
Ya sabes que tenemos la iso petada, pero vemos hueco o si podemos descartar alguna otra aplicación. Si no, pues a paquete y a +Aplicaciones.

**Comment by DaniMAdridlinuX** [comment]
Creo que el hueco lo logramos quitando Scratch 1.4 que es el que viene ahora y está desactualizado. Aparace en el menú de programación y en la barra de Infantil y Primaria. Sería sustituir Scratch 1.4 por Scratux
