### ISSUE TITLE
MAX 10 a 11: El servicio SAMBA da un error al actualizar

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1023]
Reportado por Pablo Triviño.

Hola, al actualizar MAX 10 me ha salido esto:

Configurando samba-libs:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando samba-vfs-modules (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando python-samba (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando libsmbclient:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando smbclient (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando samba-common-bin (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando samba-dsdb-modules (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Configurando samba (2:4.7.6+dfsg~ubuntu-0ubuntu2.17) ...
Samba is not being run as an AD Domain Controller.
Please ignore the following error about deb-systemd-helper not finding samba-ad-dc.service.
Job for smbd.service failed because the control process exited with error code.
See "systemctl status smbd.service" and "journalctl -xe" for details.
invoke-rc.d: initscript smbd, action "restart" failed.
● smbd.service - Samba SMB Daemon
Loaded: loaded (/lib/systemd/system/smbd.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2020-07-02 21:05:04 CEST; 3ms ago
Docs: man:smbd(8)
man:samba(7)
man:smb.conf(5)
Process: 13908 ExecStart=/usr/sbin/smbd --foreground --no-process-group $SMBDOPTIONS (code=exited, status=1/FAILURE)
Main PID: 13908 (code=exited, status=1/FAILURE)

jul 02 21:05:04 MaxPapa systemd[1]: Starting Samba SMB Daemon...
jul 02 21:05:04 MaxPapa systemd[1]: smbd.service: Main process exited, code=exited, status=1/FAILURE
jul 02 21:05:04 MaxPapa systemd[1]: smbd.service: Failed with result 'exit-code'.
jul 02 21:05:04 MaxPapa systemd[1]: Failed to start Samba SMB Daemon.
dpkg: error al procesar el paquete samba (--configure):
instalado samba paquete post-installation guión el subproceso devolvió un error con estado de salida 1

**Comment by victoramdz** [comment]
Tengo un equipo con Max10 sin instalaciones añadidas,  y actualizado a tope,  no he podido reproducir esta incidencia.

**Comment by jrodriguezpascua** [comment]
Es posible que esto no sea un ticket, si no una mala actualización de algún paquete de Pablo.

**Comment by maxezek** [comment]
Si, eso parece... Creo que se puede cerrar
