### ISSUE TITLE
MAX 11 Prealfa: INSTALACIÓN DE PROGRAMAS Y PRUEBAS DE FUNCIONAMIENTO

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1030]
### PRUEBAS MAX11 PREALFA – INSTALACIÓN DE PROGRAMAS Y PRUEBAS DE
FUNCIONAMIENTO

|PROGRAMA FUNCIONALIDAD|FUNCIONAMIENTO|PROPUESTA DE SOLUCIÓN|
|----------|-----------|------------|
| Arasuite  |Le pasa lo mismo que en MAX10, el editor de texto Araword no cambia pictogramas al pulsar con F3 y es algo fudamental para los PT y AL|Solución encontrada por Victor y reportada por Daniel. MAX 9.5 a 10.5. Araword de Arasuite no funciona correctamente #1003. Víctor Armendariz me ha proporcionado una solución para el problema de Araword. Os recuerdo que se trata de un procesador de textos de pictogramas. En MAX no funciona la funcionalidad de cambiar de criptograma, que se activa a través de menú o pulsando F3. Se trata de una funcionalidad clave y los profesionales que lo han usado dicen que sin esa funcionalidad no se puede aprovechar el programa. Pues Víctor me ha propuesto, y lo he probado y funciona, instalar la versión que hay en esta página: https://sourceforge.net/projects/arasuite/Me la he descargado y hay que arrancar un archivo denominado ArawordApp y funciona perfectamente. |
| caja-image-converter|Se instala desde Synaptic, no pesa nada y permite redimensionar imágenes desde el botón derecho del ratón. Funciona perfecta.|Instalarlo de serie |
| Aplicaciones de eLearning|No aperece en el menu Educación. Ahí iría exeLearning y ¿Learningapps?|Volver a incluirlo. |
| Exelearning|No está en el menú Educación. Aparece instalado intef-exe 3:2.5ppa1max1 pero incompleto, no hay /usr/bin/exe ni /usr/bin/exe_do|Debería venir instalado de serie Si está instalado pero incompleto. Volver a empaquetar el .deb oficial intef-exe_2.5_all.deb del github https://github.com/exelearning/iteexe/releases/tag/2.5 Depende de Python 2.7 
LibreOffice||Subir a versión 7 |
| Ardublock|No está en los repositorios|Hasta ahora siempre ha estado en los repos |
| jarnal|Tarda mucho en abrirse|Redundante, tenemos Xournal. Quitar de la iso |
| define-me|Funciona pero a mi no me aporta mucho. Quitar de la iso|No me aporta valor añadido |
| Calculadoras|Aparece Calculadora de mate, Gcalculadora (Gnome?) y speedCrunch|Quitar Gcalculadora y speedcrunch de la iso por redundante pero dejar en repos. Alguna a la boutique +Aplicaciones.  |
| gEDA|Parecen viejos rockeros|Quitar de la iso y mantener en repos. Sustituir por draw.io que ahora se usa mucho https://github.com/jgraph/drawio-desktop/releases/tag/v13.9.9 Es como DIA pero más actual. |
| Logisim|Proyecto original abandonado|Existen dos fork interesantes y en desarrollo: https://github.com/LogisimIt/Logisim y https://github.com/reds-heig/logisim-evolution/releases/tag/v3.3.0 Yo lo quitaría de la iso y o sustituiría en repos por uno de estos. |
| denemo|Instalada la 2.2|Actualizar a la última estable 2.4 porque va en consonancia con Musescore http://denemo.org/downloads-page/ |
| Musescore|El lanzador del menú música no funciona pero está instalada y aparece en el menú Sonido y Video|Cambiar el lanzador del menú Música manteniendo redundante el de Sonido y Vídeo. La orden es:  mscore3 %F Ahora es Musescore3 y la versión de MAX 10 era Musescore 2.3.2 |
| Gnu-Octave|Aparece en otras aplicaciones educativas|Debe aparecer en el menú matemáticas. |
| Step|Aparece en otras aplicaciones educativas|Yo creo que debe ir en el menu ciencias.  |
| Phet |No es una app de escritorio pero es un conjunto de simuladores de Ciencias en HTML5 enorme|Creo que merece la pena crear un lanzador tipo: firefox https://phet.colorado.edu/es/ o chromium https://phet.colorado.edu/es/ |
| Learningapps|No es una app de escritorio pero es un buen añadido para el Aula virtual como recurso|Creo que merece la pena crear un lanzador tipo: firefox https://learningapps.org/ o chromium https://learningapps.org/ |
| wxmaxima|Aparece en el menu Otras aplciaciones|No estaba en nuestros menús. De ir debe ir en matemáticas |
| Dia|Funciona pero me parece un milagro. Aplicación de 32 bits |Sustituir por draw.io |
| Inkscape|Esta la versión 0.92.5|Actualizar a la última estable: https://launchpad.net/~inkscape.dev/+archive/ubuntu/stable/+files/inkscape_1.0.1+r74~ubuntu20.04.1_amd64.deb https://launchpad.net/~inkscape.dev/+archive/ubuntu/stable/+sourcefiles/inkscape/1.0.1+r74~ubuntu20.04.1/inkscape_1.0.1+r74~ubuntu20.04.1.tar.xz  |
| Imagemagik|No se porque aparece y no hace nada|Simplemente lo eliminaría del menú Gráficos |
| Shutter|No funciona, aparentemente sin desarrollo pero sigue existiendo incluso como snap.|Está la opción flameshot: https://github.com/flameshot-org/flameshot/releases/tag/v0.8.5 y ksnip: https://github.com/ksnip/ksnip/releases/tag/v1.7.3  |
| Mypaint|No está instalado ni aparece en el menu Graficos.|Instalar https://github.com/mypaint/mypaint/releases/tag/v2.0.1 Y llevar al menu Gráficos |
| caja|Añadir como menu contextual OptimizarPDF |Lo explico en https://github.com/maxezek/optimizarPDF#versi%C3%B3n-como-elemento-del-men%C3%BA-contextual-en-caja  |
| dvddisaster||Propongo quitarlo de la iso |
| gnome-firmware|No se abre|Esta es nueva. No se lo que hace. Está en el menu Herramientas del sistema como firmware |
| max-configurador-java||No tiene icono en el menu |
| hexchat||No lo teníamos en MAX anteriores. Debe ir en la iso de Ubuntu Mate. Si no molesta lo dejaría pero habría que ver como sacarle partido. |
| KDE connect|No funciona. O eso parece porque estaba en MV|No la teníamos pero es  interesantísima. . Para Gnome existe Gsconnect https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki Probada KDEConnect en MAX 10 y funciona de maravilla. El móvil se convierte en un presenter y en un control de ratón y teclado perfecto. |
| Gcompris, Childplay, PySyCache, Tux Typing, Tux Paint, Ktubering (Señor patata), Pinta | Todos estos programas se encuentran en Synaptic y son parte de la barra de personalización Infantil y Primaria | Que vengan en la iso de serie ya que son lo que aporta un carácter diferenciador a MAX para Infantil y  Primaria. Probadas y funcionan. Va a estar complicado. _Mucho que pulir de la iso de Ubuntu. Creo que por eso iban en el metapaquete max-infantil._
| Omnitux | Suite educativa que forma parte de la personalización de Infantil y primaria https://sourceforge.net/projects/omnitux/ | probado y funciona |
| Eduactiv8 | Suite educativa que forma parte de la personalización de Infantil y primaria https://sourceforge.net/projects/eduactiv8/ | No he sabido cómo instalarlo así que no se si funciona bien. |

**Comment by victoramdz** [comment]
Educativ8 

Packages for multiple Linux distributions are available from:
https://software.opensuse.org//download.html?project=home%3Aimiolek-i&package=eduactiv8

**Comment by mariodebian** [comment]
* Arasuite lo descargo desde https://sourceforge.net/projects/arasuite/files/ y lo empaqueto en deb junto con la home por defecto, ver script: https://github.com/max-linux/max-desktop/blob/master/max-arasuite/debian/rules
Ya tengo la ultima versión 2.2.4 ¿Qué lanzador hay que cambiar?

* caja-image-converter: Hecho en aba528a9edd5d70cbb32411a52ef42ded3da6bd4

* Aplicaciones de eLearning Ahí van moodle, malted, jclic, intef-exe que no se habían instalado, por eso no salía el menú, ahora con intef-exe areglado ya sale

* Exelearning es un reempaquetado de su PPA incluyendo el tema de MAX, pero como Ubuntu 20.04 ha dejado python2 en deprecated fallan muchas cosas, cambiado a pybuild parece que ya incluye los archivos perdidos.

* LibreOffice 7.x más adelante

**Comment by maxezek** [comment]
Al aplicar en la MV las actualizaciones he perdido el acceso por red NAT. 

Arasuite con Araword y TICO deben ir en el menu Accesibilidad pero también en el en nuevo submenú Accesibilidad e inclusión del menú Educación según #1027

El resto lo compruebo cuando vuelva a una instancia anterior en la MV. Cosa extraña, además de perder el acceso a la red me dice que bluegriffon puede quitarse por no ser necesario. Eso no debería ser así.

**Comment by mariodebian** [comment]
He forzado a que se desinstale netplan.io (otro ingenioso invento de Ubuntu para romper la red), debería tomar el control el network-manager de toda la vida. 

No te vuelvas loco porque me gustaría entre hoy y mañana dejar una ISO que se parece más a MAX que una Ubuntu Mate MAXterizada.

Intentando hacer una ISO no entra en los 4GB (ha engordado el tamaño pero no la cantidad de paquetes) por lo que he quitado de la instalación base unos pocos de los que más ocupan: bluegriffon, fritzing, librecad, openclipart-png, openclipart-svg, stellarium.

**Comment by maxezek** [comment]
Ok. Me lo tomo entonces como un aprendizaje, vi lo de netplan.io al actualizar y no sabía lo que era. Es bueno ir lo conociendo por si acaso.

Si quieres eliminar más programas de la iso quita celuloide, DVDStyler , Brasero, mpv mediaplayer, WinFF y xine. Alguno más podremos quitar...
