### ISSUE TITLE
MAX 11 alfa: Ayuda para generar la iso. Programas a eliminar de la iso

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1031]
# APLICACIONES A QUITAR DE LA ISO DE MAX 11 

* [x] celuloide  --→ Llevamos VLC
* [x] DVDStyler   → Seguro que a alguien le es útil pero no como para ir por defecto
* [x]  Brasero  → Redundante teniendo K3B 
* [x]  mpv mediaplayer --→ Llevamos VLC
* [x]  FFdiaporama  → Es un proyecto abandonado. Una pena. Para llevarlo al repo +Aplicaciones
* [x]  WinFF  → Esto es innecesario con handbrake
* [x]  xine  → Redundante con VLC
* [x]  jarnal → Redundante con Xournal
* [x]  define-me → Poca utilidad
* [x]  gEDA.. → Poco uso. A +Aplicaciones
* [x]  Logisim  --→ Está discontinuado aunque existe un fork italiano https://github.com/LogisimIt/Logisim . También podemos cambiarlo por https://github.com/hneemann/Digital A +Aplicaciones
* [x]  Speedcrunch → A +Aplicaciones y nos sobran calculadoras
* [x]  Gcalculadora → Idem, está la calculadora de MATE
* [x]  Gnu-Octave → Para +Aplicaciones. Tenemos Geogebra 5
* [x]  wxmaxima → Para +Aplicaciones. Tenemos Geogebra 5
* [x]  Mypaint → Muy a mi pesar. Creo que se usa poco. A +Aplicaciones
* [x]  dvddisaster → Seguro que a alguien le es útil pero no como para ir por defecto
* [x]  kmag → Tenemos Orca screen magnifier y magnus. Pasar a +Aplicaciones
* [ ]  TCOS → Me parte el corazón pero que sea Pyhton 2.7 y que Mario ya no lo mantenga me parece entonces que puede quitarse. ¿Metemos entonces Epoptes?
* [x]  Avidemux  → A mi me sigue sacando de apuros pero entiendo que teniendo KDEnlive puede ir a +Aplicaciones sin problemas
* [x]  Bluegrifon.  Dejarlo en mas aplicaciones
* [x] Editor de texto Scite. Dejarlo en más aplicaciones
* [x]  Scribus. Lo usan cuatro gatos aunque es muy potente. Los que lo usan se lo pueden instalar desde +aplicaciones
* [x]  Pidgin- A +aplicaciones
* [x]  Scracth 2 a +Aplicaciones. Pero su hueco debe rellenarse con Scratux [https://scratux.org/](https://scratux.org/)

**Comment by DaniMAdridlinuX** [comment]
Blender. Es muy potente aunque su uso es para perfiles muy técnicos. Dejarlo en +aplicaciones
Shutter: está descontinuado. Sustituir por Ksnip https://github.com/ksnip/ksnip

**Comment by maxezek** [comment]
OJO!!!! Resulta que **Shutter** no está discontinuado. Acaban de sacar una nueva versión... No

Y Blender... mucho cuidado con el empaquetado. Debe funcionar en usuario alumno y da problemas homealumno con el actual Blender de la web.

No has marcado TCOS... Mario me vas a dar una alegría si todavía puede correr en MAX 11

**Comment by mariodebian** [comment]
TCOS sigue vivo (en UCI) igual no como clientes ligeros pero la app de control de equipos es instalable, y arranca.
