### ISSUE TITLE
MAX 11: Autofirma no llega a cargar certificado de fnmt

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#1032]
Arranco Autofirma, cargo un pdf para firmar, no encuentra certificado (Firefox y Chrome lo tienen cargado sin problema), me muestra la pantalla para que firme con imagen, cancelo, y entonces me pide el cetificado por ubicación, encuentro mi certificado, lo cargo, pero no firma el documento.
¿Dónde se cargan los certificados de autofirma? He visto que puede ser por la versión de Java.

**Comment by DaniMAdridlinuX** [comment]
En cambio si cuando busco el certificado, en vez de seleccionar el de la FMNT selecciono uno de Camerfirma sí funciona.

**Comment by DaniMAdridlinuX** [comment]
Adjunto vídeo donde se ve cómo funciona con certificados de Camerfirma, con los de FMNT , cuando lo selecciones y pones la contraseña no pasa nada.
 
https://user-images.githubusercontent.com/75364104/108258272-1fd84b80-7160-11eb-8d10-e235b5cff16f.mp4

**Comment by maxezek** [comment]
José Miguel ha hecho un estudio pormenorizado que está genial:

"Buenos días,

dejo por aquí algunas cosas que he probado, y algunas consideraciones.

(aclaro que funciona para una firma local de un documento, pero no para una firma electrónica en la web en ninguno de los dos navegadores)

las pruebas las hago con las siguientes web:

[1] https://valide.redsara.es/valide/firmar/ejecutar.html

[2] https://preinterweb.mitramiss.gob.es/autoAfirmaTest/


1- creo que en Max live debería funcionar autofirma directamente.

Quiero decir que sin hacer nada o con un paso muy sencillo (además de instalar el certificado propio del usuario) autofirma funcionara  para comunicaciones con la administración.

Permitiría tener una solución rápida en caso de que desde cualquier SO instalado no funcionara la firma electrónica para enviar doc o firmar archivo. Tendríamos un entorno controlado libre de modificaciones/actualizaciones/... del usuario después de la instalación.

Un punto para Max 


2- Como digo ahora no funciona ni en live ni instalado en máquina virtual,  ni actualizando, ni  sin actualizar sistema.

Los errores que he encontrado (estos cambios hay que hacerlos tanto para que funcione en live como instalada):

2.1 El certificado /usr/lib/Autofirma/autofirma.pfx tiene permiso rw - - (600) solo lo puede leer root

Como la aplicación autofirma la lanza el usuario necesitamos que ese certificado lo pueda leer cualquier usuario

* pasar los permisos a 644

2.2 Tenemos en Max un script Autofirma-Firefox que reinstala los certificados de comunicación entre el FF y autofirma. Este script hay que actualizarlo ya que las BBDD que utiliza FF en las últimas versiones han cambiado de formato de dbm a sql (es el paso de archivos cert8.db key3.db a cert9.db key4.db)

* propongo actualizar el script añadiendo :

for certdb in $(find $userdir/firefox -maxdepth 2 -name "cert9.db")
  do
    certdir=$(dirname ${certdb});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql{certdir}
  done


3-  Mejoras

3.1 Posible mejora del nuestro paquete autofirma1.6.5max1

El certificado que se instala en el navegador para la comunicación segura entre  autofirma y navegador, AutoFirma.crt, nuestro paquete lo deja en /usr/share/Autofirma.

Creo que sería mejor que lo pusiera en el almacén general /usr/local/share/ca-certificates y luego se lanzara un update-ca-certificates para que quedara a disposición de cualquier aplicación (navegador) como otros certificados. Sería una localización más estándar.


4- Pruebas

4.1 - Con 2.1 y 2.2 se consigue que en modo live funcione autofirma en Firefox haciendo lo siguiente (y en este orden):

- Abrir FF y cerrarlo

- Lanzar Autofirma-Firefox (Oficina- Instalar Autofirma) o Lanzar Autofirma (Oficina- Autofirma) en el menú de la aplicación Herramientas- Restaurar instalación (si esto segundo funciona bien quizá no sea necesario el script Autofirma-Firefox)

- Abrir FF para firmar algo


4.2 - Con 2.1 y 2.2 se consigue que en modo live funcione autofirma en Chromium haciendo lo siguiente (y en este orden):

- Abrir Chromium y cerrarlo

- Lanzar Autofirma (Oficina- Autofirma) en el menú de la aplicación Herramientas- Restaurar instalación

- Abrir Chromium para firmar algo

* En el caso chromium a veces me funciona y otras no. Lo estoy estudiando


5- Lo ideal sería que no hiciese falta abrir el navegador y cerrarlo para crear el perfil del usuario y luego restaurar la instalación de autofirma (lo que hace realmente es instalar el certificado de autofirma en el perfil del usuario) .

Mis preguntas son, si ya tenemos instalados los certificados en el sistema, ¿por qué los navegadores no los leen de ese almacén central?. Si cuando abrimos los navegadores ya tienen certificados de entidades instalados ¿de dónde los sacan?¿podemos poner el de autofirma en ese repositorio?

Tengo alguna idea para FF, que tengo que asentar, pero para chromium ni idea


6- En el CRIF preparé una acción para el navegador de archivos, caja, que permitía que al pulsar con el botón derecho del ratón sobre un pdf saliera una opción de "firmar digitalmente con autofirma"

En el CRIF era muy útil, pero para uso normal ¿os parece útil?. Lo digo porque si es útil se puede intentar incorporar al paquete autofirma de MAX11.


Perdón por lo largo del correo"

A mi me parece un gran correo, nada que perdonar y si de alabar :+1:

**Comment by maxezek** [comment]
José Miguel lo ha logrado en Firefox.

Copio y pego de su correo:

Al final lo he conseguido con Firefox :)

Arrancando desde live y  sin abrir nada más que el terminal:

1)hacemos que todos puedan leer el certificado de autofirma.

sudo chmod 644 /usr/lib/Autofirma/auutofirma.pfx


2) ponemos el certificado de autofirma donde están todos los certificados del sistema


sudo cp /usr/share/Autofirma/Autofirma.crt /usr/local/share/ca-certificates/


3) Actualizamos los certificados


sudo update-ca-certificates


4) Enlazamos una biblioteca

sudo mv /usr/lib/firefox/libnsscckbi.so /usr/lib/firefox/libnsscckbi.so.backup

sudo ln -sf /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so /usr/lib/firefox/libnsscckbi.so


sudo mv /usr/lib/thunderbird/libnsscckbi.so /usr/lib/thunderbird/libnsscckbi.so.backup

sudo ln -sf /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so /usr/lib/thunderbird/libnsscckbi.so


5) Abrimos Firefox instalamos nuestro certificado personal y probamos en:

https://preinterweb.mitramiss.gob.es/autoAfirmaTest/

https://valide.redsara.es/valide/validarCertificado/ejecutar.html


(También podemos ver que entre los certificados de las entidades aparece uno que se llama Autofirma ROOT)


Si los puntos 1 a 5 se pueden dejar hechos en modo live ya estaría el sistema preparado para firmar cualquier cosa en modo live

Cualquier prueba bienvenida


Sobre el punto 4

Lo que hace es sustituir la biblioteca que trae FF y Thmderbird por otra que lee los certificados instalados en /usr/local/share/ca-certificates

https://p11-glue.github.io/p11-glue/p11-kit/manual/trust-module.html

http://www.linuxfromscratch.org/blfs/view/stable/postlfs/p11-kit.html


Si nos decidimos por este cambio en este enlace tenemos como evitar que al actualizar FF se rompa esta configuración:

https://unix.stackexchange.com/questions/479420/apt-get-post-hook-for-specific-package


Saludos

**Comment by maxezek** [comment]
José Miguel lo ha logrado en Firefox.

Copio y pego de su correo:

Al final lo he conseguido con Firefox :)

Arrancando desde live y  sin abrir nada más que el terminal:

1)hacemos que todos puedan leer el certificado de autofirma.

sudo chmod 644 /usr/lib/Autofirma/auutofirma.pfx


2) ponemos el certificado de autofirma donde están todos los certificados del sistema


sudo cp /usr/share/Autofirma/Autofirma.crt /usr/local/share/ca-certificates/


3) Actualizamos los certificados


sudo update-ca-certificates


4) Enlazamos una biblioteca

sudo mv /usr/lib/firefox/libnsscckbi.so /usr/lib/firefox/libnsscckbi.so.backup

sudo ln -sf /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so /usr/lib/firefox/libnsscckbi.so


sudo mv /usr/lib/thunderbird/libnsscckbi.so /usr/lib/thunderbird/libnsscckbi.so.backup

sudo ln -sf /usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so /usr/lib/thunderbird/libnsscckbi.so


5) Abrimos Firefox instalamos nuestro certificado personal y probamos en:

https://preinterweb.mitramiss.gob.es/autoAfirmaTest/

https://valide.redsara.es/valide/validarCertificado/ejecutar.html


(También podemos ver que entre los certificados de las entidades aparece uno que se llama Autofirma ROOT)


Si los puntos 1 a 5 se pueden dejar hechos en modo live ya estaría el sistema preparado para firmar cualquier cosa en modo live

Cualquier prueba bienvenida


Sobre el punto 4

Lo que hace es sustituir la biblioteca que trae FF y Thmderbird por otra que lee los certificados instalados en /usr/local/share/ca-certificates

https://p11-glue.github.io/p11-glue/p11-kit/manual/trust-module.html

http://www.linuxfromscratch.org/blfs/view/stable/postlfs/p11-kit.html


Si nos decidimos por este cambio en este enlace tenemos como evitar que al actualizar FF se rompa esta configuración:

https://unix.stackexchange.com/questions/479420/apt-get-post-hook-for-specific-package


Saludos
