### ISSUE TITLE
Nuevo escritorio para MAX 11

### ISSUE THREAD

**Issue by DaniMAdridlinuX** [max-linux/max-desktop#1034]
Vamos a cambiar algunas cosas en la nueva versión de MAX, estos cambios están avalados por el responsable de MAX:

- [Fondo de Escritorio, los que ya hemos compartido en este ISSUE](https://github.com/max-linux/MAX11-fondos)
- [Tema "Marwaita Light", descargable desde este enlace](https://www.mate-look.org/p/1239855/).
- Iconos Papirus Light, instalable desde Synaptic "papirus-icon-theme"
- La barra de menú pasa a estar en la parte superior con transparencia del 50%
- Incluimos un Dock por defecto en la parte inferior. Si se instala la personalización de Infantil y Primaria ese Dock será sustituido por el de la Personalización.
- Dock configurado como: Transparente, Ocultamiento Inteligente, Retardo de ocultamiento y en mostrar de 1000, Mostrar inconos no anclados, Bloquear iconos
- Por defecto traerá los siguientes iconos:

Enlace a Portal Educamadrid  https://www.educa2.madrid.org/educamadrid/
Enlace a página de MAX https://www.educa2.madrid.org/web/max/inicio
Cliente Owncloud
Firefox
Buscador de aplicaciones
Captura de pantalla
Simple Screen Recorder
Calculadora
Libreoffice
Escritorio

Adjunto vídeo en el que se explica todo

https://user-images.githubusercontent.com/75364104/108979917-6e6b7580-768b-11eb-8861-e0ac5e7b5b74.mp4

**Comment by mariodebian** [comment]
¿cual es el software que ejecuta el panel inferior? no tiene pinta de ser mate-panel ni plank (el que se usa en infantil)

**Comment by DaniMAdridlinuX** [comment]
![Captura de pantalla -2021-02-24 11-03-42](https://user-images.githubusercontent.com/75364104/108984454-3c104700-7690-11eb-8c35-ad3748683a32.png)
 Es Plank 0.11.89

**Comment by DaniMAdridlinuX** [comment]
A lo mejor es que también está activado el dock en Mate Tweak.
En Mate Tweak por defecto queremos que esté activado el led de teclado
![Captura de pantalla -2021-02-24 11-07-48](https://user-images.githubusercontent.com/75364104/108984932-bfca3380-7690-11eb-9e94-04d612f6ca80.png)

**Comment by unquimico** [comment]
Me encanta la nueva apariencia, muy elegante. A lo del dock no sé si me
acostumbraré, pero eso ya son temas personales, seguro que los alumnos y
los profesores lo encuentran muy útil. Y creo que es una gran idea, dado
los tiempos que corren, incluir un icono bien visible de
SimpleScreenRecorder. Una duda: en la barra superior ¿habrá también
iconos o va a servir únicamente para acceder al menú y mostrar
notificaciones y ventanas abiertas? 

Un saludo, 

Miguel Ángel

---
MIGUEL ÁNGEL MAYORAL PÉREZ
miguel.mayoral@educa.madrid.org
IES Victoria Kent, Torrejón De Ardoz
(ies.victoriakent.torrejondeardoz@educa.madrid.org) 

El 24/02/2021 10:32, DaniMAdridlinuX escribió:

> Vamos a cambiar algunas cosas en la nueva versión de MAX, estos cambios están avalados por el responsable de MAX: 
> 
> * Fondo de Escritorio, los que ya hemos compartido en este ISSUE [1]
> * Tema "Marwaita Light", descargable desde este enlace [2].
> * Iconos Papirus Light, instalable desde Synaptic "papirus-icon-theme"
> * La barra de menú pasa a estar en la parte superior con transparencia del 50%
> * Incluimos un Dock por defecto en la parte inferior. Si se instala la personalización de Infantil y Primaria ese Dock será sustituido por el de la Personalización.
> * Dock configurado como: Transparente, Ocultamiento Inteligente, Retardo de ocultamiento y en mostrar de 1000, Mostrar inconos no anclados, Bloquear iconos
> * Por defecto traerá los siguientes iconos:
> 
> Enlace a Portal Educamadrid https://www.educa2.madrid.org/educamadrid/
> Enlace a página de MAX https://www.educa2.madrid.org/web/max/inicio
> Cliente Owncloud
> Firefox
> Buscador de aplicaciones
> Captura de pantalla
> Simple Screen Recorder
> Calculadora
> Libreoffice
> Escritorio 
> 
> Adjunto vídeo en el que se explica todo 
> 
> https://user-images.githubusercontent.com/75364104/108979917-6e6b7580-768b-11eb-8861-e0ac5e7b5b74.mp4 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/max-linux/MAX11-fondos
[2] https://www.mate-look.org/p/1239855/
[3] https://github.com/max-linux/max-desktop/issues/1034
[4]
