### ISSUE TITLE
MAX11 RC1: mejoras, errores, propuestas

### ISSUE THREAD

**Issue by DaniMAdridlinuX** [max-linux/max-desktop#1037]
Una vez liberada la RC1 vamos a recopilar en esta Issue las cuatro pequeñas cosas que hay que cambiar antes de sacar la definitiva

**Comment by DaniMAdridlinuX** [comment]
Algunos comentarios emergentes de las aplicaciones de los menús salen en inglés. Esta es la propuesta de traducción:


ORCA | Presenta la información de la pantalla como voz o Braille
SCREEN MAGNIFIER | Amplía zonas de la pantalla para facilitar la lectura
NOISE TORCH | Suprime ruidos de fondo en tus grabaciones
GEOGEBRA | Software de geometría dinámica
GNU DENEMO | Editor de partituras
GTICK | Metrónomo
SCRATUX | Programa historias, juegos y animaciones interactivas
HANDBRAKE | Reduce de peso tus vídeos, entre otras muchas funciones
OBS | Graba, edita y emite en directo tus vídeos
SIMPLE SCREEN RECORDER | Sencillo grabador de escritorio
XOURNAL++ | Toma notas a mano
IMAGE MAGIC | Visualiza y edita imágenes
OPEN SCAD | Crea objetos 3D sólidos de CAD
TRANSMISSION | Descarga y comparte archivos sobre BitTorrent
ADOBE READ 9 | Visor de PDF
ARDUINO IDE | Crea proyectos de computación
MUSESCORE3 | Crea, escucha e imprime tus partituras
MATE TWEAK | Customiza MAX
MÁS CONTROLADORES | Instala drivers privativos

**Comment by DaniMAdridlinuX** [comment]
CAMBIOS EN MENÚS

Incluir Shutter y OptimizaPDF en el menú Educación a distancia/Programas (mantener también el lugar donde se encuentran ahora).

En "Accesorios" renombrar "Galculator" y poner "Calculadora" 

Incluir Scratux en el menú "Programación"

Ocultar en el menú "Accesorios" el programa "Textinfo"

En "Graficos" Renombrar "ImageMagick (color depth=16)" dejando solo "Imagen Magick"

En "Gráficos" Renombrar "Programa de manipulación de imágenes GNU" dejando solo "GIMP"

En "Internet"  Poner Owncloud con la primera O en mayúscula

**Comment by DaniMAdridlinuX** [comment]
Se acaban de actualizar las slides que aparecen durante la instalación: https://github.com/max-linux/max-desktop/tree/master/ubiquity-slideshow-max/slideshows/ubuntu/slides

Solo hay que cambiar el texto de la primera y en vez de "Desde este DVD" hay que poner "Desde este USB"

![Captura de pantalla -2021-05-30 18-22-00](https://user-images.githubusercontent.com/75364104/120182433-ad6f1100-c20e-11eb-9271-d62c95fca4c8.png)

**Comment by DaniMAdridlinuX** [comment]
Hay que sustituir el logotipo de EducaMadrid por el nuevo en la pantalla de arranque:

![Captura de pantalla -2021-05-30 18-17-45](https://user-images.githubusercontent.com/75364104/120182530-d099c080-c20e-11eb-8a99-2ac1b305084a.png)

**Comment by DaniMAdridlinuX** [comment]
Hay que sustituir el logotipo de EducaMadrid por el nuevo en la pantalla de selección de usuario:

![Captura de pantalla -2021-05-30 18-35-53](https://user-images.githubusercontent.com/75364104/120182678-fcb54180-c20e-11eb-8ae9-8836f724b810.png)

**Comment by DaniMAdridlinuX** [comment]
En la siguiente pantalla hay que sustituir el membrete de la esquina superior derecha por el actual:

![pantalla1](https://user-images.githubusercontent.com/75364104/120183270-c5936000-c20f-11eb-8d6a-e7cfa9bddde4.jpg)

El actual está subido en:

https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS.png

https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS%20copia.eps

**Comment by DaniMAdridlinuX** [comment]
Cuando arrancamos Firefox o Chromium se abre la página: (file://usr/share/doc/max-ubufox/startpage.html y en ella hay que hacer cambios:

- [ ] Donde pone : "Complete su instalación de MAX con las sugerencias de aplicaciones en el portal +Aplicaciones"

Poner: "Complete su instalación de MAX con las sugerencias recopiladas en +Aplicaciones"

- [ ] En esa frase poner solo un hiperenlace, en "+Aplicaciones" y que lleve a https://www.educa2.madrid.org/web/max/-aplicaciones1

- [ ] Donde pone: "No deje de consulttar el Manual de Instalación, configuración y uso básico de MAX incluido en su sistema instalado, el DVD y la WEB de MAX"

Poner: "No deje de consulttar el Manual de Instalación, configuración y uso básico de MAX incluido en su sistema instalado, el USB y la WEB de MAX"

![imagen](https://user-images.githubusercontent.com/75364104/120209787-5fb6d080-c22f-11eb-82cc-dae2a07f725a.png)

**Comment by maxezek** [comment]
>     * [ ]  Hay que sustituir el logotipo de EducaMadrid por el nuevo en la pantalla de selección de usuario:
> 
> 
> ![Captura de pantalla -2021-05-30 18-35-53](https://user-images.githubusercontent.com/75364104/120182678-fcb54180-c20e-11eb-8ae9-8836f724b810.png)

Está en https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png

**Comment by victoramdz** [comment]
La App Image Magick se  ha eliminado del menú

**Comment by maxezek** [comment]
>     * [ ]  En la siguiente pantalla hay que sustituir el membrete de la esquina superior derecha por el actual:
> 
> 
> ![pantalla1](https://user-images.githubusercontent.com/75364104/120183270-c5936000-c20f-11eb-8d6a-e7cfa9bddde4.jpg)
> 
> El actual está subido en:
> 
> https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS.png
> 
> https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS%20copia.eps

Daniel, ¿puedes subir el logo oficial de la DGIS pero para la derecha? Esa versión es para la izquierda

**Comment by maxezek** [comment]
Hay que tener en cuenta que de  #1035 queda mucho sin hacer todavía.

Y que nos pillan cosas como que sale una nueva versión de eXeLearning

**Comment by maxezek** [comment]
Hay que tener en cuenta que de  #1035 queda mucho sin hacer todavía.

Y que nos pillan cosas como que sale una nueva versión de eXeLearning

**Comment by DaniMAdridlinuX** [comment]
> > ```
> > * [ ]  En la siguiente pantalla hay que sustituir el membrete de la esquina superior derecha por el actual:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![pantalla1](https://user-images.githubusercontent.com/75364104/120183270-c5936000-c20f-11eb-8d6a-e7cfa9bddde4.jpg)
> > El actual está subido en:
> > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS.png
> > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS%20copia.eps
> 
> Daniel, ¿puedes subir el logo oficial de la DGIS pero para la derecha? Esa versión es para la izquierda

Desde publicaciones de la CM nos indican que en la actualidad solo hay un logo oficial que puede usarse y es el que he adjuntado en la entrada.

**Comment by DaniMAdridlinuX** [comment]
- [ ] Reportado por Victor Armendariz. 3 iconos repetidos en menú: Sistema/Preferencias, Sistema/Centro de control y Sistema/Preferencias/Aspecto y comportamiento. Para los dos últimos los iconos alternativos pueden ser: /usr/share/icons/ePapirus/64x64/categories/mateconf-editor.svg y /usr/share/icons/ePapirus/64x64/categories/lookswitcher.svg

- [ ] Reportado por Victor Armendariz. 3 iconos repetidos en menú: Gráficos/gThumb, Gráficos/Shotwell y Gráficos/Visor de imágenes Ojo de Mate. Alternativos /usr/share/icons/ePapirus/64x64/categories/photolayouteditor.svg y /usr/share/icons/ePapirus/64x64/categories/portal.svg
 
- [ ] Reportado por Victor Armendariz. No aparece en menú Sistema/Administración/Administración de arranque que es el paquete startupmanager que sin embargo está instalado. ¿Paquete python 2.7? Ver si se puede incluir o directamente sustiturlo por grub-customizer

**Comment by DaniMAdridlinuX** [comment]
- [ ]  Problema con SAMBA descrito por Manuel Galvéz:

Desde Caja normalmente con Control+L escribo:

ftp://(ip servidor) o smb://(ip servidor) y conecta con uno u otro protocolo.

En MAX11 smb no conecta.

He probado "Menú->Lugares->Conectarse al servidor..." con el mismo resultado.

Y en terminal con "mount.cifs" y lo mismo.

SOLUCIÓN: He conseguido conectar haciendo lo siguiente.

Editar /etc/samba/smb.conf archivo (se necesitan permisos de root)

en la [global] sección, agregar la siguiente línea.

client min protocol = NT1

Tras ello se reinicia el servicio.

sudo service smbd restart

- [ ] Error en el prompt de MAX 11. También Manuel Gálvez: en MAX11 live al abrir una terminal en el promp aparece max10.

- [ ] Incluir en caja la extensión de compresión de PDF. Ver https://github.com/maxezek/optimizarPDF La mejor opción creo que es https://github.com/maxezek/optimizarPDF#versi%C3%B3n-como-elemento-del-men%C3%BA-contextual-en-caja. 

- [ ] Reportado por José Angel Navarro. No funciona bien exeLearning. No abre los .elp de MAX 10 por alguna extraña razón. Pero en el sitio oficial ya han hecho paquete .deb oficial y funciona. Sustituir el actual por https://descargas.intef.es/cedec/exe_learning/2.5.1/intef-exe_2.5.1_all.deb

- [ ] CRÍTICO Araword de Arasuite no funciona correctamente #1003 Esto lo arrastramos y esto tiene que funcionar bien. (ver también #1024)

- [ ]  Incluir el reemplazo de tipo de letra para Calibri y Cambria por Carlito y Caladea en libreoffice como en los MAX anteriores

![image](https://user-images.githubusercontent.com/75364104/120608223-3e352f00-c451-11eb-93cf-0d9d89af85f5.png)

- [ ]  Incluir que el programa de correo de LO sea Thunderbird

![image](https://user-images.githubusercontent.com/75364104/120608272-4beab480-c451-11eb-979a-a636a25c9a3e.png)

- [ ]  En Openboard no se ven los colores del lápiz aunque luego funcionan

![image](https://user-images.githubusercontent.com/75364104/120608347-63c23880-c451-11eb-9b7f-2141282d2fa3.png)

**Comment by ignaciogros** [comment]
La nueva versión de eXeLearning (2.6) saldrá dentro de nada. Como tarde, creemos que el 18 de junio. La versión actualmente en pruebas (beta3) está funcionando bien.

**Comment by albertomax** [comment]
En la instalación de profesor aparece en el escritorio el lanzador de TCOS monitor

**Comment by DaniMAdridlinuX** [comment]
- [ ] Al instalar la versión alumno aparece Scratch tanto en el menú de programación como en la barra de juegos. Debe ser sustituido por Scratux que ya está instalado y aparece  en el menú Educación/otras aplicaciones Educativas

![Captura de pantalla -2021-06-07 09-30-12](https://user-images.githubusercontent.com/75364104/120977230-62f01600-c773-11eb-9403-4c47bdfef37c.png)

**Comment by DaniMAdridlinuX** [comment]
- [ ] En la versión alumno en el menú Educación/Música aparace MuseScore y tiene que aparecer MuseScore3 que ya está instalado y se encuentra en Sonio y vídeo

**Comment by mariodebian** [comment]
> * [ ]  En la versión alumno en el menú Educación/Música aparace MuseScore y tiene que aparecer MuseScore3 que ya está instalado y se encuentra en Sonio y vídeo

Actualiza, el menú de mscore se ha eliminado este fin de semana: https://github.com/max-linux/max-desktop/commit/3b4dbd2ad2ea4dad5277325894009492d0fdc933

**Comment by mariodebian** [comment]
> En la instalación de profesor aparece en el escritorio el lanzador de TCOS monitor

TCOS debería funcionar

**Comment by DaniMAdridlinuX** [comment]
> > En la instalación de profesor aparece en el escritorio el lanzador de TCOS monitor
> 
> TCOS debería funcionar

Es una excelente noticia que se mantenga TCOS como programa de control de aula

**Comment by DaniMAdridlinuX** [comment]
> > * [ ]   En la versión alumno en el menú Educación/Música aparace MuseScore y tiene que aparecer MuseScore3 que ya está instalado y se encuentra en Sonio y vídeo
> 
> Actualiza, el menú de mscore se ha eliminado este fin de semana: [3b4dbd2](https://github.com/max-linux/max-desktop/commit/3b4dbd2ad2ea4dad5277325894009492d0fdc933)

Actualizado y perfecto

**Comment by victoramdz** [comment]
> > ```
> > * [ ]  Hay que sustituir el logotipo de EducaMadrid por el nuevo en la pantalla de selección de usuario:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Captura de pantalla -2021-05-30 18-35-53](https://user-images.githubusercontent.com/75364104/120182678-fcb54180-c20e-11eb-8ae9-8836f724b810.png)
> 
> Está en https://user-images.githubusercontent.com/75364104/115219941-47b84100-a108-11eb-9435-71d85f23f4b1.png

Hecho el cambio en el servidor git.

**Comment by victoramdz** [comment]
> > > ```
> > > * [ ]  En la siguiente pantalla hay que sustituir el membrete de la esquina superior derecha por el actual:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![pantalla1](https://user-images.githubusercontent.com/75364104/120183270-c5936000-c20f-11eb-8d6a-e7cfa9bddde4.jpg)
> > > El actual está subido en:
> > > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS.png
> > > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS%20copia.eps
> > 
> > 
> > Daniel, ¿puedes subir el logo oficial de la DGIS pero para la derecha? Esa versión es para la izquierda
> 
> Desde publicaciones de la CM nos indican que en la actualidad solo hay un logo oficial que puede usarse y es el que he adjuntado en la entrada.

Hecho el cambio en el servidor.

**Comment by maxezek** [comment]
> > En la instalación de profesor aparece en el escritorio el lanzador de TCOS monitor
> 
> TCOS debería funcionar

Para mí, es una gran alegría. Solo como control de aula me parece que va finísimo.

**Comment by maxezek** [comment]
Tened en cuenta **max-mate-welcome** tiene issues propias en https://github.com/max-linux/max-mate-welcome/issues

**Comment by victoramdz** [comment]
- [ ]  OBS instalada en MAX con este bug... es la versión 27.0.0 

Se prueba la versión 27.0.1 del repositorio oficial, y este  funciona correctamente. 
https://obsproject.com/wiki/install-instructions#linux

**Comment by DaniMAdridlinuX** [comment]
> > > > ```
> > > > * [ ]  En la siguiente pantalla hay que sustituir el membrete de la esquina superior derecha por el actual:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![pantalla1](https://user-images.githubusercontent.com/75364104/120183270-c5936000-c20f-11eb-8d6a-e7cfa9bddde4.jpg)
> > > > El actual está subido en:
> > > > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS.png
> > > > https://github.com/max-linux/MAX11-fondos/blob/main/CE_DGIS%20copia.eps
> > > 
> > > 
> > > Daniel, ¿puedes subir el logo oficial de la DGIS pero para la derecha? Esa versión es para la izquierda
> > 
> > 
> > Desde publicaciones de la CM nos indican que en la actualidad solo hay un logo oficial que puede usarse y es el que he adjuntado en la entrada.
> 
> Hecho el cambio en el servidor.

Acaba de cambiar el nombre de la Consejería y hay que actualizarlo en este fondo.


![DG_IIySS](https://user-images.githubusercontent.com/75364104/122899886-822e9c00-d34c-11eb-9d6f-55b26b3b0c52.jpg)

**Comment by DaniMAdridlinuX** [comment]
- [ ] Ya tenemos la nueva versión de ExeLearning y tendría que venir instalada en MAX11

https://exelearning.net/descargas/

**Comment by DaniMAdridlinuX** [comment]
- [ ] El enlace al "Manuel de instalación, configuración y uso básico de Max" lleva a max.educa.madrid.org/manual y allí se abre el manual de MAX 9.0. En cuanto tengamos el manual del 11.0 habrá que hacer que lleve allí.

![Captura de pantalla -2021-06-23 16-24-18](https://user-images.githubusercontent.com/75364104/123114386-8c7d9280-d43f-11eb-88af-f0eeff6a3c8c.png)

**Comment by DaniMAdridlinuX** [comment]
En cuanto tengamos la documentación de MAX 11.0 hay que actualizar los dos enlaces del menú MAX y EducaMadrid/Max/

Manual de instalación y uso (internet)
Manual de instalación y uso (Local)

![Captura de pantalla -2021-06-23 16-26-55](https://user-images.githubusercontent.com/75364104/123114935-fbf38200-d43f-11eb-878c-ddf9e91e07b6.png)

**Comment by victoramdz** [comment]
>     * [ ]  Hay que sustituir el logotipo de EducaMadrid por el nuevo en la pantalla de arranque:
> 
> 
> ![Captura de pantalla -2021-05-30 18-17-45](https://user-images.githubusercontent.com/75364104/120182530-d099c080-c20e-11eb-8a99-2ac1b305084a.png)

Fondo de instalación

**Comment by DaniMAdridlinuX** [comment]
- [ ] Al pasar el cursor del ratón por el menú MAX y EducaMadrid/EducaMadrid/Comunidades Virtuales aparece el mensaje emergente "Enlace a los espacios de formación en EducaMadrid" y debería poner "Selección de Comunidades Virtuales en EducaMadrid"

![Selección_015bhh](https://user-images.githubusercontent.com/75364104/123691336-c7276680-d855-11eb-89fe-7f4ff4c1ca08.png)

**Comment by ignaciogros** [comment]
@mariodebian:

Adjunto un zip con los estilos MAX y MAX Institucional actualizados y un archivo adicional: [exe.zip](https://github.com/max-linux/max-desktop/files/6740041/exe.zip)

**Cambios:** 
1. Imagen de cabecera en sitio web (logo oficial de MAX en MAX Institucional, y pingüino del fondo de escritorio de MAX 11 en ambas versiones).
2. Actualización de los datos de la versión.
3. Nuevo logo de la Plataforma Tecnológica EducaMadrid (sólo en MAX Institucional cuando añades un pie de página desde la pestaña Propiedades de eXe).
4. Nuevo favicon de EducaMadrid (sólo en MAX Institucional).
4. Revisión de los botones de paginación.

**Avisos importantes:**

- El estilo MAX (no oficial) ya está subido al repositorio de estilos de eXe, así que se podrá descargar desde la aplicación.
- He visto que en debian/install hay un "NO FUNCIONA" en MAX_institucional. Prueba a copiar los estilos a "exe/webui/style" además de a "usr/share/exe/style" (se guardan en dos ubicaciones).
- El zip incluye un fichero a copiar en "exe/webui/scripts/exe_lightbox". Pisa el fichero de la 2.6, por favor. Sirve para corregir este fallo: al añadir un enlace a un vídeo de la Mediateca con rel="lightbox" no funcionaba la pantalla completa.

Me hubiera gustado llegar a renovar el estilo, pero ya no hay tiempo. Espero que los cambios funcionen bien. Muchas gracias.
