### ISSUE TITLE
MAX11 y anteriores: Frase tipo del visor de tipografías

### ISSUE THREAD

**Issue by DaniMAdridlinuX** [max-linux/max-desktop#1042]
El visor de tipografías usa la siguiente frase de ejemplo:

"Jovencito empozoñado de whisky: ¡qué figurota exhibe!"

Sustituir por otra frase más adecuada para una distribución educativa como por ejemplo:

""Empeñado en ir a Washington: ¡qué gran viaje!

**Comment by victoramdz** [comment]
Este texto se encuentra en los binarios  libpango-1.0.so.0.4400.7 de 32 y 64btis respectivamente...
Al descargar el código de la  aplicación pango, se modifica el archivo: 
/pango1.0-1.44.7/pango/pango-language-sample-table.h 
al volver a compilar, se toma el fichero modificado y se cambia por el original 

Ruta: /usr/lib//usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.4400.7

**Comment by mariodebian** [comment]
Subido libpango 1.44.7-2ubuntu4max1
