### ISSUE TITLE
MAX11: nuevos apartads en el menú

### ISSUE THREAD

**Issue by DaniMAdridlinuX** [max-linux/max-desktop#1043]
Vamos a incluir un par de apartados nuevos en los menús. Estamos a la espera de diseñar los iconos de ambos pero por ahora lo dejamos documentado hasta que se diseñen:

- [x] Educación a distancia/Herramientas WEB/Comparti2   llevará a https://comparti2.educa.madrid.org/  En el menú emergente que aparezca "Comparte archivos de gran tamaño"
- [x] MAx y EducaMadrid/EducaMadrid/Portal CAU EducaMadrid  llevará a https://portalcau.educa.madrid.org/login?back_url=http%253A%252F%252Fportalcau.educa.madrid.org%252F  "Portal CAU EducaMadrid"

**Comment by victoramdz** [comment]
Actualizado en el servidor.

**Comment by mariodebian** [comment]
Hecho en 003bbe30ea01a33118f021b018b26bf7a080eadd
