### ISSUE TITLE
MAX 11: instalar el paquete v4l2loopback-dkms

### ISSUE THREAD

**Issue by DaniMAdridlinuX** [max-linux/max-desktop#1046]
Para activar la cámara virtual en OBS es necesario instalar desde Synaptic el paquete:

 v4l2loopback-dkms 

Al hacerlo se instalan otros dos paquetes

dkms
dctrl-tools 

¿Se pueden instalar estos tres paquetes con una actualización para que el usuario no tenga que realizar ese proceso y le aparezca la opción de cámara virtual en OBS?

**Comment by victoramdz** [comment]
subido [ 3801ff5](https://github.com/max-linux/max-desktop/commit/303c16694f2a7c9b4023f6af8bb610a36b5e3366)
