### ISSUE TITLE
MAX 11.x: Siguen los problemas con homealumno que vienen de #770 #980 #983 

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1050]
Tenemos que resolver de nuevo todos estos problemas.

Empiezo por el #770 y #980 que creo que he encontrado el problema del **fondo de pantalla**. Copio y pego:

> Aprovecho este issue para incluir la solución al problema de #980 
No funciona que se mantenga la pantalla porque el esquema utilizado en 6e469d7 es:
línea 204 data=[{'key':'/org/mate/desktop/background/picture-filename',
Cambiar key /org/mate/desktop/background/picture-filename
a
/org/mate/background/picture-filename
Por lo menos funciona:
gsettings set org.mate.background picture-filename 'path a la imagen de fondo de pantalla'

Pero  en #980 la doble ejecución de **self.exe("xdg-user-dirs-update --force")** no hace nada. No se recuperan los directorios.

Y de #983 https://github.com/max-linux/max-desktop/commit/78e0e9eb8f883e4b64ab7dae36c995144a795986 no resuelve que la cajonera se vea transparente en el escritorio de alumno.

**Comment by maxezek** [comment]
Creo que ya se que va pasando en #983. En la versión de MAX 11 no se queda comentado compiz = 1 en **profiles.ini** Pero es que lo que necesita es que este a 0.
Y tampoco que se ha incluido en exceptions a Plank como decía Victor en https://github.com/max-linux/max-desktop/issues/983#issuecomment-562080998
Tiene que empaquetarse homealumno-gui con un profiles.ini que incluya

exceptions = .drmc, .config/plank, .cache/plank, .local/share/plank
compiz = 0

**Comment by victoramdz** [comment]
cambios hechos subido al repo  https://github.com/max-linux/max-desktop/commit/9e2ecc779f21b3bdc7b05b1fb1332420c5b2ed90

**Comment by victoramdz** [comment]
subido cambio para fondo de pantalla. https://github.com/max-linux/max-desktop/commit/4ad81410933aff4ee676cf860d03e704f3390bd9
