### ISSUE TITLE
MAX 11 y 11.5: Error en el enlace de la página de inicio de Firefox

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1052]
Se trata de:

![imagen](https://user-images.githubusercontent.com/6005738/153923396-dce78007-dcdf-41de-b594-6894b6843aac.png)

En enlace de +Aplicaciones apunta mal.

Debe ira a https://www.educa2.madrid.org/web/max/aplicaciones

**Comment by victoramdz** [comment]
subido [db4ea74](https://github.com/max-linux/max-desktop/commit/db4ea7416156e6feed1e4a9a7e9dc421255f7d34)
