### ISSUE TITLE
check-efi-install detección disco a partir de partición

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#1054]
https://github.com/max-linux/max-desktop/blob/0b79148897cf40d757bd4294af638d1da38750ff/max-skel-conf/usr/sbin/check-efi-install#L79

El código correcto para sacar el disco a través de una partición es:

```
EFI_DISC=$(grub-probe --device $MAX_PART --target=disk)
```

Está en dos sitios.

**Comment by victoramdz** [comment]
subido https://github.com/max-linux/max-desktop/commit/0b79148897cf40d757bd4294af638d1da38750ff
