### ISSUE TITLE
MAX 11.5: Cambio en el menú REA

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1055]
Se trata de añadir enlaces al menú **Educación > REA** 

Ahora solo está eXeLearning. Sería añadir enlaces a:

Nombre del submenú ---------------> Comando

Proyecto EDIA                                  x-www-browser  https://cedec.intef.es/proyecto-edia/
Itinerarios didácticos                         x-www-browser  https://intef.es/recursos-educativos/recursos-para-el-aprendizaje-en-linea/itinerarios-didacticos/
eScholarium                                     x-www-browser  https://escholarium.educarex.es/LMS/index.php?u=11&catalog
CREA                                               x-www-browser  https://emtic.educarex.es/recursos-crea
Europeana                                        x-www-browser https://www.europeana.eu/es

**Comment by victoramdz** [comment]
subido https://github.com/max-linux/max-desktop/commit/112c60c856227400d88484d56ce8095bdf2ee2e4
