### ISSUE TITLE
MAX 11.5: Errores de la iso 

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1056]
Reportado por Fernando Lisón.

Encantado con MAX 11.5. Algunas cosillas:

**En el grub aparece todavía "MAX 11.0"**
Cada vez que accedes como **alumno** aparece un mensaje de **RfKill** que pide la contraseña de administrador. También como **profesor** (José Miguel)
Cada vez que accedes como **alumno tienes que meter la clave de la wifi** (¿Está relacionado con lo anterior?).

Gracias

**Comment by victoramdz** [comment]
subido https://github.com/max-linux/max-desktop/commit/56f52477c1293c51814eb7873091ffd47456efd6
