### ISSUE TITLE
Arduino - actualizar en max11 a la ultima version estable

### ISSUE THREAD

**Issue by jasaleyva** [max-linux/max-desktop#1059]
-querrría que se actualizase la version de arduino que hay en la distro de max 11 a la última versión estable: 
Arduino IDE 1.8.19

**Comment by jasaleyva** [comment]
Muchos profes empezamos a trabajar  en proyectos IoT con placas de control tipo ESP8266 y ESP32. Para ello usamos el IDE de programación de Arduino, pero la versión instalada en MAX11 está obsoleta y no admite otras placas diferentes a las de Arduino.

**Comment by victoramdz** [comment]
Se actualiza Arduino Version 1.8.19 
Como el cambio de version es muy alta es necesario realizar un dist-upgrade

**Comment by jasaleyva** [comment]
En primer lugar quiero agradeceros el trabajo de actualizar Arduino.
Acabo de actualizar MAX11.5 con dist-upgrade para probar Arduino 1.8.19 y he encontrado que no termina las compilaciones.
Método probado: 
1 - cargo un ejemplo que use alguna librería, desde Archivo/Ejemplos. 
2 - compruebo que tengo esa librería instalada en Programa/Incluir Librería/Adm Bibliotecas
3 - Compilo y obtengo error que muestro a continuación...
----------------------------------------------------------------------------------------------------------------------------
Atención: platform.txt del núcleo 'Arduino AVR Boards' contiene compiler.path={runtime.tools.avr-gcc.path}/bin/ desfasada, automáticamente convertida a compiler.path=/usr/bin/. Considera el actualizar este núcleo.
/home/madrid/Arduino/libraries/Servo/examples/Knob/Knob.ino:10:19: error fatal: Servo.h: No existe el archivo o el directorio
compilación terminada.
exit status 1
Error compilando para la tarjeta Arduino Uno.
----------------------------------------------------------------------------------------------------------------------------
He actualizado el S.O. y luego 
He probado a instalar la librería a traveś de un .zip y persiste el mismo error de compilación.

He probado con los siguientes archivos de ejemplo y todos fallan al compilar: 
 - /ThingSpeak/examples/ArduinoEthernet/ReadField/ReadField.ino
 - /Servo/examples/Knob/Knob.ino
 - /TimerOne/examples/FanSpeed/FanSpeed

ME GUSTARÍA REABRIR ESTE ISSUE Y QUE LE ECHÁSEIS UN VISTAZO.

**Comment by victoramdz** [comment]
Por el tipo de error, puedes hacer la siguiente comprobacion. 
Abre arduino > Herramientas > placa > Gestor de Tarjetas > Actualiza  la Arduino AVR Board, para que quede en la versin 1.8.6
reinicia y vuelve a probar. 
Saludos.

**Comment by jasaleyva** [comment]
Hola Victor, gracias por tu rápida respuesta.
Acabo de actualizar Arduino AVR Boards a la versión 1.8.6. he reiniciado pero nada, persiste el mismo error.
Tengo instalado desde /descargas otro Arduino 1.8.19 que funciona bien y he comprobado que en el archivo platform.txt tiene como parámetro compiler.path={runtime.tools.avr-gcc.path}/bin/ , en lugar de compiler.path=/usr/bin/ así que lo he cambiado en el compiler.path del arduino problemático y..... persiste el mismo error.
He probado en dos equipos, PC y portátil, ambos con MAX11.5 y en ambos falla Arduino 1.8.19.
¿alguna idea más por probar?
Gracias por tu ayuda.

**Comment by victoramdz** [comment]
Solventada esta incidencia, se vera reflejado  en la  la próxima actualización de max 11.5.1
