### ISSUE TITLE
MAX 11.5 y anteriores: Actualizar exelearning a la versión 2.7

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1060]
Además, esta vez si incluyen versión .deb con lo que será más fácil incluirla en los repos de MAX.

https://exelearning.net/descargas/

https://github.com/exelearning/iteexe/releases/tag/2.7

**Comment by victoramdz** [comment]
Subido https://github.com/max-linux/max-desktop/commit/1095d47f6426bcb753c538fbd145fbd395b0e9c7
