### ISSUE TITLE
MAX 11 y siguientes: actualizar AutoFirma

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#1069]
Tenemos nueva versión de autofirma:

[https://firmaelectronica.gob.es/Home/Descargas.html](https://firmaelectronica.gob.es/Home/Descargas.html)**

**Comment by DaniMAdridlinuX** [comment]
Comenzamos pruebas de funcionamiento en MAX 11.5.1

**Comment by victoramdz** [comment]
subidos en los repos de  MAX 11 y 12
