### ISSUE TITLE
en xfce en resoluciones 4:3 las ventanas se abren por detrás de la barra superior de programas (infantil-primaria) y esto dificulta moverlas/cerrarlas, etc...

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#456]
en xfce en resoluciones 4:3 las ventanas se abren por detrs de la barra superior de programas (infantil-primaria) y esto dificulta moverlas/cerrarlas, etc...

**Comment by DaniMAdridlinuX** [comment]
MAX11 ya no lleva xfce
