### ISSUE TITLE
generador de discos de arranque mete syslinux 3.6 en vez de la 4

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#500]
Arrancando en dvd-live lo hace bien, pero desde Max 7.5 instalado parece que no mete la versión correcta de syslinux

**Comment by javierpuche** [comment]
en max8-alpha1 sigue habiendo un problema de versión de syslinux, vamos con la 3.63 y en algunos equipos se queda en pantalla negra y boot:  (luego pulsando live sí arranca)

**Comment by mariodebian** [comment]
Subidas nuevas versiones en 7.5 y 8.0 que detectan MAX 8.0
