### ISSUE TITLE
Calibración de pantalla táctil en Toshiba de dotación oficial

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#535]
En un tablet M400 la relación de aspecto es 4:3 con lo que su uso como PDI en un cañón estandar es directo.
Sin embargo, en un M700 la relación de aspecto es panorámica y no su proyección con un cañón estandar no sigue bien el lápiz. Si se cambia en el portátil a 4:3 el problema sigue manteniéndose.
Se requiere un sistema de calibración de la pantalla para que pueda ser usada como PDI en relación 4:3 que es la que usan la mayoría de cañones instalados.

**Comment by javierpuche** [comment]
probar en max8
