### ISSUE TITLE
"Crea lanzador" en nautilus

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#571]

**Comment by javierpuche** [comment]
La ruta cambió a .local/share/nautilus/scripts y Mario la actualizó, en 14.04 el problema es que sale en el menú contextual de fichero y de carpeta, pero no sobre el fonde de escritorio ¿? (pero sí si abrimos carpeta personal y ahí botón derecho encima de la carpeta escritorio)
Lo voy mirando, prioridad baja.

**Comment by javierpuche** [comment]
Parece que el paquetes nautilus-actions ofrece más posibilidades y un comportamiento más homogéneo (o mejor integrado) Lo vamos evaluando

**Comment by javierpuche** [comment]
Integrada nueva extensión de Rober
