### ISSUE TITLE
menú de inicio tarda mucho la primera vez (solucionado en gnome, falta xfce)

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#590]
Es un viejo problema conocido, en algún momento se mejoró  pero no sé si hemos perdido  esa mejora, tarda mucho sólo la primera vez, aunque sea media hora después de haber encencido el equipo, tanto en Xfce como en Gnome. Lo ideal sería hacer una precarga de las operaciones que tenga que hacer esa primera vez.

**Comment by javierpuche** [comment]
Esto tampoco funciona:
http://ubuntuforums.org/showthread.php?t=2196413

# This file should be placed in your (x)ubuntu home folder
# and name ".gtkrc-2.0"
#
gtk-menu-popup-delay=0
gtk-menu-popdown-delay = 0
gtk-menu-bar-popup-delay = 0
gtk-enable-animations = 0
gtk-timeout-expand = 10

**Comment by mariodebian** [comment]
Los menús en GNOME son GTK3, dudo que el archivo funcione en GNOME

¿En XFCE van lentos?

**Comment by javierpuche** [comment]
Ups, no había caído. Sí, tanto en nuestro gnome3-fallback como en xfce la primera pulsación en la estrellita del menú de inicio, tarda mucho en desplegarse, da lo mismo que se haga media hora después de estar trabajando, en unos equipos más que en otros, pero hay algo que ralentiza mucho esa primera pulsación.

**Comment by javierpuche** [comment]
Con el strace  (sudo strace -e open -p XXXX > 2strace-gnome-panel.log 2>&1  ) veo que la primera pulsación en la estrellita de inicio con gnome-panel o xfce4-panel, provoca más de novecienteas llamadas de sistema de abrir ficheros (open) incluso llegando a 1500, que en una segunda pulsación se reducen a muy pocas, e incluso 0.  Mientras analizo el código de los paneles para ver si se puede añadir la precarga que realiza classicmenu-indicator, veo:
1.- Que el classicmenu-indicator hace lo mismo que la estrellita de inicio, habría que probarlo intensivamente pero podría sustituir tanto al menú en gnome3-fallback como en xfce, retocando la configuración.
2.- Que classicmenu-indicator solo realiza la precarga cuando está activo en el panel, al quitarlo del panel, aunque se invoque vía /usr/share/pyshared/classicmenu_indicator/cmindicator.py  no provoca tal precarga

 esto mirando cómo hacer que se lance y se termine al arrancar la sesión que podría ser un apaño temporal

**Comment by javierpuche** [comment]
Dejando a parte xfce, solo en gnome3-fallback comparando el código de panel-menu-button.c con panel-menu-bar.c (ambos de gnome-panel)  vemos que el segundo en el init incluye más acciones, ahora es ver si esas acciones se pueden provocar desde panel-menu o en un widget que no se vea.
```
static void
panel_menu_bar_init (PanelMenuBar *menubar)
{
        menubar->priv = PANEL_MENU_BAR_GET_PRIVATE (menubar);

        menubar->priv->info = NULL;

        menubar->priv->applications_menu = create_applications_menu ("applications.menu", NULL, TRUE);

        menubar->priv->applications_item = panel_image_menu_item_new ();
        gtk_menu_item_set_label (GTK_MENU_ITEM (menubar->priv->applications_item),
                                 _("Applications"));
        menubar->priv->image = gtk_image_new_from_icon_name (PANEL_ICON_MAIN_MENU,
                                                             panel_menu_bar_object_icon_get_size ());

        gtk_menu_item_set_submenu (GTK_MENU_ITEM (menubar->priv->applications_item),
                                   menubar->priv->applications_menu);
        gtk_menu_shell_append (GTK_MENU_SHELL (menubar),
                               menubar->priv->applications_item);
        gtk_widget_show (menubar->priv->applications_item);

        menubar->priv->places_item = panel_place_menu_item_new (FALSE, TRUE);
        gtk_menu_shell_append (GTK_MENU_SHELL (menubar),
                               menubar->priv->places_item);
        gtk_widget_show (menubar->priv->places_item);

        panel_menu_bar_setup_tooltip (menubar);
}
```
vs.
```
static void
panel_menu_button_init (PanelMenuButton *button)
{
        button->priv = PANEL_MENU_BUTTON_GET_PRIVATE (button);

        button->priv->toplevel          = NULL;
        button->priv->settings_instance = NULL;

        button->priv->menu_path   = NULL;
        button->priv->custom_icon = NULL;
        button->priv->tooltip = NULL;

        button->priv->path_root       = LAST_MENU;
}
```

sí, porque en panel-menu-button.c  se llaman (ej: create_applications_menu) pero desde panel_menu_button_popup_menu

**Comment by javierpuche** [comment]
El atajo que describen aquí (http://ubuntuforums.org/showthread.php?t=89136&highlight=Possible+to+change+%26quot%3B%26quot%3BApplications-Places-System%26quot%3B%26quot%3B+menu%3F&page=2)   es dejar solo el menubar y cambiar las traducciones para que no ocupen tanto en el menú, pero no deja de ser otra ñapa más ...

**Comment by javierpuche** [comment]
Solucionado para gnome
En panel-menu-button.c (del gnome-panel-3.8.0 que llevamos en max8) añadir:
línea 281 o cualquier anterior fuera de cualquier función, declaración de función forward:
static GtkWidget *
panel_menu_button_create_menu (PanelMenuButton *button);

Línea 303 (final de la función panel_menu_button_parent_set  justo antes de cerrar llave)
panel_menu_button_create_menu(button);

 Básicamente llamar a la función que crea el menú en un momento dado de la inicialización (encontrado a palos de ciego, no iba bien en el init ni en algún otro sitio probado) Pendiente de ver que no tiene efectos laterales.

 Ahora a mirar en xfce y en max7.5 que ahí no consigo compilarlo. Le escribo al desarrollador para ver si pueden añadir algo más elegante en este sentido y no tengamos que meter versión.

**Comment by mariodebian** [comment]
Subido en 7.5 y 8.0 con este parche

```
--- gnome-panel-3.8.0.orig/gnome-panel/panel-menu-button.c
+++ gnome-panel-3.8.0/gnome-panel/panel-menu-button.c
@@ -277,6 +277,9 @@ panel_menu_button_associate_panel (Panel
 	panel_applet_menu_set_recurse (GTK_MENU (button->priv->menu), "menu_panel", panel_widget);
 }
 
+static GtkWidget *
+panel_menu_button_create_menu (PanelMenuButton *button);
+
 static void
 panel_menu_button_parent_set (GtkWidget *widget,
 			      GtkWidget *previous_parent)
@@ -297,6 +300,9 @@ panel_menu_button_parent_set (GtkWidget
 
 	if (GTK_WIDGET_CLASS (panel_menu_button_parent_class)->parent_set)
 		GTK_WIDGET_CLASS (panel_menu_button_parent_class)->parent_set (widget, previous_parent);
+
+	/* init menu to cache it */
+	panel_menu_button_create_menu (button);
 }
 
 static void
```

**Comment by javierpuche** [comment]
lo reabro para acordarme de hacerlo también en xfce si saco tiempo

**Comment by DaniMAdridlinuX** [comment]
MAX11 ya no lleva xfce
