### ISSUE TITLE
soporte UEFI en 32 bits para MAX 8

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#599]
Ubuntu ya tiene los paquetes grub-efi-ia32_1.98-1ubuntu13_i386.deb, y habla del efi en 32 bits (https://help.ubuntu.com/community/UEFIBooting)  hay que ver si de verdad permiten el arranque uefi en equipos de 32 bits (lo utilizan para algunos modelos de mac) e incorporarlo
 Una referencia interesante:
http://askubuntu.com/questions/392719/32-bit-uefi-boot-support

 También investigar si ya funciona el grub firmado con secureboot.

**Comment by DaniMAdridlinuX** [comment]
Ya no damos soporte para MAX8
