### ISSUE TITLE
añadir ktechlab

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#605]
http://foros.educa.madrid.org/viewtopic.php?f=28&t=2702&sid=db05e3af8a4e364e61e4f0bc00433c16

Localizar las modificaciones que se hicieron y ver si podemos meterlo, si no es posible lo reintentaremos para la max8

**Comment by javierpuche** [comment]
Activar por defecto el plugin de componentes electrónicos activado por defecto, si no queda todo vacío y no se ve cómo utilizarlo, aunque dice Ezequiel que al hacer esto dejan de ir la simulación de los PIC

**Comment by mariodebian** [comment]
Añadir una cosa que rompe otra... ktechlab está muy verde y el viejo no se puede instalar (depende de libs muy obsoletas de QT), aplazado

**Comment by mariodebian** [comment]
Subido nuevo snapshot ktechlab

**Comment by maxezek** [comment]
Está en inglés. Por si acaso no lo reabro pero adjunto los ficheros de ayuda de contexto y el .po de la traducción de está versión
[CMakeLists.txt](https://github.com/max-linux/max-desktop/files/1887994/CMakeLists.txt)

[ktechlab.po.txt](https://github.com/max-linux/max-desktop/files/1888004/ktechlab.po.txt)
[help-es.txt](https://github.com/max-linux/max-desktop/files/1888005/help-es.txt)
Estos últimos sin .txt que he añadido para que github me los admita.

Sería bueno recuperar el help-es de contexto que teníamos en nuestro viejo ktechlab de MAX... No se si MAX 5 ¿?
