### ISSUE TITLE
Actualizar python-exe

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#608]

**Comment by javierpuche** [comment]
Idem para la versión 2.0.3 en max 8 y si de paso se compila para la 7.5 genial.

**Comment by mariodebian** [comment]
Como el paquete ha cambiado de nombre (intef-exe) en 8.0 ira este por defecto pero en 7.5 prefiero no actualizar max-meta/max-desktop-common y que sea el usuario el que lo actualice.
