### ISSUE TITLE
actualizar geogebra

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#619]
Cuando se pueda, no es urgente. Puede ir a extras.

 En http://wiki.geogebra.org/en/Reference:GeoGebra_Installation habla de sus repos.

Ahora tienen el paquete geogebra5 como rama estable, distinto del geogebra44, la gente que trabaja con el (Pablo) nos dirá en breve si podemos borrar la 4 que tenemos ahora o mantener las dos.

 Los fuentes están aquí: http://dev.geogebra.org/trac   Bajo licencia http://www.geogebra.org/download/license.txt  La rama trunk es la válida estable de la 5 http://dev.geogebra.org/trac/browser/trunk
(svn co https://dev.geogebra.org/svn/trunk/geogebra )

 Las instrucciones para generarlo va todo sobre Eclipse, lo voy mirando y cuento.

En un ticket previo teníamos apuntado:

De aquí: http://download.geogebra.org/installers
Y evaluar lo necesario para que funcione bien http://web.geogebra.org/chromeapp/

**Comment by javierpuche** [comment]
Tenemos ya autorización escrita para meter la última versión de Geogebra en nuestros repositorios, así que sí que podemos hacer lo de pillar los recompilados, rehacerlo y probarlos.

**Comment by mariodebian** [comment]
duplicado #642
