### ISSUE TITLE
Quitar paquetes para MAX 8.0 basic

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#644]
Quitar paquetes y dependencias de:

- [x] Moodle, Apache, PHP y MySQL
- [x] JClic, HotPotatoes, edilim, malted
- [x] Komposer, Anjuta, Glade, gTranslator, Meld
- [x] Empathy, gwibber, pidgin
- [x] Ekiga
- [x] Imágenes Scratch
- [x] fprint
- [x] Amazon
- [x] Ardesia, curtain, spotlighter, whyteboard, python-whiteboard, NoteLab
- [x] Robolinux RCX y Robolinux NXT
- [x] PSe Int
- [ ] xdiagnose, Servicio Landscape, dvdisaster, 
- [x] kturtle
- [x] gambas3

**Comment by javierpuche** [comment]
hecho
