### ISSUE TITLE
Cuentas de usuario en Xfce

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#645]
En gnome en Administración llevamos Cuentas de Usuarios y Usuarios y Grupos,  en xfce solo Usuarios y Grupos, desde ahí no se puede fijar el inicio automático.

**Comment by mariodebian** [comment]
Arreglado en max-menus_8.0.max22 https://github.com/max-linux/max-desktop/commit/a63759b25118c50d0ad8cc43410b92f6d7a61d89
