### ISSUE TITLE
Gio FileMoniotr js-ctypes

### ISSUE THREAD

**Issue by Noitidart** [max-linux/max-desktop#653]
Absolutely awesome work with the GIO file moniotring system!! This is some really great work.

I was trying to also write this up in js-ctypes but was having some issues.

It watches the desktop.

https://github.com/Noitidart/jscFileWatcher/blob/gio/modules/workers/FSWatcherWorker.js#L132-165

That block runs fine, no errors. Then I make a new folder on desktop and firefox crashes.

May you please take a look for me to guide me as to why this is happening please.

My types are defined here: https://github.com/Noitidart/jscFileWatcher/blob/gio/modules/ostypes_gio.jsm#L62

If you download and install that addon, then create a file on desktop you will see same crash. I am doing this to bring a js-ctypes file watcher api to firefox here is the bugzilla topic: https://bugzilla.mozilla.org/show_bug.cgi?id=992896#c24

Thanks very much for whatever advice you can share! :) Keep up the awesome js-ctypes work!

If you are available to chat I would really appreciate it, I'm on the mozilla irc channel #jsctypes here: https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.mozilla.org%2F%23jsctypes

Thank you!

**Comment by Noitidart** [comment]
This topic is for @mariodebian who wrote this here please: https://github.com/max-linux/max-desktop/blob/ba002b6de880af9ec02e79fa9b7f194cc7cb5e91/max-ubufox/res/libs/gio.jsm#L202

Just a small bump because I was stuck :(

If you could please advise that would be real awesome!! Thanks!

**Comment by mariodebian** [comment]
max-ubufox package is a fork of Ubuntu's ubufox: https://launchpad.net/ubufox

You should contact them because max-ubufox only changes Firefox about:start page, don't touch GIO stuff

**Comment by Noitidart** [comment]
Thanks very much @mariodebian !
