### ISSUE TITLE
Enlaces firefox de barra de marcadores

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#658]
Los enlaces a Aula Virtual y Documentación en la barra de marcadores de Firefox no llevan a ningún sitio.

**Comment by javierpuche** [comment]
El de Documentación sí funciona, el del aula virtual ha cambiado, ahora es http://aulavirtual.educa.madrid.org/madrid_linux/   pero creo que mejor quitarlo, no la tenemos muy al día, mejor sustituir ambas por la web de max y punto, que puede ser max.educa.madrid.org que redirije a http://external.educa2.madrid.org/web/max/
