### ISSUE TITLE
Icono Equipo en GNOME

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#659]

**Comment by javierpuche** [comment]
Ha desaparecido en la 14.04, ni siquiera gnome-tweak-tool muestra la opción, poniendo un lanzador sí lo muestra, tipo:
[Desktop Entry]
Version=1.0
Type=Application
Name[es]=Equipo
GenericName[es]=Equipo
Comment=Equipo
Exec=nautilus computer://
Icon=computer
Terminal=false
X-MultipleArgs=false
StartupNotify=true

**Comment by mariodebian** [comment]
Ya lo teníamos para Xfce: https://github.com/max-linux/max-desktop/blob/master/max-skel-conf/etc/skel/Escritorio/Equipo.desktop

Paquete max-skel-conf

Hay que cambiarlo para que valga para los dos y lance thunar/nautilis dependiendo del escritorio en el que se pulse
