### ISSUE TITLE
Quitar kwallet

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#662]

**Comment by mariodebian** [comment]
¿Donde esta kwallet?
No lo veo en ningun menu

Pertenece a kde-runtime y no se puede quitar sin quitar todo lo que dependa de KDE

**Comment by javierpuche** [comment]
Aparece al lanzar programas que piden usuario y contraseña (marble, pysiogame... )  es para guardar conjuntos de identificaciones bajo una contraseña común, miro si se puede simplemente quitar el que se lance, aunque hay todo un mecanismo de enlace de cada apliación con kwallet que tendré que evaluar. De momento se queda como está.

**Comment by javierpuche** [comment]
Podemos probar a poner en el skel, .kde/share/config/kwalletrc  y ver qué pasa, yo lo voy probando, quedaría:

[$Version]
update_info=kwallet-4.13.upd:kde4.13

[Wallet]
Close When Idle=false
Enabled=false
First Use=false
Use One Wallet=true
