### ISSUE TITLE
terminal xfce en gnome en max8-alpha1

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#671]
en herramientas de sistema estando en entorno gnome aparece el Terminal de xfce

**Comment by javierpuche** [comment]
Sería cuestión de poner 
OnlyShowIn=XFCE 
en el lanzador /usr/share/applications/xfce4-terminal.desktop
y añadir System a Categories del gnome-terminal.desktop

**Comment by mariodebian** [comment]
Sólo se va a llevar un terminal gnome-terminal y xfce4-terminal entra en conflicto con max-xfce-desktop
