### ISSUE TITLE
quitar carpeta entorno-squeak del menú de educación en max8-alpha1

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#673]
quitar carpeta entorno-squeak del menú de educación en max8-alpha1

**Comment by mariodebian** [comment]
Dentro de esa carpeta es donde está Scratch

¿A donde movemos ese menú?

**Comment by javierpuche** [comment]
Scratch debería mostrarse en Programación y la carpeta Squeak ocultarla, pregunto en el grupo si además dejamos Scratch en aplicaciones eLearning

**Comment by javierpuche** [comment]
Pues dejamos Scratch 1.4 en Programación y en aplicaciones eLearning (y la 2.0 offline igual) y sugiere Antonio Ángel poner en aplicaciones eLearning un enlace a Scratch2 online: https://scratch.mit.edu/projects/editor/

**Comment by mariodebian** [comment]
done in max-menus 8.0.max10
