### ISSUE TITLE
Instalando desde USB en modo EFI se generan entradas en el menú de GRUB para el USB

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-desktop#676]
He instalado la MAX8 desde un USB en modo EFI. He tenido que crear manualmente la partición EFI en fat32 ya que el instalador en ningún momento propone o se queja de que necesita esta partición, habría que ver si esto se puede automatizar o por lo menos avisar, bueno, el caso es que una vez que existe la partición EFI la instalación termina sin problemas y se crea el directorio /EFI/max-8.0.
El problema es que ha creado dos entradas que no proceden y que hacen referencia al USB desde el que he instalado la MAX. Una vez iniciada la MAX las entradas se quitan si vuelvo a ejecutar "update-grub2".

**Comment by mariodebian** [comment]
la partición UEFI la crea Microsoft normalmente, no creo que nadie instale en modo UEFI un equipo en blanco.

**Comment by javierpuche** [comment]
ok, lo dejamos para más adelante, lo curioso es que la opción de borrar todo sí crea correctamente la partición (probado en máquina virtual)

**Comment by javierpuche** [comment]
Ezequiel reporta que no le funciona en un max7.5 instalado en uefi al instalar max8 en uefi, lo estudiamos, quizás no deberían utilizar la misma entrada MAX

**Comment by mariodebian** [comment]
Cambiado /boot/efi/EFI/MAX por /boot/efi/EFI/MAX8
