### ISSUE TITLE
Al instalar en modo EFI no muestra el menu de GRUB

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-desktop#677]
Una vez terminada la instalación en modo EFI realizada desde un USB, al reiniciar el equipo sí carga el grub pero este no encuentra el menú de configuración "grub.cfg". Consigo cargarlo manualmente con "configfile /efi/max-8.0/grub.cfg".

Luego he descubierto que si creo un directorio en la partición EFI llamado "EFI/ubuntu" entonces grub sí encuentra el fichero "grub.cfg" y carga el menú correctamente.

Otra opción con la que he coseguido correguir el problema ha sido generar un nuevo fichero "grubx64.efi" ejecutando:

grub-mkimage --format=x86_64-efi -p /EFI/max-8.0 -o grubx64.efi acpi all_video bitmap bitmap bitmap_scale boot btrfs bufio bufio chain configfile crypto datetime disk diskfilter diskfilter echo efifwsetup efi_gop efinet efi_uga ext2 extcmd extcmd font fshelp gcry_sha512 gettext gfxmenu gfxterm gfxterm_background gzio halt hfsplus iso9660 jpeg keystatus linux linuxefi loadenv lsefi lsefimmap lsefisystab lssal lzopio memdisk minicmd mmap normal part_gpt part_msdos password_pbkdf2 pbkdf2 priority_queue reboot relocator search search_fs_file search_fs_uuid search_label sleep terminal test trig video video_bochs video_cirrus video_colors video_fb fat help ls lspci

**Comment by javierpuche** [comment]
sigue pasando en max8-alpha2

**Comment by javierpuche** [comment]
Ezequiel reporta que no le funciona en un max7.5 instalado en uefi al instalar max8 en uefi, lo estudiamos, quizás no deberían utilizar la misma entrada MAX
