### ISSUE TITLE
meter mono 4.0 en max 8

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#679]
para que funcione bien repetierhost
http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

**Comment by mariodebian** [comment]
Lleva un montonazo de paquetes: http://origin-download.mono-project.com/repo/debian/dists/wheezy/main/source/Sources.gz

**Comment by javierpuche** [comment]
ok, lo dejamos de momento, dependen muchas cosas de este paquete como para quitarlo de serie y dejarlo solo en repos, lo dejamos tal como está y pondremos instrucciones en +Aplicaciones para el caso concreto del repetierhost
