### ISSUE TITLE
falta Preferencias/Aplicaciones al inicio en xfce

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#681]

**Comment by mariodebian** [comment]
A mí si se me ven esos menus.

**Comment by javierpuche** [comment]
Vale, ahora está en Inicio->Preferencias->Sesión e inicio -> Autoarranque de aplicaciones,   el menú de configuración del sistema al que se accede desde el icono de equipo en la barra de notificaciones ha quedado muy pobre, salen apenas cuatro configuraciones frente a todas las de inicio->Preferencias ¿Los ponemos más visibles?
