### ISSUE TITLE
falta menú educación en xfce max8alpha1 y alpha2

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#682]

**Comment by mariodebian** [comment]
Los menús son los mismos que en MAX 7.5, espero que en Xfce no hayan quitado el soporte a submenús y todo menú que tenga un submenu desaparezca...

**Comment by mariodebian** [comment]
Xfce4 no muestra menus si sólo contienen submenús.

He añadido +Aplicaciones dentro de Educación para arreglar este bug (tanto en GNOME como Xfce4)
