### ISSUE TITLE
¿contraseña a root?

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#685]
Como el arranque en modo de recuperación da una opción de iniciar una shell pero pide contraseña de root y lo normal es que no exista, tenemos las siguientes posibilidades:
1.- Fijar una contraseña de root: inseguro de por sí y habría que habilitar que cuando se cambie la de madrid se cambie también la de root, o que pida cambiar la de root en el primer arranque o en la instalación o de forma opcional.
2.- Añadir una entrada al arranque que sea iniciar shell como root, init=/bin/bash, para que el usuario que lo necesite le cambie la contraseña a root y pueda iniciar una shell

 Ahí queda para irlo pensando, según escribo me parece que la opción de poder poner en el instalador una contraseña de "recuperación" (root) opcional, no es mala idea.

**Comment by mariodebian** [comment]
la forma oficial es usar init=/bin/bash

https://help.ubuntu.com/community/LostPassword

Pero yo no pondría como entrada en el GRUB, ya que se pueden romper cosas....
