### ISSUE TITLE
instalador falla en max8alpha1

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#688]
Ha habido algunos reportes de fallo del instalador, hay sospechas de si puede ser el modo que tenemos desde la 7.5 de no conectar a red para acelerar la instalación. Son equipos en los que ubuntu 14.04 se instala sin problemas con el cable de red quitado, tenemos que mirar si hay algo que pueda influir y sobre todo pedir trazas a los que puedan reproducirlo.

**Comment by mariodebian** [comment]
Necesitamos los logs de /var/log/installer
