### ISSUE TITLE
XFCE4 meter gcompris pysycache y scratch en botonera infantil max8alpha3

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#696]

**Comment by mariodebian** [comment]
En ls instalación de MAX 8.0 alfa 2 (20150608) **SI SALE**

**Comment by mariodebian** [comment]
Captura de XFCE4
![captura de pantalla_2015-06-13_13-42-41](https://cloud.githubusercontent.com/assets/522472/8144210/2052f702-11d2-11e5-8b8d-2f4c0966af72.png)


Faltan gcompris y pysycache en GNOME, pero no scratch
![captura de pantalla_2015-06-13_13-36-12](https://cloud.githubusercontent.com/assets/522472/8144209/204ffc00-11d2-11e5-87f3-46d903566b66.png)

**Comment by javierpuche** [comment]
El ticket está mal, es en gnome donde no salen en la botonera en la
alpha2

El sáb 13 jun 2015 13:39:41 CEST, Mario Izquierdo
<notifications@github.com>:

> En ls instalación de MAX 8.0 alfa 2 (20150608) SI SALE
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/696#issuecomment-111701613

**Comment by javierpuche** [comment]
Verficado de nuevo en una máquina virtual con la alpha2 64 bits, pero en la real sí los tengo (alpha1 actualizada 64 bits) ¿Tendrá que ver con la resolución 640x480 en primer arranque, que no quepan y los quite?  si se pone la barra en modo expandir deja huecos entre omnitux y childsplay

 Luego pruebo en más máquinas reales pero tengo al menos 4 virtuales con este problema.

**Comment by mariodebian** [comment]
estan subidos paquetes nuevos que lo arreglan

**Comment by javierpuche** [comment]
Mario del Olmo sigue reportando que pasa en XFCE en la beta1

**Comment by mariodebian** [comment]
Ya están todos

GNOME
![captura de pantalla_2015-06-27_13-25-03](https://cloud.githubusercontent.com/assets/522472/8391798/047de7e0-1cd0-11e5-8878-bfdf4e511080.png)

XFCE
![captura de pantalla_2015-06-27_13-25-34](https://cloud.githubusercontent.com/assets/522472/8391799/07c1dea2-1cd0-11e5-811c-1b8a681500d3.png)

Si no sale en XFCE hay que limpiar el perfil de la HOME (las actualizaciónes en XFCe no actualizan el perfil de la HOME de usuario por lo que si se usa homealumno probablemente si salga, en la cuenta de madrid no saldrá)

Instalación limpia de la próxima RC1 si saldrá en todos los casos
