### ISSUE TITLE
max-multiseat para max8

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#710]
El paquete max-mulsiseat no va en las betas de max8, el error al intentar instalarlo es:

 max-multiseat : Depende: xserver-xorg-video-displaylink pero no es instalable
                 Depende: xserver-xorg-video-tusb (>= 0.1.0-4max7) pero no es instalable

**Comment by javierpuche** [comment]
Otro tema que arrastramos de la max 7.x es que no funciona el sonido, para que vaya bien hay que añadir la siguiente línea a /etc/pam.d/common-auth:
auth required pam_group.so use_first_pass

 pero resulta que si la añadimos antes de unir al dominio, luego casca el script de unir al dominio porque se bloquea al ver que ese fichero no es el original. Se puede solucionar con el siguiente comando, pero no puede ejecutarse de forma no interactiva:
sudo pam-auth-update --force libpam-runtime

 El tema es investigar:
1.- Si el añadir la línea de más arriba es la solución correcta (parece que sí porque si no no tiene en cuenta la configuración de grupos por defecto en un fichero que ahora no localizo) o hay otra manera de hacerlo
2.- Dónde hacerlo para que no interfiera con el script de unir al dominio

 Lo vamos mirando.

**Comment by mariodebian** [comment]
DejaVU de nComputing.

En /usr/share/pam-configs/ hay que crear un archivo con un formato especial para que inserte lo que necesites en /etc/pam.d/, por ejemplo este es el que crea el antiguo max-ldap:

```
Name: Make home dir for user
Default: yes
Priority: 192
Session-Type: Additional
Session-Interactive: yes
Session:
	optional	pam_mkhomedir.so
```

pam-auth-update se puede hacer preseed y ejecutar de manera no interactiva con 2 simples variables de entorno: 
 * DEBCONF_FRONTEND="noninteractive"
 * DEBIAN_FRONTEND="noninteractive"

Mirar el ejemplo completo de max-ldap: https://github.com/max-linux/max-desktop/blob/master/max-ldap/max-ldap

**Comment by javierpuche** [comment]
Vale, el problema es que estabamos editando directamente el archivo /etc/pam.d/common-auth en vez de crear un archivo nuevo (https://help.ubuntu.com/community/LDAPClientAuthentication)

 La solución es simplemente crear un archivo /usr/share/pam-configs/grupos-ldap con el siguiente contenido:
```
Name: activar grupos ldap de /etc/security/group.conf
Default: yes
Priority: 900
Auth-Type: Primary
Auth:
        required                        pam_group.so use_first_pass
```
 Luego ejecutar el pam-auth-update para que lo tenga en cuenta, de esta manera sí lo respetan las actualizaciones. 

 Se podría meter en el script de unir max al dominio.

**Comment by mariodebian** [comment]
Subido paquete xserver-xorg-video-tusb 0.1.0-4max11
