### ISSUE TITLE
traducción de Change en la ventana de manejar particiones del instalador en max8alpha2

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#712]

**Comment by mariodebian** [comment]
En el ubiquity que he subido parcheado (traduce los mensajes de LVM) está traducido "Change..." por "Cambiar..." pero no lo esta pillando

**Comment by javierpuche** [comment]
Si me dices dónde está traducido investigo qué puede estar pasando, he buscado pero no lo encuentro ¿Puede ser que falte compilar el pyc correspondiente?

**Comment by mariodebian** [comment]
No es un python es un glade + debconf.

En el paquete de ubiquity (de Ubuntu no el nuestro) /usr/share/ubiquity/gtk/stepPartAdvanced.ui
Las traducciones son de debconf: /usr/lib/dpkg/info/ubiquity.templates => ubiquity/text/parttition_button_edit

**Comment by javierpuche** [comment]
en ubuntu también pasa ...

**Comment by mariodebian** [comment]
Arreglado en ubiquity-2.18.8.8max2
