### ISSUE TITLE
en max8 dnie solo carga bien el módulo si no se ha utilizado previamente firefox

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#718]
TACHAR:
No funciona, hay varias cosas que ir mirando, primero si los certificados han cambiado (no, esto va a ser que no)
http://www.dnielectronico.es/descargas/certificados/AVDNIEFNMTSHA2_new.zip
http://www.dnielectronico.es/descargas/certificados/AVDNIEFNMTSHA2.rar
estos no:
http://www.dnielectronico.es/ZIP/ACRAIZ-SHA2.CAB
http://www.dnielectronico.es/ZIP/ACDNIE001-SHA2.zip
http://www.dnielectronico.es/ZIP/ACDNIE002-SHA2.zip
http://www.dnielectronico.es/ZIP/ACDNIE003-SHA2.zip

 A parte en max8 no consigo que vaya, pero tengo que hacer más pruebas, en 7.5 me ha costado pero si funciona el primer enlace de verificación de certificados que ponen en http://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_320&id_menu=[25]
pero el de la fnmt se queda con un aviso de introducir token pero que no deja introducir nada, lo voy miranado.

FIN TACHAR. IR AL ÚLTIMO MENSAJE

**Comment by javierpuche** [comment]
Sí funciona, lo único que hay que hacer es en firefox añadir el dispositivo de seguridad pkcs11 con la ruta /usr/lib/opensc-pkcs11.so , no sé en qué paquete lo hacíamos antes

**Comment by mariodebian** [comment]
Eso se debería hacer en el postinst del paquete dnie-support: /var/lib/dpkg/info/dnie-support.postinst

**Comment by mariodebian** [comment]
Cuando se instala se ve como se añade sin errores:

```
Configurando dnie-support (1:0.12.2-2ubuntu1+opendnie1max3) ...
Module "OpenSC PKCS#11 Module" added to database.
Certificate "ACRAIZ-SHA1.crt" added to database.
Certificate "FNMTClase2CA.cer" added to database.
```

Y si se añade:

![captura de pantalla_2015-06-13_16-57-28](https://cloud.githubusercontent.com/assets/522472/8144768/54eed376-11ed-11e5-96fa-e18eefa87179.png)

(instalación limpia de MAX 8.0 alfa2 e instalado el paquete dnie-support)

**Comment by mariodebian** [comment]
El certificado de la FNMT caduca en 2019 y el de la policia del DNI en 2036

**Comment by javierpuche** [comment]
Comprobado una vez más en alpha1 actualizada y alpha2, 64 bits, la
captura adjunta ¿es en 64 bits? 
 me aparecen los tres mensajes:
   Configurando dnie-support (1:0.12.2-2ubuntu1+opendnie1max3) ...
  Module "OpenSC PKCS#11 Module" added to database.
  Certificate "ACRAIZ-SHA1.crt" added to database.
  Certificate "FNMTClase2CA.cer" added to database.
  Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
  Procesando disparadores para max ...

pero luego en firerfox no aparece 


El sáb 13 jun 2015 16:58:22 CEST, Mario Izquierdo
<notifications@github.com>:

> Cuando se instala se ve como se añade sin errores:
> Configurando dnie-support (1:0.12.2-2ubuntu1+opendnie1max3) ... Module
> "OpenSC PKCS#11 Module" added to database. Certificate "ACRAIZ-SHA1.crt"
> added to database. Certificate "FNMTClase2CA.cer" added to database.
>   Y si se añade:
>
>   [1]
>
>   (instalación limpia de MAX 8.0 alfa2 e instalado el paquete
> dnie-support)
>
>   —
> Reply to this email directly or view it on GitHub[2].
>       



Vínculos:
---------
[1]  
https://cloud.githubusercontent.com/assets/522472/8144768/54eed376-11ed-11e5-96fa-e18eefa87179.png
[2] https://github.com/max-linux/max-desktop/issues/718#issuecomment-111717316

**Comment by mariodebian** [comment]
yo lo he hecho en un 8.0 alfa2 recién instalado de 64 bits.

Supongo que será importante no haber abierto firefox nunca, o si se ha hecho cerrarlo y borrar ~.mozilla

**Comment by javierpuche** [comment]
comprobado que solo funciona si no se ha abierto firefox antes, hay que mirar cómo hacer para que funcione incluso cuando ya hay un perfil de mozilla
 Por otro lado al acceder a la verificación del dnie en https://av-dnie.cert.fnmt.es/compruebacert/compruebacert   sale un aviso para introducir el token de seguridad pero ningún campo donde introducirlo y ahí se queda bloqueado.

**Comment by mariodebian** [comment]
Arreglado en opensc-opendnie 0.12.2-2ubuntu1+opendnie1max4
