### ISSUE TITLE
+Aplicaciones bugs

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#722]
- [x] Quitar el target=_blank  de los enlaces de APT
 - [x] python-intef-exe ahora se llama intef-exe
 - [x] Moodle se instala con maxmoodle y maxmoodle-preseed
 - [x] Enlace de bluegriffon roto
 - [x] qlandkarte es un paquete virtual (o eso dice al pulsar)
 - [x] pseint lo tenemos en repo, falta enlace instalar...
 - [x] ffdiaporama en repo (handbrake creo que tambien...)

**Comment by javierpuche** [comment]
He quitado algunos target=_blank y actualizado instrucciones para que no los metamos así, me queda dar una batida para localizar los que queden y cambiarlos, rellenar impresión 3D con Rober, y definir los preferidos para proponer en el primer arranque por categorías

**Comment by javierpuche** [comment]
Quitado el target=_blank de los enlaces apt, a mano, no tenemos acceso a la bd ni ninguna api, luego con un script he comprobado que están ya bien. Si hace no obstante una expresión regular para filtrar me lo decís ..

**Comment by javierpuche** [comment]
Al final ponemos un enlace a http://external.educa2.madrid.org/web/maxcontent/metapaquetes  y se queda así
