### ISSUE TITLE
versión de arduino

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#724]
Comenta Ezequiel:
 Estoy usando más el arduino IDE de arduino.org que el que tenemos en repos que viene de arduino.cc. 

 junto con ver si la 1.6.x la paquetizan o si la hacen más independiente de la versión de las liberías avr o directamente en max8 se lleva bien con las que llevemos de serie

**Comment by mariodebian** [comment]
Actualizado a arduino 1.5.6.2+sdfsg2-3max1

**Comment by maxezek** [comment]
Reabro este issue. Ahora es javier el que se ha fijado que tenemos una versión incluso más antigua que la de la MAX 8. 
La versión actual no admite ni arduino YUN ni DUE. La última es del 5 de junio:

[Fuente de arduino 1.8.3](https://github.com/arduino/Arduino)

Lo suyo sería paquetizar la nueva 1.8.3

**Comment by mariodebian** [comment]
Subido arduino IDE 1.8.5

**Comment by maxezek** [comment]
Parece que ahora tenemos un daño colateral. Deja de funcionar **ardublock**. 

El fallo es que no carga el programa hecho en ardublock en la placa arduino.

Mo se si es por la versión aqui estan las versiones de ardublock:

[VerArdublock ](https://sourceforge.net/projects/ardublock/files/?source=navbar)

**Comment by mariodebian** [comment]
La versión anterior no era compatible con IDEs nuevos, recompilada la actual desde el github ( https://github.com/taweili/ardublock ) parece que funciona (aunque en consola muestra una excepción)
