### ISSUE TITLE
icono de Información de la conexión de red en barra inferior roto (aspa roja)

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#727]

**Comment by mariodebian** [comment]
Duplicado #553

**Comment by javierpuche** [comment]
El 553 lo tenemos cerrado y mezcla dos cosas:
1.- dejamos abierte este porque en todas las instalaciones independientemente del hw. aparece con aspa roja el icono de información que se puede ver al clicar sobre el icono de red en el panel inferior, en el desplegable la segunda opción de abajo a arriba es Información y va con un aspa roja ¿?
2.-  en hw. muy concretos de portátiles, ese desplegable a veces desaparece, se ve un reborde pero como si se hubiera vacíado, sigue pasando con max8 pero tengo que hacer pruebas más extensivas para documentar y abro ticket nuevo, lo he reproducido en un fujitsu amilo y un toshiba protegé, aunque en este último de forma muy esporádica (una vez)

Conclusión: este no es prioritario pero lo dejo abierto por el aspa roja

**Comment by mariodebian** [comment]
Aplazado

**Comment by javierpuche** [comment]
Se soluciona añadiendo a la línea 5 del archivo /usr/share/icons/maxtoon/index.theme (Inherits) los temas:
,Humanity-Dark,hicolor
 que son los que hereda el tema ambiance en el que encuentra bien ese icono, en realidad basta con el Humanity-Dark, pero por precaución yo dejaría los dos, voy a ver que no trastoque ningún otro tema...

**Comment by javierpuche** [comment]
Cerrado via https://github.com/max-linux/max-desktop/commit/9d6d398fe4dc93f29e0a5f18b8b8fa18be3fea01#diff-9cb4271dd5bdf2a95906fdc8328f8211
