### ISSUE TITLE
eXe arranca en inglés

### ISSUE THREAD

**Issue by amadeomora** [max-linux/max-desktop#732]
Debería arrancar ya configurado a es

**Comment by javierpuche** [comment]
Sí, es la configuración por defecto, esta vez hemos pillado el .deb de eXe tal cual, se lo comento a ellos para ver si los pueden generar poniendo por defecto Español y nos ahorramos tener que reempaquetar nosotros solo para eso.

**Comment by javierpuche** [comment]
Me dicen que lo hablaron y es el comportamiento por defecto hasta que hagan un desarrollo para autodetectar, de momento lo dejamos, podríamos reempaquetar nosotros poniéndolo en español pero prefiero esperar a la autodetección, gracias por reportarlo.

**Comment by javierpuche** [comment]
Ups, resulta que el apaño que hicimos para la 1.4 sigue siendo válido, en su día les escribí pero no lo tuvieron en cuenta, he vuelto a lanzarlo en su lista de desarrolladores a ver si ahora lo hacen, porque sería una pena tener que reempaquetar nosotros solo por esta pijadilla.
http://lists.forja.cenatic.es/pipermail/iteexe-developers/2014-April/000301.html
http://lists.forja.cenatic.es/pipermail/iteexe-developers/2015-July/000945.html

**Comment by mariodebian** [comment]
Estamos reempaquetando porque metemos un tema que ellos no llevan así que ya puestos se puede meter el parche de idioma....

**Comment by mariodebian** [comment]
subido intef-exe-2.0.4ppa01max2

**Comment by javierpuche** [comment]
El vie 17 jul 2015 10:08:56 CEST, Mario Izquierdo
<notifications@github.com>:

> Estamos reempaquetando porque metemos un tema que ellos no llevan así
> que ya puestos se puede meter el parche de idioma....
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       

 No, en realidad ellos ya metieron las dos plantillas y por eso podíamos
coger el .deb de su ppa tal cual, pero mejor así ahora para corregir ese
pequeño bug que ellos no tengo claro que vayan a reempaquetar solo por
eso.

https://forja.cenatic.es/tracker/index.php?func=detail&aid=2607&group_id=197&atid=1107

Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/732#issuecomment-122211655

**Comment by mariodebian** [comment]
Pues entonces lleva 3 paquetes de MAX
