### ISSUE TITLE
Ampliar la biblioteca de piezas de LeoCAD

### ISSUE THREAD

**Issue by antonioarm** [max-linux/max-desktop#733]
Si es posible, sería muy interesante ampliar la librería de piezas de LeoCAD en MAX 8.0. En isntalaciones anteriores era más amplia.

Saludos.

**Comment by javierpuche** [comment]
probar a meter el paquete leocad-parts

**Comment by mariodebian** [comment]
Hecho en leocad 0.80.3 y  ldraw-parts 1401+ds-2max1
