### ISSUE TITLE
no funcionan las preferencias de accesibilidad

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#734]
el .desktop ejecuta:
unity-control-center universal-access
pero también con gnome-control-center da el mismo error:

GLIb-GIO-ERROR ***: Settings schema 'com.canonical.Unity.Interface' is not installed

**Comment by mariodebian** [comment]
Arreglado en https://github.com/max-linux/max-desktop/commit/f062ebfacae392ad3b3ec0e9ab856690825857a5
