### ISSUE TITLE
tcos-config en max8-beta1 no tiene distrubución trusty ni el kernel actual

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#737]
además se queja del paquete tcos-keyring y termina fallando el padbear o algo así ...

**Comment by mariodebian** [comment]
Subido tcosconfig_0.3.35max1

tcos-keyring no hace falta desde 0.89.88 https://github.com/mariodebian/tcos/commit/5aef37e14df2e10d8a22d29e91a154879d033ec2
