### ISSUE TITLE
scratch no reconoce los mp3 ni los jpg en 64 bits en MAX 8 RC1

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#750]
La solución ya la dio Mario para la max 7.5:
En el paquete scratch llevar la máquina virtual de squeak-vm de 32 bits compilada de la web www.squeakvm.org/unix/  ya que el paquete de debian (y ubuntu) parece que desactiva el mpeg en 64 bits.  Además cambiar el enlace a libjpeg8 por la 6.2 para que funcionen los jpg, esto hay que hacerlo también en 32 bits.
Pondré un ticket en launchpad a ver si lo solucionan también ellos y no nos toca seguir parcheando nosotros en cada nueva versión.

 De paso (ya que hay que rehacer el paquete scratch para cambiar las dependencias) poner con scratch la regla udev para el Wedo de los tickets #485 y #495

**Comment by mariodebian** [comment]
Subido nuevo scratch, las reglas de wedo ya vienen en la ultima version de squeak-plugins-scratch
