### ISSUE TITLE
personalización de chromium

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#752]
Lo único que veo que se puede hacer es:
- Crear un archivo  /etc/chromium-browser/policies/recommended/max-startpage.json  con estos contenidos:
```
{
 "RestoreOnStartup": 4,
 "RestoreOnStartupURLs" : ["file:///usr/share/chromium-browser/startpage.html"]
}
```
 y haber puesto el startpage.html (el mismo que llevamos en firefox) en esa carpeta (no podemos utilizar el de firefox porque va dentro de un jar)

Estoy mirando si hay alguna manera para que no salga en la barra de arriba la ruta al fichero, o que el newtab sea nuestra página. Pasa por crear una extensión, es fácil y me sale (generando un .crx) pero luego no consigo que la cargue de serie con ninguno de estos métodos:
http://www.adambarth.com/experimental/crx/docs/external_extensions.html
https://developer.chrome.com/extensions/external_extensions#preferences

CONSEGUIDO, el lunes pongo los detalles :-)

**Comment by mariodebian** [comment]
Modificando el paquete max-ubunfox llevamos el html en /usr/share/doc/max-ubufox/startpage.html por lo que ya no habría que duplicarlo
