### ISSUE TITLE
desaparece el desplegable de conexiones de red en gnome-panel

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#753]
Despliego en dos el ticket #727, esta parte:
  en hw. muy concretos de portátiles, ese desplegable a veces desaparece, se ve un reborde pero como si se hubiera vacíado, sigue pasando con max8 pero tengo que hacer pruebas más extensivas para documentar y abro ticket nuevo, lo he reproducido en un fujitsu amilo y un toshiba protegé, aunque en este último de forma muy esporádica (una vez)

 es fácil reproducir parcialmente, no la desaparición pero sí el que aparezcan flechas de scroll cuado no debería: basta con clicar en Activar Red para desactivarla y luego otra vez para activarla, entonces aparece el scroll.

 el tema de que desaparezca totalmente (solo se ve el borde) parece ligado a portátiles con wifi, ahora tengo aquí un toshiba donde lo reproduzco si trasteo un rato con el nm-applet, conecto, desconecto y en un momento dado pasa, el log del strace no veo nada sospechoso (como único mensaje sospechoso pendiente de analizarlo más en detalle) salvo

(nm-applet:3044): Glib-CRITICAL **: Source ID 137 was not found when attemping to remove it    

 pero aparece despueś del detach ¿?

**Comment by mariodebian** [comment]
En Mate no ocurre lo muevo a max-next

**Comment by DaniMAdridlinuX** [comment]
Parece que ya no se ha reportado en las nuevas versiones
