### ISSUE TITLE
gazapos en textos en el administrador de impresoras

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#756]
Por Fernando:

    El primero dice "Se necesitan __priviegios__ para obtener una lista de los dispositivos disponibles"
    El último dice "Se necesitan __priviegios__ para añadir, quitar o editar una impresora local".
    También aparece así cuando la impresora es remota: "Se necesitan __priviegios__ para añadir, quitar o editar una impresora remota"

**Comment by mariodebian** [comment]
Subido cups-pk-helper-0.2.5 parcheado

**Comment by mariodebian** [comment]
Subido parche a launchpad: https://bugs.launchpad.net/ubuntu/+source/cups-pk-helper/+bug/1475525
