### ISSUE TITLE
la instalación de guest-additions debería meter a algunos usuarios en el grupo vboxfs

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#760]
Deberían tenerlo previsto los de virtualbox, pero en un futuro evaluamos meter alumno y madrid durante los scripts desencadenados por la instalación de las guest-additions. Es necesario luego para poder utilizar las carpetas compartidas y algunas otras funcionalidades de las guest additions.

**Comment by daviddavo** [comment]
Tampoco creo que sea necesario, en Linux es sólamente un comando para añadir un grupo a un usuario.
`usermod -a -G <group> <user>`, o, por ejemplo `usermod -a -G vboxsf madrid`

**Comment by mariodebian** [comment]
Podemos forzarlo en algun script que se ejecute siempre de instalar un paquete.. pero es algo que se debería hacer manualmente.
