### ISSUE TITLE
Error en startupmanager, modulo grub.py, es una instalación UEFI

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-desktop#762]
El "Administrador de arranque"(comando starupmanager) no se abre. Es una instalación con Windows 8.1 instalado en UEFI. Una vez instalado MAX también en UEFI, si ejecuto el startupmanager desde la consola me aparece el siguiente error:

root@equipoXX:/home/madrid/Escritorio# startupmanager 
Generando archivo de configuración grub...
Found background image: /usr/share/images/grub/maxgrub.png
Se encontró una imagen linux: /boot/vmlinuz-3.13.0-58-generic
Se encontró una imagen initrd: /boot/initrd.img-3.13.0-58-generic
Encontrado en Windows 8 (loader) en UEFI ESP
Adding boot menu entry for EFI firmware configuration
hecho
Grub2 detected
Usplash not detected
Splashy not detected
Traceback (most recent call last):
  File "/usr/sbin/startupmanager", line 54, in <module>
    main()
  File "/usr/sbin/startupmanager", line 51, in main
    SumGui()
  File "/usr/share/startupmanager/gtk_frontend.py", line 203, in __init__
    self.serch_old_kernels()
  File "/usr/share/startupmanager/gtk_frontend.py", line 1154, in serch_old_kernels
    for item in self.grub.get_titles():
  File "/usr/lib/pymodules/python2.7/bootconfig/grub.py", line 134, in get_titles
    entries.append(line.split("'")[1])
IndexError: list index out of range
root@equipoXX:/home/madrid/Escritorio#

**Comment by javierpuche** [comment]
Error mío, en la última modificación que hice del grub.py no tuve en cuenta que hay entradas que pueden venir sin la comilla simple, lo miro.

**Comment by javierpuche** [comment]
Mejor comprobar si hay comilla o no, grub.py, el bucle a partir de la línea 121:
```
        for linenum,line in enumerate(lines):
            if line.find("'"):
                desc=line.split("'")[1]
            else:
                desc=line
            if "\tmenuentry" in line:
                entries.append(desc)
            else:
                r=re.search('^menuentry',line)
                if r:
                    remainingText = ''.join(lines[linenum+1:])
                    r1=re.search('submenu',remainingText,re.MULTILINE)
                    if r1:
                         r2=re.search('^\t?menuentry',remainingText,re.MULTILINE)
                         if r2 and (r1.start(0)>r2.start(0)):
                             entries.append(desc)
                    else:
                         entries.append(desc)
```

**Comment by mariodebian** [comment]
Una forma más pythonica de buscar cosas en cadenas es:
```
if '"' in line:
```
Ya he subido el nuevo paquete startupmanager 1.9.13-5max16
