### ISSUE TITLE
abrir archivos .swf con firefox

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#769]
firefox no abre directamente archivos .swf salvo que vengan bien enlazados desde un html previo. Si le das a abrir directamente un .swf te pide una aplicación externa para abrirlo.

He visto que funciona la solución descrita aquí: http://askubuntu.com/questions/478169/why-cant-firefox-run-local-swf-files

 Evaluar incluirla en max por defecto.

**Comment by jrodriguezpascua** [comment]
Más información que aporta Javier Puche en los foros de MAX.

http://foros.educa.madrid.org/viewtopic.php?f=2&t=2988&p=10293&hilit=swf&sid=6a7054b153bbd27972f9c18e1734d8b6#p10293

**Comment by mariodebian** [comment]
El fin de vida de FLASH es Diciembre de 2020: https://www.adobe.com/es/products/flashplayer/end-of-life.html

No va a haber soporte, no se va a poder descargar y los navegadores no lo van a ejecutar.

Creo que es mejor olvidarse de flash.
