### ISSUE TITLE
Añadir a los repositorios handbrake-gtk y handbrake-cli

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#772]
Tenemos en MAX 8 incluido en el repositorio handbrake en el paquete handbrake 0.9.9+dfsg-2~2.gbpa4c3e9build1 que es antiguo.
De la página oficial https://handbrake.fr/ ya te manadan a este ppa en launchpad https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases con las versiones:
handbrake-cli
handbrake-gtk
que sustituyen al paquete anterior.

**Comment by jrodriguezpascua** [comment]
Lo movemos a la milestone 8.5

**Comment by mariodebian** [comment]
Hecho y subido
