### ISSUE TITLE
No funcionan algunos lectores de CDs y DVDs

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#773]
Reportado en varias ocasiones. Algunos DVDs de vídeo no se abren, por falta de codecs.

**Comment by jrodriguezpascua** [comment]
Fernando Lisón encontró la solución y Ezequiel lo reporta en los foros de MAX. Habría que incluirlo como una actualización y meterlo en la 8.2.

----------- CORTO Y PEGO SOLUCIÓN DE AMBOS ------------------

Hace más de un mes Fer dió con la solución para leer CD/DVD y era instalar una biblioteca:

sudo apt-get install libdvdread4

Esta en el foro desde el 1 de febrero:

http://herramientas.educa.madrid.org/foros/viewtopic.php?f=3&t=2979#p10500

No se si son necesarios el resto de paquetes que incluyes en el foro. No parece que para esto tenga que ver el proxy de la macrolan pero puedo equivocarme.

Está genial todo lo que te mueves Pedro. Si sacáis algo en claro, pasadselo a Daniel para su guía que es una "herramienta" fantástica.

**Comment by jrodriguezpascua** [comment]
Y MÁS....

Luego después de instalar la biblioteca hay que ejecutar:

sudo /usr/share/doc/libdvdread4/install-css.sh

**Comment by mariodebian** [comment]
La solución realmente no es esa, en el README.css de este paquete lo explica:

```
Content Scramble System (CSS)
-----------------------------

Many DVDs use CSS[0] as a form of a Digital Rights Management (DRM) to encrypt
the content of Video DVDs. To play such discs a special library is needed to
decode them, libdvdcss.

Due to the legal limbo of libdvdcss in some particular juristictions, some
distributions including Debian do not distribute libdvdcss.

If it is legal for you to use CSS in your juristiction, you can:

  * Manually download and compile the source code from
    <http://www.videolan.org/developers/libdvdcss.html>.

  * Use packages from derivatives that include libdvdcss.

 [0] <http://en.wikipedia.org/wiki/Content_Scramble_System>
```

Este script install-css.sh compila e instala el paquete libdvdcss2 del repo del VLC (Videolan).

Para MAX es mejor compilarlo y tenerlo en nuestro repo como dependencia y que venga instalado por defecto.
