### ISSUE TITLE
Actualizar ffdiaporama de la versión 1.5 a la 2.1

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#775]
En MAX 8 tenemos en el repositorio la 1.5 que ya es obsoleta.

Intentar incluir en los repositorios la versión 2.1 que es la última estable y ya data del 2014.

**Comment by mariodebian** [comment]
Compilado y subido desde PPA: https://launchpad.net/~ffdiaporamateam/+archive/ubuntu/stable?field.series_filter=trusty
