### ISSUE TITLE
Volver a añadir apps quitadas por dependencias kde

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#776]
Parece que se quitaron apps en la versión 8.0 por problemas de dependencias y hay que volver a añadirlas. Ahora funcionan de los respos, por lo que no habría problema en volver a añadirlas. 

Corto y pego conversación en lista de correo la respuesta de Javier Puche a Fernando Lisón, quien se dio cuenta del problema.

El dom 10 abr 2016 19:20:12 CEST, Javier Puche
>
> Hola Fernando,
>
>  Efectivamente nunca se habló de quitar kmplot, en la lista de apps que estuvimos discutiendo y baranjando durante varios meses así consta. Creo que dio problemas en algún momento en las alphas y debimos quitar esa y alguna otra por precaución (creo recordar que no funcionaban bien pero no lo localizo, en repo está y parece que sí funciona bien)
>
>  He mirado mis notas y en la alpha1 (05/05/2015) faltaba esa algunas más y lo hice ver:
>
>     En ciencias Kalzium
>     En Lengua faltan unos cuantos: todos empiezan por Kanagram, KHangMan, KLetters, KTouch y KWordQuiz  ¿por las dependencias kde?
>     En geografía: Marble, Kstarts y Kgeography 
>     En mates: kAlgebra, KBrunch, Kig y KmPlot
>
>  Sospechosamente todas empiezan por K, fue algún tema de dependencias con kde que seguro que se resolvió ... hice seguimiento pero no encuentro más notas :-(
>  
>
> Saludos.
>
>  
>>
>> El otro día una compañera de Matemáticas me dijo que no encontraba KMPlot en los ordenadores de los alumnos. Al ir a ver, me encuentro con que efectivamente KMPlot no está en MAX 8 y no recuerdo que se hablase de quitarlo, pero posiblemente es eso, que no me acuerdo.

**Comment by mariodebian** [comment]
rel #644
