### ISSUE TITLE
En MAX 8.0 el alumno puede cambiar su nombre y contraseña con Cuentas de usuario. URGENTE

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#780]
Descubierto por Fernando Lisón.

Lo que describe el título. Un alumno puede cambiar el nombre de usuario y la contraseña con Cuentas de usuario.

Si un alumno lo hace no se resetea al reiniciar (no le afecta homealumno-gui) y se mantiene la nueva contraseña. Los siguientes alumnos no pueden entrar.

No puedo asignarle yo prioridad pero esto es un error grave y por eso he incluido el URGENTE. Debe quedar protegido la relación usuario-contraseña alumno-alumno.

**Comment by mariodebian** [comment]
Me parece que es algo inevitable.

Esto no tiene nada que ver con homealumno, es el sistema de usuarios de Linux.

Un usuario **SI** puede:

	* Cambiar su contraseña
	* Cambiar su nombre de usuario

Existen maneras para bloquear esto pero probablemente se rompan otras cosas.

Se puede cambiar en modo gráfico pero en consola con el comando passwd también se puede.

Si se bloquea el cambio de contraseña (quitando permisos de ejecución en el comando passwd) tampoco madrid podrá cambiar su contraseña.

**Comment by mariodebian** [comment]
Creo que es menos intrusivo cambiar la periodicidad mínima de cambio de contraseña a cambiar permisos de un binario que ya de por si tiene permisos muy especiales.

passwd tiene bit SUID activado ya que un usuario normal al cambiarse su contraseña "edita" el archivo /etc/shadow que solo puede escribir root.

Prueba en lugar de cambiar permisos a configurar el mínimo tiempo de cambio de contraseña:

	sudo passwd -n 99999 alumno

Explicación de la página man:

       -n, --mindays MIN_DAYS
           Set the minimum number of days between password changes to MIN_DAYS.
           A value of zero for this field indicates that the user may change his/her
           password at any time.

Es probable que con este te quites muchos intentos de "liarla" aunque el propio usuario alumno puede volver a ponérselo en 0 y luego cambiarlo, aunque requiere conocimientos de esta configuración especial.


La forma más radical sería quitando permisos a passwd:

	(por defecto tiene 4755)

	sudo chmod 4750 /usr/bin/passwd

Si haces esto solo con root (o ejecutar con sudo) se podrán cambiar las contraseñas.
