### ISSUE TITLE
No se puede actualizar a Ubuntu 16

### ISSUE THREAD

**Issue by daviddavo** [max-linux/max-desktop#781]
Este es el mensaje de error:
No se ha podido calcular la actualización

Ha ocurrido un problema mientras se calculaba la actualización.

 Eso se ha podido causar por:
- Actualizar a una versión de Ubuntu aún no publicada
- Estar ejecutando la versión actual, aún no publicada, de Ubuntu
- Paquetes no oficiales de software no proporcionados por Ubuntu

Si nada de esto aplica, informe de este error usando la orden «ubuntu-bug ubuntu-release-upgrader-core» en una terminal.

**Comment by mariodebian** [comment]
Hola @daviddavo.

MAX no está pensado para actualizaciones sino para instalaciones limpias.

La última versión de MAX (8.0 u 8.5) está basada en Ubuntu 14.04, no hay soporte ni paquetes para Ubuntu 16.04.

**Comment by daviddavo** [comment]
Y como se podría instalar Gtk+ 14? Estoy desarrollando una aplicación en la que es necesario su uso.

**Comment by mariodebian** [comment]
Usa un Ubuntu 16.04 o Debian sketch

**Comment by mariodebian** [comment]
MAX 9.0 estará basada en Ubuntu 16.04, cierro issue
