### ISSUE TITLE
Peticiones multimedia/gráficas

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#786]
* [x] Añadir synaptic !!!!!!
 * [x] Actualizar Blender a 2.78 (PPA Thomas Schiex)
 * [x] Cambiar gtkRecordMyDesktop por Simple Screen Recorder
 * [x] OpenShot por KDENLIVE ???
 * [x] Ripeador DVD ¿handbrake?
 * [x] Videos youtube => clipgrab
 * [x] Documentar generador ISOS

**Comment by maxezek** [comment]
¡Ojo! considerar KAZAM en vez de Simple Screen Recorder (SSR) porque está en los repositorios de Ubuntu.
Voy a añadirte una pequeña hoja de cálculo con la que estamos trabajando para "peticiones":

[documento para MAX9 general](http://cloud.educa.madrid.org/index.php/s/FgJKXevqxRK8NoG)

y este otro para la personalización de Primaria:

[Personalización infantil y primaria](http://cloud.educa.madrid.org/index.php/s/9U1YaaFxmv55P5t)

**Comment by maxezek** [comment]
He puesto etiqueta +Aplicaciones para documentarlo allí puesto que blender no va de serie y hay que dar a conocer SSR.
