### ISSUE TITLE
Paquetizar cmaptools y añadirlo al repo [enhanced]

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#787]
Está en +Aplicaciones:

[cmaptools en +Aplicaciones](http://external.educa2.madrid.org/es/web/maxcontent/-aplicaciones/-/visor/cmaptools)

Pero no está en los repositorios de Ubuntu y sería una gran mejora de instalación.

**Comment by mariodebian** [comment]
Hecho en e7d9d5bcc52a421870b643759be8a7885735ed62 se debería actualizar la web de +Aplicaciones para que sólo sea un apt://cmaptools

**Comment by maxezek** [comment]
Gracias Mario :-)

Por este y los demás.

Feliz año!!!!!
Ezequiel

Mario Izquierdo <notifications@github.com> escribió:

> Closed #787[1].
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/787
[2] https://github.com/max-linux/max-desktop/issues/787#event-909342510
[3]
