### ISSUE TITLE
Ktuberling, Khangman y Pysiogame (max-infantil-primaria)

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#788]
Al arrancar Ktuberling da un error (que permite luego usarlo pero queda mal) que dice que el fichero guardado esta en una versión anterior. 

Pysiogame de repositorios descarga la versión 1.30.811 pero en MAX8 tenemos la 3.50.311

Khangman: se queda en blanco la ventana que abre.

Quizá hay que esperar a tener personalización preparada para arreglar esto.

**Comment by mariodebian** [comment]
Pysiogame tenemos ahora la 3.60.
Ktuberling no da errores al arranque.
A Khangman le faltaba la dependencia qml-module-qtgraphicaleffects, recompilado y añadido.

**Comment by Marito17** [comment]
Ktuberling no da fallo al abrirlo desde la terminal ni desde el menú, pero al añadir al cairo si sale un mensaje 
"El archivo guardado se corresponde con una versión antigua de Ktuberling y desafortunadamente no se puede abrir en esta versión."
