### ISSUE TITLE
Cambiar opensankore a openboard  como soft de PDI

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#790]
Opensankore se ha parado en su desarrollo. Un fork en Suiza lo ha continuado. Es **openboard**.

[Descarga de openboard](http://openboard.ch/download.en.html)

[GitHub con las fuentes](https://github.com/OpenBoard-org/OpenBoard)

Yo lo sustituiría también en MAX 8. Para Ubuntu 14.04 da problemas en MATE pero allí usamos GNOME y Xfce. 

En líneas generales va bastante más fino que el "abandonado" opensankore.

**Comment by mariodebian** [comment]
Hecho en a7717dbc27b0dbb2ce06218145603ee904af0cb4 y 648cb1ad4e0ed3634ba860a4e851d38dfba5b3ad
