### ISSUE TITLE
Añadir ffdiaporama 2.1 en repos para MAX 9

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#791]
transmitido por Daniel Esteban:

"Intento instalar **FFdiaporama la versión 2.1** creo, desde Synaptic pero me dice que depende de **libavresample1** pero que no es instalable. Este programa para mi es básico en primaria para alumnos y para profes así que me gustaría encontrar una solución."

Pablo Treviño;

"Los siguientes paquetes tienen dependencias incumplidas:
 ffdiaporama : Depende: **libavcodec-extra**
               Depende: **libavresample1** pero no es instalable"

**Comment by mariodebian** [comment]
Recompilado ffDiaporama 2.2 sin las dependencias forzadas libavcodec-extra y libavresample1
