### ISSUE TITLE
El paquete qucs necesita  libtool-bin incluido en MAX 9

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#793]
Encontrado por David Gonzalez:

"Probando QUCS a fondo he visto que daba un error con las **simulaciones digitales**. Se resuelve instalando este paquete:

$ sudo apt-get install **libtool-bin**

Un saludo

David González"

**Comment by mariodebian** [comment]
Añadido como dependencia del propio paquete qucs
