### ISSUE TITLE
MAX 9 beta 1: alternativas a synapse

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#798]
¡ojo! en MAX 8 tenemos por defecto **xfce4-appfinder** ("Buscador de aplicaciones") que sigue funcionando bien.

Existe también si synapse no se arregla gnome-do (muy pesado) y kupfer que funciona parecido.

Si es posible, yo si incluiría xfce4-appfinder por defecto además de synapse o una de esas alternativas más visuales.

**Comment by mariodebian** [comment]
Synapse ya funciona e instalar una aplicación de Xfce4 sin instalar XFCE4 entero causa que varias dependencias de ese escritorio no se instalen, cierro de momento con synapse funcionando...
