### ISSUE TITLE
MAX beta 1: Barra de marcadores de Firefox, Chromium

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#799]
Incluir la barra de marcadores de Firefox con enlace a educamadrid, web de MAX, al foro y a +Aplicaciones

**Comment by mariodebian** [comment]
Se han añadido los bookmarks pero sin recompilar firefox no se puede hacer que se muestren por defecto (pinchando con el botón derecho -> Barra de herramientas de marcadores se ven) , cierro este issue.
