### ISSUE TITLE
MAX 9 beta 1: No se ve flash en navegadores. FAlta libpepflashplayer.so

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#800]
Aunque está instalado pepper no funcionan los flash en navegadores que si funcionan en MAX 8.

Está instalado la aplicación browser pepper flash pero no aparece por ningún lado el módulo

**libpepflashplayer.so**

y creo que es fundamental.

Si se actualiza mediante:

**sudo update-pepperflashplugin-nonfree --install**

devuelve este error:

mv: nose puede efectuar 'stat' sobre 'unpackcrome/opt/google/chrome/PepperFlash/libpepflashplayer.so': No existe el archivo o el directorio

Por lo que he leído se debe a un cambio de politica de Google y habría que instalar el módulo dierctamente de la página de Adobe  :-(

**Comment by mariodebian** [comment]
No se donde has hecho la prueba pero en MAX 9.0 beta1 si hay flash en los dos navegadores
![max9-beta1-flash](https://cloud.githubusercontent.com/assets/522472/21742081/8afa5f08-d4e7-11e6-8489-fab9879dfa91.png)

**Comment by mariodebian** [comment]
Subida versión nueva: pepperflashplugin-nonfree (1.8.3-0york2~16.04max1)

Que descarga el flash de la web de Adobe (Chrome ya no lo trae)

**Comment by maxezek** [comment]
Si, lo se, pero no va.

Adjunto pantallazo.

Mario Izquierdo <notifications@github.com> escribió:

> No se donde has hecho la prueba pero en MAX 9.0 beta1 si hay flash  
> en los dos navegadores
> [1]
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3].
>       



Vínculos:
---------
[1]  
https://cloud.githubusercontent.com/assets/522472/21742081/8afa5f08-d4e7-11e6-8489-fab9879dfa91.png
[2] https://github.com/max-linux/max-desktop/issues/800#issuecomment-271084591
[3]

**Comment by maxezek** [comment]
Eres el más rápido al este del río Pecos, forastero :-)

Mario Izquierdo <notifications@github.com> escribió:

> Closed #800[1].
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/800
[2] https://github.com/max-linux/max-desktop/issues/800#event-914956632
[3]

**Comment by maxezek** [comment]
Mario, funciona en Chomium pero no en Firefox

Mario Izquierdo <notifications@github.com> escribió:

> Closed #800[1].
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/800
[2] https://github.com/max-linux/max-desktop/issues/800#event-914956632
[3]

**Comment by maxezek** [comment]
No funciona en Firefox pero si en Chromium.

En chromium: Shockwave Flash 11.2 r999
Nombre:	Shockwave Flash
Descripción:	Shockwave Flash 11.2 r999
Versión:	11.2.999.999
Ubicación:	/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
Tipo:	PPAPI (fuera de proceso)


En Firefox: Shockwave Flash

    Archivo: libfreshwrapper-flashplayer.so
    Ruta: /usr/lib/browser-plugin-freshplayer-pepperflash/libfreshwrapper-flashplayer.so
    Versión: 13.1.2.3
    Estado: Habilitado
    Shockwave Flash 13.1 r2
