### ISSUE TITLE
MAX 9 beta 1: Dar visibilidad a las herramientas de mate, mate-search-tool

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#801]
No aparece en el menú:

**"Buscar archivos"**

Se trata de la herramienta mate-search-tool equivalente a la de GNOME. Creo que debe estar explicitamente en accesorios aunque con tweak se pueda añadir.

**Comment by mariodebian** [comment]
Esta en el menú Lugares, lo duplico a accesorios....
