### ISSUE TITLE
MAX 9 beta 1: Caja en rojo cuando se usa con sudo o gksudo 

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#802]
Conviene que CAJA (nautilus) reaccione como en las anteriores MAX. Si se usa como _root_ que aparezca en **rojo** para avisar que se pude organizar un berenjenal si se usa mal.

Me he fijado que al hacer sudo caja no se abre en el directorio home de root sino en el de Madrid. Eso me parece raro pero cómodo.

**Comment by mariodebian** [comment]
Hecho como root, con sudo (o gksudo) no se puede hacer
