### ISSUE TITLE
MAX 9 beta 1: configurador de java MAX ==> MAX 9 final actualización

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#803]
Ahora no son instalables ni java 7 ni java 9 desde el configurador de java de max

**Comment by mariodebian** [comment]
Se ha reescrito parte de ese asistente para que soporte versiones viejas y más nuevas, no veo un problema que muestre que un paquete no está en el repositorio.

**Comment by maxezek** [comment]
OK

Mario Izquierdo <notifications@github.com> escribió:

> Se ha reescrito parte de ese asistente para que soporte versiones  
> viejas y más nuevas, no veo un problema que muestre que un paquete  
> no está en el repositorio.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/803#issuecomment-271085855
[2]

**Comment by maxezek** [comment]
Creo que Javier Puche tiene razón en un correo:

_El configurador java no es un bug del script, pero creo que debería mostrar solo los paquetes de java que creamos convenientes para la max9 y en ningún caso poner 'no disponible'  mi opinión. Se creó con la idea de que mostrara todos los java posibles para max y elegir cual se pone como por defecto, según está ahora no veo que cumpla la función, y no es por el script si no por configurarlo (actualizarlo)  Si se decide quitar el java7 pues puede ser muy buena elección, la compatibilidad con descartes u otros ya se antoja muy desfasada,   casi mejor dejar que pueda seleccionar entre oracle y openjdk y punto, si no en mi opinión despista y no sirve a su propósito._

Como Java 7 no está en repos que no aparezca en el configurador.
