### ISSUE TITLE
MAX 9 beta 1: K3b en herramientas del sistema => solo en sonido y video

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#805]
K3b solo debe aparecer en sonido y video

**Comment by mariodebian** [comment]
¿Y donde más aparece?

**Comment by maxezek** [comment]
En Heramientas del sistema

Mario Izquierdo <notifications@github.com> escribió:

> ¿Y donde más aparece?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/805#issuecomment-271085606
[2]
