### ISSUE TITLE
MAx 9 beta 1: Incluir en repos blocksCAD si eso es posible

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#806]
Otro de robótica. Si se puede paquetizar y meter en nuestro repos sería genial. 

Pero me da que es online 100% :

[Página web](https://www.blockscad3d.com/)

[Editor de blocksCAD](https://www.blockscad3d.com/editor/)

**Comment by mariodebian** [comment]
Subido como blockscad
