### ISSUE TITLE
MAX 9 beta 1: cierre eterno de MAX 9 beta

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#807]
Pablo comento en su momento el problema en la alfa y se corrigió.

No se si depende de nosotros pero el cierre se hace interminable al menos en vbox con 64 bits. tarda minutos en apagarse la máquina

**Comment by mariodebian** [comment]
Es un bug entre network manager y dbus en el orden de apagado de servicios, no pasa siempre pero si de vez en cuando... no se si tiene arreglo y si sólo pasa con VirtualBox, no lo he probado en instalación real.

**Comment by mariodebian** [comment]
Desde hace unos días ya no ocurre, debe haber habido una actualización del kernel que lo ha solucionado...

**Comment by maxezek** [comment]
Hola Mario.

No se si está relacionado. Esto aportan Pablo y Daniel que les está ocurriendo:

El mar 17 ene 2017 00:11:22 CET, "Pablo J. Triviño Rodríguez" <ptrivino@educa.madrid.org>:
>
> Hola,
> **después de ejecutarse un update-grub (automático se entiende) o al menos eso me parece a mi**, tardaba muuuuucho en apagarse. Así que (probad, por favor) pulsé cursor abajo mientras se apagaba y te salen los comandos que se van ejecutando, el problema es este:
>
> **A stop job is running for Mysql community server (xx/10min)**
>
> Y las xx van avanzando y tarda 10 minutos en apagarse. Mario ya ha leido esto, pero he preferido escribirlo en un mensaje único pues me parece muy importante. Si el culpable es el MySQL de moodle, ya sabéis mi voto, pero no tiene sentido tener que esperar 10 minutos.
> Saludos.

Daniel: A mi me ha pasado lo mismo....y eso que uno de mis argumentos a la hora de convencer a la gente de usar MAX es que en unos segundos se apaga...no como en W2 que hay que esperar a veces mucho tiempo por culpa de actualizaciones.
