### ISSUE TITLE
MAX 9 beta 1: Incluir en repos Open Broadcaster Software, OBS

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#814]
Es un software increible para streaming que permite otras diabluras como capturar pantallas.

Esta recomendado por YouTube. Lo más importante para nosotros es que se emite bien con él para la Mediateca de EducaMadrid para hacer streaming.

[GitHub de OBS](https://github.com/jp9000/obs-studio/wiki/Install-Instructions#linux)

**Comment by mariodebian** [comment]
Subido como obs-studio
