### ISSUE TITLE
MAX 9 beta 1: Incluir en repos la última versión de wxmaxima. Mejora

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#815]
wxMaxima es software para matemáticas que en los repos de ubuntu está muy atrasada.

Si se puede incluir una versión actualizada en MAX mejor:

[Fichero fuente de la ver 16.04.1.1](https://launchpad.net/~blahota/+archive/ubuntu/wxmaxima/+files/wxmaxima_16.04.2.1.orig.tar.gz)

**Comment by mariodebian** [comment]
Done
