### ISSUE TITLE
Khangman

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#816]
La  configuración que tiene no es la misma de versiones anteriores. Esta en otro idioma. No he encontrado el paquete en español y con el aspecto que tenía antes. En MAX8 se podía varias el fondo y la temática de las palabras. Mandadme lo que haya que probar y decido que instalar.
Gracias

**Comment by mariodebian** [comment]
Si que es distinto pero funciona igual y por defecto arranca en español:


![khangman](https://cloud.githubusercontent.com/assets/522472/21750340/4968d1b2-d5b1-11e6-9438-834497aef0c7.png)
