### ISSUE TITLE
MAX 9 beta 1: Incluir en repos respin o makelive.

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#817]
Esto es una petición abrumadora en el grupo. Se trata de poder hacer versiones personalizadas de MAX a partir de la distro base a modo de backup o a modo de disponer de versiones de uso específico.

Antes existían remastersys o UCK. La primera era genial porque se podían hacer versiones live isntalables. Ambas han desaparecido.

Existen dos forks de remastersys especialmente atractivos Respin y makelive. Makelive está creada por los gallegos de minino artabros pero es debian pura.

Respin parece más potente. No se que hago mal cuando lo instalo pero luego las .iso que creo les falta un fichero para funcionar. Pero ahora dice en su web que funciona en Ubuntu perfectamente:

[Web de respin](http://www.linuxrespin.org/)
[GitHub de respin](https://github.com/ch1x0r/LinuxRespin)

**Comment by jrodriguezpascua** [comment]
Entiendo que a muchos TICs les puede ser de ayuda. Mario, por favor, valora la complejidad y el tamaño para ver si lo podemos incluir con las limitaciones de tiempo y presupuesto. ¿ok?

**Comment by mariodebian** [comment]
Hay un paquete mucho mejor y nuestro que es max-genlive, con algo tan simple como esto:

```
max-genlive amd64
```
Se hace un DVD de 64bits, tiene configuraciones forzadas para el servidor de desarrollo
Con
```
max-genlive --help
```
Se pueden ver algunas de las variables que se pueden sobreescribir.

PD.- Necesita bastante disco duro y una muy buena conexión a internet ya que se descargan varios gigas.
