### ISSUE TITLE
MAx beta 1: Incluir en repos Snap4arduino y s4a. Instalar por defecto biblioteca StandardFirmata de arduino

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#818]
Estas herramientas son esenciales para robótica. La primera es en HTML5 y viene de snap! un clon de Scratch que evita flash.

¡Ojo! hay que instalar la biblioteca **StandardFirmata** en el Arduino IDE

[Web de snap4arduino](http://snap4arduino.org/)

[Fuente de 32 bits](http://snap4arduino.org/downloads/1.2.2/Snap4Arduino_desktop-gnu-32_1.2.2.tar.gz)
[Fuente de 64 bits](http://snap4arduino.org/downloads/1.2.2/Snap4Arduino_desktop-gnu-64_1.2.2.tar.gz)

Y se ha parado el desarrollo de s4a (scratch4arduino) pero hay muchos profes que lo usan. Está en repos de MAx 8 la versión s4a15. Lo suyo es meter la s4a16 con el firmware instalado. Lo malo. No encuentro las fuentes. Las descargas están aquí:

[Ficheros de s4a](http://vps34736.ovh.net/S4A/)
[Fichero deb ](http://vps34736.ovh.net/S4A/S4A16.deb)
[Fichero firmware](http://vps34736.ovh.net/S4A/S4AFirmware16.ino)

**Comment by maxezek** [comment]
He puesto etiqueta +Aplicaciones para documentarlo allí puesto que no van de serie.

**Comment by mariodebian** [comment]
Subido s4a 1.5-3max2
