### ISSUE TITLE
MAX beta 1:  Vinculación con EducaMadrid. 

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#821]
Copio y pego el mensaje de Daniel de hoy 8 de enero. Muchas propuestas pero basadas en algo decidido en el grupo, vincular mas estrechamente MAX y EducaMadrid.

"Buenos días

Antes de nada gracias por la rapidez en dar respuesta a mis peticiones, así da gusto, aunque eso me lleva a seguir pidiendo, jajajaja:

Synapse ya funciona, Jnetmap ya está en Synaptic, PDFShuffler también, bitbloqoffline ya aparece instalado en programación......Todo perfecto

Mis nuevas propuestas:

    He instalado Shutter desde Synaptic y aparece en el menú accesorios ¿Podría aparecer en el menú gráficos? Es más propio que esté allí ==> **Ya es un issue** 
    He instalado Cmaptools desde Synaptic y aparece en el menú Oficina y a lo mejor estaría mejor en
 Educación Estudio que allí ya está Freemind que es del mismo estilo ==> **Ya es un issue** 
   
He instalado Scratch2offline desde Synaptic y aparece en Educación/Otras aplicaciones educativas pero a lo mejor es mejor que aparezca en el menú Programación junto al otro Scratch ==> **¡Ojo! esto es nuevo y tiene toda la lógica del mundo.**
    He instalado el cliente de Owncloud desde Synaptic y aparece en el menú Accesorios, a lo mejor estaría mejor en el menú Internet. Y ya puestos, que estuviera instalado de serie para  estrechar la relación con los servicios de Educamadrid. ==> **¡MUY IMPORTANTE! lo pongo como issue aparte**
    En Otras aplicaciones educativas incluir un enlace a Infopitágoras. Un servicio de Educamadrid, casi desconocido, pero muy potente: http://infopitagoras.educa.madrid.org/zprivada/login.php ==> **Considerar**
    También en otras aplicaciones Educativas, o a lo mejor en Accesibilidad, enlace a la página ALBOR de Educamadrid: http://www.educa2.madrid.org/web/albor **Considerar**
    Retomando lo de vincular MAX y Educamadrid,  a lo mejor una pestaña en el Menú general denominada Educamadrid con un submenú con accesos a: cloud, mediateca, aulavirtual, correo-e, AbiesWEB, Albor, Portal. ==> **ESto generaliza los considerar anteriores.**
    Ya puestos a mejorar la atención  a todos los alumnos ¿se podría tener instalado de serie el tipo de letra Opendislexyc? http://opendyslexic.org/ ==> **Considerar**
    WEB2board no me funciona. Lo bajo de la página de BQ pero sólo hay versión para Ubuntu 14.04 ¿Alguna idea para hacerlo  funcionar en MAX9? Es que si no no puedo utilizar Bitbloq ==> ** Hay que ver porque no funciona, con ello se evita instalar bitbloqoffline.
    Y queda pendiente de correos anteriores el poder instalar desde Synaptic la Suite Araword que iría a Accesibilidad por ejemplo" ==> **¡Ojo! ya es un issue pero es importante**

**Comment by mariodebian** [comment]
#820
