### ISSUE TITLE
MAX Beta 1: Incluir de serie el cliente owncloud y poner menú EducaMadrid

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#822]
Lo primero es importante. Es una mejora de EducaMadrid que lo convierte en un Google Drive con LibreOffice. 

[Pagina web](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)
[Ficheros de ubuntu 16.04](http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/) 

Si se puede crear un menú EducaMadrid con las consideraciones del issue #821 de Daniel

**Comment by mariodebian** [comment]
Cuidado al abrir bug duplicados, esto ya esta resuelto en :https://github.com/max-linux/max-desktop/commit/84fc8524a84d30ae3569cb4507101e7a470a27a6

y referenciado desde #820
