### ISSUE TITLE
MAX beta 1: Personalización de Infantil y Primaria. Cairo, khangman y ktuberling

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#823]
Replico un mensaje de Mario Olmo:

Vaya Reyes que estamos teniendo, jugando todo el rato con MAX9, jeje. Gracias por el trabajo Mario

Continuamos con infantil y primaria.
Al elegir la instalación de la personalización no instala la barra en **Cairo**, sí que instala todos los programas.
Os adjunto la configuración de la barra de Cairo. Se supone que al instalar Cairo-dock podéis cargar un tema. He guardado la configuración, espero lo haya hecho bien. Probadlo porfa

Sigo probando ;-)

El adjunto.

[MAXinfantilprimaria.zip](https://github.com/max-linux/max-desktop/files/692127/MAXinfantilprimaria.zip)

#816 **Khangman**, en esta versión es muy diferente. Falta español, poder elegir temas de palabras y fondos.

Se mantiene el fallo en **Ktuberling** al arrancarlo.

**Comment by Marito17** [comment]
Ktuberling no da fallo al abrirlo desde la terminal ni desde el menú, pero al añadir al cairo si sale un mensaje
"El archivo guardado se corresponde con una versión antigua de Ktuberling y desafortunadamente no se puede abrir en esta versión."

**Comment by mariodebian** [comment]
NO funciona el .zip que habéis adjuntado, ¿cómo configuro Cairo-Dock?

**Comment by Marito17** [comment]
Voy a dejando las especificaciones
Tema: Clear

En comportamiento
Posición: Superior
Animación y efectos de los iconos: Al pasar (nada)/ Al pulsar: Animación: Pulsar/ Al aparecer o desvanecer: Desvanecer

![screenshot at 2017-01-15 18_21_00](https://cloud.githubusercontent.com/assets/5994507/21964612/ac2dcfac-db4f-11e6-81b8-46a98cf0eea7.png)
