### ISSUE TITLE
MAX 9 beta 1: Firma digital, DNIe, FNMT,...

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#825]
Esto es ya para salirse del marcador si lo consigues. Se trata de intentar crear un paquete que permita instalar los certificados y la firma digital "pa tontos" como yo. En otras MAX ya lograste algo parecido. El reto ahora es mayor.

No se si Javier o Ismail te lo han propuesto ya pero es un clamor entre los miembros del grupo a causa de la entrada en vigor de las leyes 39 y 40/2015 este otoño. Nos afecta sobre todo a los funcionarios que en muchos casos tenedremos que hacer todo mediante firma digital. En linux parace casi una cosa imposible.

Tiene que poder incluirse los certificados y poder firmar digitalmente.

**Comment by mariodebian** [comment]
El certificado FNMT funciona perfectamente en cualquier navegador (llevo 2 años usándolo sin problemas)

Para el DNIe se instala el paquete: **dnie-support** que configura Firefox para los lectores de DNIe más comunes.

**Comment by maxezek** [comment]
Puse un correo con copia a Javier e Ismail. Ahora ha comenzado el proceso de habilitación lingüistica en Madrid. De ahí es importante el programa autofirma y el DNIe. Te adjunto el fichero de autofirma
[AutoFirma_Linux(2).zip](https://github.com/max-linux/max-desktop/files/694911/AutoFirma_Linux.2.zip)
Este software se está imponiendo como un estándar para la A.P. Dentro del zip viene un PDF que dice como instalarlo.

Sería bueno que **autofirma** estuviese instalado de serie.

Pregunta ¿el **dnie-support** funciona para el nuevo DNI 3.0?

**Comment by maxezek** [comment]
Traslado un comentario de **Jose Miguel Sancho** que me parece muy aclaratorio:

Llevamos tiempo con problemas para la firma electrónica de documentos y para la firma en paginas web (concurso de traslados,...)

Parece que las administraciones se han decantado por Autofirma para todos estos trámites, y tiene versión para linux:

http://firmaelectronica.gob.es/Home/Descargas.html

Yo lo he utilizado con certificado electrónico sin problemas en MAX8 pero en cierto momento me dejó de funcionar sin tener muy claro cual era el motivo.

Me tocó desinstalar certificados, volver a instalarlos, desinstalar la aplicación volver a instalarla.... Finalmente volvió a funcionar.

Creo que el problema vino por una actualización del FF, ya que por lo que leído, y me ha parecido entender, autofirma genera un certificado en el navegador asociado a la versión del mismo. Si actualizas el navegador el certificado deja de ser valido.

Se me ocurre que se podría crear un script que cada vez que se actualice el navegador se genere un nuevo certificado de autofirma, y todo esto en un paquete de MAX= Autofirma+script

Es una idea que tengo en la cabeza, y este mail es más un pensamiento en voz alta :)

**Comment by mariodebian** [comment]
Subido como paquete autofirma y preparado un disparador que monitoriza las actualizaciones de firefox

**Comment by mariodebian** [comment]
¿Debería ir por defecto?

**Comment by maxezek** [comment]
Si, dada la importancia que ha tomado el tema con las dos nuevas leyes

Mario Izquierdo <notifications@github.com> escribió:

> ¿Debería ir por defecto?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/825#issuecomment-271689979
[2]

**Comment by jrodriguezpascua** [comment]
Genial. Estoy de acuerdo con Ezequiel, este tipo de cosas es un punto a tener muy en cuenta, ya que pasa a ser obligatorio el uso de la firma digital, etc. Estupendo Mario. Trataré de que lo pruebe José Miguel que es quien más experiencia tiene con esto.
