### ISSUE TITLE
MAX beta 1: Personalización de Infantil y Primaria. Cosas que se quitan de la barra o faltan

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#826]
De Mario Olmo:

Hay dos programas que quitamos de la barra superior pero, desde mi punto de vista, **no** deberíamos quitar de la personalización. **Kgeography** es una aplicación que me gusta bastante. La otra es **Marble**. Propongo que esten dentro de la personalización instalados, pero **no** en la barra superior, como ya decidimos.

**Klettres** es un programa para aprender letras y silabas y su pronunciación, pero esta instalado también en el MAX versión normal (no la personalización). En definitiva que no creo que sea necesaria, pero a lo mejor esta dentro de un montón de aplicaciones de KDE. Lo comento por si queréis valorarlo.

No encuentro el grabador de sonidos, sorry.

**Blinken** (dentro de la personalización) aparece en el menú Juegos y en Educación> Otras aplicaciones educativas

**Comment by mariodebian** [comment]
Cierro este y seguimos en #823
