### ISSUE TITLE
MAX 9.5 beta 1: Incluir FreeCAD 0.16 en repos ==> Reabrir please

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#828]
Esto es un caballo de batalla. La versión 0.16 es la última y tiene la virtud de ser paramétrico lo que le da a FreeCAD un valor añadido excepcional. La web es [http://www.freecadweb.org/wiki/?title=Download](http://www.freecadweb.org/wiki/?title=Download)

**Funciona sin problemas en Ubuntu, Debian,... en Windows... Pero no en MAX 8 ni en MAX 9.** Estamos con un curso en el CTIF Madrid-Capital y el ponente lo explica en una Ubuntu 16.04 64bits pero los asistentes tienen que usar Windows  :-(

**En MAX se cierra o queda frito al arrastrar y soltar objetos** y **no permite** alterar la longitud de un objeto dibujado a **las décimas de milimetro**. Es decir, una medida de 10,7 la dibuja a 10 mm, trunca.

¿Quizás una biblioteca de Python?

FreeCAD es importante por el número de Tecnólogos y profesores de FP que lo están empezando a usar que ha crecido de manera espectacular.

**Comment by mariodebian** [comment]
Subido freecad 0.16.6707

**Comment by maxezek** [comment]
No consigo actualizar la beta para probarlo.

**Comment by maxezek** [comment]
Ya esta hecho y persiste el problema
![screenshot - 140117 - 19 12 16](https://cloud.githubusercontent.com/assets/6005738/21956994/91d74470-da8d-11e6-8c7a-a59cde4ab321.png)

Cuando se intenta redimensionar una pieza de en menos de 1 mm no lo hace. Al dar intro vuelve a la medida anterior entera. Y no se dibuja cunaod es instántaneo. ¿Alguna biblioteca?

En Ubuntu y otras funciona perfectamente

**Comment by maxezek** [comment]
Al ejecutarlo desde la línea de comando no sale ningún mensaje. Te paso la salida de por recomendación de Javier Puche:

ldd /usr/bin/freecad    para ver si ayuda:

[salidalddFREECAD16.txt](https://github.com/max-linux/max-desktop/files/706136/salidalddFREECAD16.txt)

**Comment by maxezek** [comment]
Mas cosas. En la consola de Python aparece por ejemplo:

FreeCAD.getDocument("Sin_nombre").getObject("Box").Length = '11 mm'

Y no deja introducir '11,3 mm' por ejemplo.

**Comment by maxezek** [comment]
El problema se reproduce también en MAX 9 32 bits ( y en MAX 8). Por si sirve de pista

**Comment by mariodebian** [comment]
Es un tema de "locales"

Si arrancas el programa en inglés sí funciona (con puntos como separador de decimales)

En consola:
```
LC_ALL=C freecad
```

**Comment by maxezek** [comment]
Vale por ese lado.

Sin embargo, en Ubuntu funciona perfectamente. Hay algo más por ahí  
que está fastidiando.

Compruebo esto para ver si me sirve para el curso de FreeCAD con MAX.

Mario Izquierdo <notifications@github.com> escribió:

> Es un tema de "locales"
>
>   Si arrancas el programa en inglés sí funciona (con puntos como  
> separador de decimales)
>
>   En consola:
> LC_ALL=C freecad
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/828#issuecomment-272698467
[2]

**Comment by maxezek** [comment]
Vale he comprobado que funciona:
LC_ALL=C freecad
y en español
LC_ALL=es_ES freecad

En este caso en terminal sale:

(process:30691): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

Pero funciona. Si consigues que arranque (¿cambiar el .desktop?) no cierres el ticket para que el martes en ese curso pueda verificar que no hay otros problemas.

**Comment by mariodebian** [comment]
¿En el segundo caso se ve el interfaz en español?

**Comment by maxezek** [comment]
Si. El interfaz en español. Mantiene en inglés alguna expresión sobre las propiedades de un objeto pero el resto está en castellano

**Comment by maxezek** [comment]
He puesto etiqueta +Aplicaciones para documentarlo allí puesto que no va de serie.

**Comment by maxezek** [comment]
Actualizar y corregir problemas al nuevo paquete 0.16 del[ ppa de desarrollo](https://launchpad.net/~freecad-maintainers/+archive/ubuntu/freecad-stable/+packages)

**Comment by mariodebian** [comment]
Subido 0.16.6712
