### ISSUE TITLE
MAX 9 beta 1: Meter en repos: Minetest + Mesecons, multibootusb, kataluga

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#829]
De Daniel Esteban:

Muchas gracias, ya está "purgado" y ya ha desaparecido la versión anterior de Openshot.

Ahora más peticiones por si es posible incluirlas, algunas seguro que ya están solicitadas pero por si acaso vuelvo a comentarlas:

**Instalar en Synaptic el mod mesecons de Minetest:**

[mesecons](http://mesecons.net/)

**Instalar en Synaptic multibootusb:**

[multibootusb](http://multibootusb.org/)

Instalar en Synaptic **Arasuite** (creo que hay un ticket abierto en Github):  (Ezequiel **Si el #783**) 

https://sourceforge.net/projects/arasuite/

He instalado desde Synaptic Katamotzejercicios (aparece después en otras aplicaciones educativas) pero no me funciona. Creo que es porque ahora se llama **Kataluga**. Si se pudiera instalar en Synaptic Kataluga sería perfecto:

**http://katamotzlectura.blogspot.com.es/p/kataluga.html**

(Ezequiel. Dice que es libre pero **no encuentro los fuentes**.  El autor, Gontzal Uriarte, Puedes encontrar en GitLab todo el código de mis programas. Uso Genie/Vala de Gnome. Si deseas colaborar enviame un mail: txasatonga@gmail.com)

Y por último que venga por defecto algo instalado para la firma digital, eso es algo que puede marcar la diferencia!!!!!

Y por hoy esas son mis peticiones, muchas gracias por todo el trabajazo, creo que está quedando algo muy chulo.

**Comment by mariodebian** [comment]
* [ ] mesecons
 * [ ] multiboot
 * [ ] arasuite
 * [ ] kataluga
 * [x] autofirma

**Comment by mariodebian** [comment]
De kataluga no hay ni fuentes ni descargas, cierro el issue

**Comment by maxezek** [comment]
OK, Kataluga entonces a +Aplicaciones.
