### ISSUE TITLE
MAX 9 beta 1: Infantil y Primaria, juegos y accesorios. Scid.

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#830]
De Mario Olmo.  Relacionado con #827 

 * [x] 1. Marble al arrancar aparece kwallet. (Ezequiel: Esto parece correcto pero no se si se puede evitar para que en la configuración de alumno se abra sin problemas directamente Marble.)

 * [x] 2. Hoy he actualizado falta **gnome-sound-recorder**. (Ezequiel: No existe mate-sound recorder. Incluir en la personalización de Inf y Prim.)

 * [x] 3. Sobre los juegos no ha habido casi participación. Pero he instalado **gnome-aisleriot, gnome-games y gnome-schess**. (Ezequiel: parece que no existen las versiones mate-xxxxx, instalar entonces esos paquetes para Inf y Prim)

 * [x] 4. Hay que quitar scid, al menos para primaria, porque entre que esta en inglés y que es demasiado profesional no tiene mucho sentido en la personalización. (Ezequiel: no lo quitamos, pero cumplimos #827 y quizás de serie no en Inf y Prim)

**Comment by mariodebian** [comment]
No se puede deshabilitar kwallet sin romper otras cosas (ahora recuerdo el cliente owncloud que guarda sus credenciales allí)

He subido un marble nuevo con un parche https://mail.kde.org/pipermail/marble-bugs/2016-April/004137.html que no necesita kwallet.

**Comment by maxezek** [comment]
He puesto etiqueta +Aplicaciones para poner Scid allí. Se supone que lo pidió Pedro porque los profes de Ajedrez se lo pidieron. Relacionar con https://chess24.com/es# y https://www.chess.com/es
