### ISSUE TITLE
MAX 9 beta 1: ¿¿Moodle?? ¿Solo LAMP?

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#832]
Lo planteo como pregunta porque no se porque razón tenemos **Moodle** de nuevo. Se quitó de la 8 por algo, supongo que peso.

Si las razones por las cuales se quitó de la 8 entonces lo sacaría también de la 9 y lo declararía en +Apliaciones.

Creo que al eliminar moodle también quitamos Apache.

Soy un mar de dudas, Yo creo que **LAMP** es un sello del SL y al menos mantendría eso. ¡Ojo! es mi opinión. A todo habría que consultarlo a Ismail y a Javier R. Pascua.

**Comment by jrodriguezpascua** [comment]
Muy buenas.

Yo dejaría Moodle. Ha sido una petición de algunos centros, que lo echaron de menos en la versión 8.0 y es una funcionalidad que les facilita mucho la vida y por ello usaban MAX.

Lo dicho, por mi parte, dejaría LAMP y Moodle instalado por defecto.

**Comment by mariodebian** [comment]
Lo ha vuelto a pedir Ismail y esta vez sin el asistente de instalación sino ya instalado y listo para usar.

**Comment by maxezek** [comment]
Hola Mario. 

Si lo he probado y es como magia :-) 

¿Y te da tiempo a aplicar la idea de Javier Puche? Se trata de no lanzar el servicio hasta que no se haga clic en el menú moodle. Es una idea, si eso puede causar alguna confusión o quitarte tiempo para otras urgencias, lo dejamos estar.

**Comment by maxezek** [comment]
Jose Miguel Sancho a hecho una observación que tiene toa la lógica del mundo.

Se trata de instalar la rama de Moodle 3.1 en vez de la 3.0 porque la 3.1 es LTS.

Y perdoname por freirte a issues y comentarios

**Comment by mariodebian** [comment]
Se argumentó en la lista que moodle 3.0 tiene soporte de seguridad de Ubuntu (o al menos debería) por eso ya ha instalado ese
