### ISSUE TITLE
MAX 9 beta 1: Blinken, juego de Inf y Primaria se queda semifrito.

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#835]
De Mario Olmo:

Podéis probar si funciona.
Cuando inicio el juego con blinken se enciende una de las luces y se queda parado. No me deja pulsar sobre los colores.

(Ezequiel: Lo he comprobado en MAX 9 estándar y me ocurre lo mismo. Y tampoco consigo sacar las **Preferencias**.)

**Comment by mariodebian** [comment]
Parece que le falta el backend de sonido y con eso no funciona, debería arreglarse instalando:

```
sudo apt install phonon4qt5 phonon4qt5-backend-gstreamer
```
