### ISSUE TITLE
MAX 9 beta 1: Reabir #828 FreeCAD sigue sin funcionar

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#836]
Hay que reabrir #828

Persisetn los problemas de FreeCAD. Revisar los comentarios de allí y eliminar esta issue.

**Comment by mariodebian** [comment]
Pues reabrelo, pero no abras uno nuevo.

Lo he probado y sí, ocurre que no se pueden poner decimales pero no veo forma de arreglarlo.
Deberíamos abrir un ticket en su repositorio...

**Comment by maxezek** [comment]
Es que no puedo. No tengo permisos para reabrirlo o no se hacerlo,  
que es lo más probable.

Con mi estatus puedo meter issues pero no puedo elegir otras cosas  
como indicar si es bug, enhance o si es para max9final.

Un abrazo,
Ezequiel

Mario Izquierdo <notifications@github.com> escribió:

> Pues reabrelo, pero no abras uno nuevo.
>
>   Lo he probado y sí, ocurre que no se pueden poner decimales pero  
> no veo forma de arreglarlo.
> Deberíamos abrir un ticket en su repositorio...
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, , or [1]mute the thread[2].
>       



Vínculos:
---------
[1] https://github.com/max-linux/<span%20index=
[2]
