### ISSUE TITLE
MAX 9 beta 1: Ampliar DNIe al nuevo DNIe 3.0. Mejora

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#837]
A vueltas con las firmas y certificados digitales.

tenemos el dnie-support para los distintos lectores pero luego han cambiado desde la CNP y la FNMT muchas cosas que hacen bastante incompresible seguir los pasos de instalación del DNIe.
Las páginas relativas a ello y que ponen que es instalable en Ubuntu 16.04 son:

[https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_320&id_menu=[17]](https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_320&id_menu=[17])

[https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1110](https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1110)

Y los paquetes para Linux:
[https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1112](https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1112)

Si puedes hacer algo para que sea fácil... Nunca he conseguido que funcione en MAX 8. :-(

**Comment by mariodebian** [comment]
Los scripts de instalación original de la Policía no son muy correctos (lanzan un firefox como root)

He imitado nuestro antiguo dnie-support para instalar los certificados en el perfil de Firefox de cada usuario (que haya arrancado FF al menos una vez)

El nuevo paquete se llama dnie3-support

![dnie3-support](https://cloud.githubusercontent.com/assets/522472/21963692/49e0c79c-db3f-11e6-989e-b411322e9168.png)

**Comment by maxezek** [comment]
He puesto etiqueta +Aplicaciones para documentarlo allí puesto que no van de serie y hay que documentarlo.
