### ISSUE TITLE
MAX 9 beta 1: Eliminar gtk-recordmydesktop, ya no hace falta

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#839]
Eliminar gtk-recordmydesktop, ya no hace falta puesto que tenemos **simple-screen-recorder**.

**Comment by maxezek** [comment]
Me acabo de dar cuenta de que está relacionado con #786

**Comment by mariodebian** [comment]
Ningún paquete depende de gtk-recordmydesktop
