### ISSUE TITLE
MAX 9 beta 1: Me han aparecido los dos OpenShot. Sobra uno

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#840]
Estoy con MAX 9 32 bits. Y están las dos versiones de OpenShot. Eliminar una, la 1.x?

**Comment by mariodebian** [comment]
Los paquetes de max dependen del nuevo pero un día dependieron del viejo, cuando se cambia la dependencia el viejo queda huérfano.

los paquetes huérfanos se desinstalan con:

```
sudo apt-get autoremove --purge
```

En la próxima ISO no vendrá, palabrita!!!!
