### ISSUE TITLE
MAX 9.5 beta: Owncloud a la nube de EducaMadrid. Nuevo menu MaX y EducaMadrid <= Retoques

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#841]
Mantenemos tal cual **owncloud** en el **menú Internet** pero:

 * [x] Cambiar el menú **MaX 9** por **MaX y EducaMadrid**

 * [x] Incluir ahí un **submenú MaX** que contendría lo que siempre a contenido el menú MaX: documentación, web, foro, manuales, instalación Inf. Prim, y de ahí...

 * [x] Eliminar los enlaces que venían de la 3.X que ponen: _Documentación de Usuario Instalada, se abre una ventana que no creo que sea la correcta._ y  _Documentación instalada (man), se abre una ventana vacia._
 
 * [x] Incluir un **submenú EducaMadrid** con todo aquello que pueda ser de referencia: la **nube**, ALBOR, InfoPitagoras, EducaSAAC, PEAC, Comunidad bilíngüe, Tecnorobot, Acceso al correo, Mediateca,...

El correo es **http://correoweb.educa.madrid.org/**
La mediateca es **http://mediateca.educa.madrid.org/**
EducaSAAC es **http://educasaac.educa.madrid.org/**
PEAC es **http://www.educa2.madrid.org/web/peac**
Comunidad Bilíngue es **http://comunidadbilingue.educa2.madrid.org/**
Tecnorobot es **http://tecnorobot.educa2.madrid.org/**

 * [ ] En ese acceso a la **nube** de educamadrid hacemos que owncloud apunte a **http://cloud.educa.madrid.org** y el nombre en este menú sea **Nube de EducaMadrid**. ¡Ojo! Manteniendo el actual que está en el menú Internet tal cual.

**Comment by maxezek** [comment]
Hola Mario. He cambiado el issue para adaptarlo al dilema ético. :-)

**Comment by mariodebian** [comment]
No puedo hacer que owncloud por defecto precargue una URL por defecto sin recompilarlo, creo que la URL del cloud es conocida como para seguir el asistente...

**Comment by mariodebian** [comment]
Aprovechando he subido la nueva version 2.4.0

**Comment by maxezek** [comment]
Perdón que estoy idiota... Resulta que te pongo todos los enlaces menos el fundamental el que lleva a EducaMadrid. Este debe ser el primero de la lista si se puede:

[EducaMadrid](https://www.educa2.madrid.org/educamadrid/)

**Comment by maxezek** [comment]
Reescribo todo, Aporto iconos para los dos submenús, EducaMadrid y MAX que tienen licencia CC0 de Pixabay (io.images) o bien son del propio EducaMadrid y retocadas por mi.

Para **submenú EducaMadrid** 
 
1.  Portal EducaMadrid comando **firefox https://www.educa2.madrid.org/educamadrid/ favicon** 
![portal](https://user-images.githubusercontent.com/6005738/36357663-852d92ce-1501-11e8-8ae1-12cd2d3ea509.png)
2. Correo web **firefox http://correoweb.educa.madrid.org/ favicon** 
![correo](https://user-images.githubusercontent.com/6005738/36357671-9b0fb20c-1501-11e8-97c2-4db8b5a426af.png)
3. Nube EducaMadrid **firefox http://cloud.educa.madrid.org favicon** 
![nube2](https://user-images.githubusercontent.com/6005738/36357687-e4ae91a8-1501-11e8-8d3f-0d6b48d377ca.png)
4. Mediateca **firefox http://mediateca.educa.madrid.org/ favicon** 
![mediateca2](https://user-images.githubusercontent.com/6005738/36357692-eef0276c-1501-11e8-8665-4b0dc4d0c723.png)
5. Albor **firefox https://www.educa2.madrid.org/web/albor favicon** 
![albor2](https://user-images.githubusercontent.com/6005738/36357697-f96942dc-1501-11e8-905d-fd34f0a1ca92.png)
6. EducaSAAC **firefox http://educasaac.educa.madrid.org/ favicon** 
![educasaac2](https://user-images.githubusercontent.com/6005738/36357702-022bb1a2-1502-11e8-81fc-8c592012a9d2.png)
7. Comunidad Bilíngüe **firefox http://comunidadbilingue.educa2.madrid.org/ favicon** 
![bilingue2](https://user-images.githubusercontent.com/6005738/36357706-099ff4ac-1502-11e8-9bb0-d8db21487ef0.png)
8. PEAC **firefox http://www.educa2.madrid.org/web/peac favicon** 
![peac2](https://user-images.githubusercontent.com/6005738/36357726-6a6906b6-1502-11e8-88a6-1559d6469cc4.png)
9. TecnoRobot  **firefox http://tecnorobot.educa2.madrid.org/ favicon** 
![tecnorobot2](https://user-images.githubusercontent.com/6005738/36357727-74637d18-1502-11e8-8c1a-ce3a3e922606.png)


Para **submenú MAX**

1. Web de MAX **firefox http://www.educa2.madrid.org/web/max/ favicon** 
![maxinside](https://user-images.githubusercontent.com/6005738/36356454-914444b8-14f2-11e8-833d-09c55a8decd1.png)
2. Instalación Infantil y Primaria **firefox /usr/share/max/install-personalizacion.html favicon**
![infantilprimaria2](https://user-images.githubusercontent.com/6005738/36356469-b6618652-14f2-11e8-95b1-c789de336d50.png)
2. Documentación **firefox http://www.educa2.madrid.org/web/max/documentacion/ favicon**
![manual](https://user-images.githubusercontent.com/6005738/36356476-d31ce8c2-14f2-11e8-8e04-d16b7fea8f95.png)
3. Manual de Instalación **firefox file:///usr/share/max-manuales/index.html favicon **
![instalacion](https://user-images.githubusercontent.com/6005738/36356487-edffaa8a-14f2-11e8-887a-a0377b1ab431.png)
4. Foros de ayuda **firefox http://herramientas.educa.madrid.org/foros/index.php favicon**
![foros](https://user-images.githubusercontent.com/6005738/36357644-458f5f8a-1501-11e8-8d6a-48be47eb7da9.png)
5. +Aplicaciones **firefox http://external.educa2.madrid.org/web/maxcontent/metapaquetes favicon**
![masaplicaciones](https://user-images.githubusercontent.com/6005738/36357647-4a1c1d9a-1501-11e8-9f77-aad18f7c270d.png)

Para el submenú previo de solo dos entradas, EducaMadrid y MaX, cambiar el icono de MaX para poner también: ![maxinside](https://user-images.githubusercontent.com/6005738/36356454-914444b8-14f2-11e8-833d-09c55a8decd1.png)

**Comment by mariodebian** [comment]
Me falta el icono de Info Pitágoras, los demas ya están cambiados.

**Comment by maxezek** [comment]
Para InfoPitǵoras:

![infopitagoras_64](https://user-images.githubusercontent.com/6005738/37764355-c5a6db0c-2dc1-11e8-9cb4-1274a67024cb.png)

**Comment by maxezek** [comment]
Una vez aplicado faltan detalles en el menú por la linea de EducaMadrid. Te adjunto imagen

![menus](https://user-images.githubusercontent.com/6005738/37847971-e1179cca-2ed2-11e8-9004-8c5388a04bfd.png)

Si me explicas un poco intento hacerte el menú. O te paso una maqueta o algo así

**Comment by maxezek** [comment]
No va el enlace:

 
* [ ] 1.  **Portal EducaMadrid**  **firefox https://www.educa2.madrid.org/educamadrid/ favicon** 
![portal](https://user-images.githubusercontent.com/6005738/36357663-852d92ce-1501-11e8-8ae1-12cd2d3ea509.png)


El problema es que en el menú falta la barra final /

Ahora apunta a https://www.educa2.madrid.org/educamadrid

y tiene que apuntar a:

**https://www.educa2.madrid.org/educamadrid/**
