### ISSUE TITLE
MAX 9 beta 1: El instalador todavía ofrece elegir entre Gnome y Xfce.

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#842]
MAX 9 beta 1: El instalador todavía ofrece elegir entre Gnome y Xfce.

Habría que indicar que el escritorio es MATE pero que no es elegible.

**Comment by mariodebian** [comment]
En el siguiente instalador ya no: https://github.com/max-linux/max-desktop/commit/824779666bfccb0a06d169674a2754bfa01c7343
