### ISSUE TITLE
MAX 9: Incluir logisim en una actualización de MAX 9. 

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#845]
Incluir **logisim** en una actualización de MAX 9.

Es antiguo pero funciona estupendamente. Es una mejora para una **actualización** de MAX 9 e incluir quizás de serie en una hipotética MAX 9.5.

Debe ir en el menú **Educación > Electrónica**.

**Comment by mariodebian** [comment]
Duplicado #844
