### ISSUE TITLE
Creación de USB arrancable

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#846]
Revisar usb-creator-gtk

**Comment by mariodebian** [comment]
El nuevo usb-creator-gtk sólo hace un dd del archivo iso en el dispositivo por lo que la imagen tiene que ser isohybrid: https://help.ubuntu.com/community/mkusb/isohybrid

 * El USB generado (x64) si arranca por UEFI
 * No arranca sin UEFI (isolinux)

**Comment by jrodriguezpascua** [comment]
¿Eso hace que el pendrive sólo valga para equipos nuevos? Por dar soporte a UEFI quitamos el 80% del parque, no creo que sea una buena solución. ¿tenemos alguna alternativa? ¿Se podría dar la opción de elegir si lo quieres para UEFI o norla?

**Comment by mariodebian** [comment]
Nunca he dicho que solo sirva para UEFI.

Todos los CD/DVD de Ubuntu y Debian (y muchas derivadas) de la última versión son isohybrid.

Básicamente se convierte el archivo ISO en un archivo arrancable que usa isolinux (el antiguo arranque) si la BIOS lo soporta o UEFI. **LOS DOS A LA VEZ CON LA MISMA ISO**.

**Comment by jrodriguezpascua** [comment]
ok, perdona. ;-)

Genial entonces.
