### ISSUE TITLE
MAX 9final: Problemas con la isohibrid beta2

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#851]
Intento darte toda la información posible. 

No consigo una DVDlive correcta ni USB live. Muchos problemas y en algún caso me ha dado un error en la falta de alguna biblioteca pero no hice foto, sorry. Adjunto fotos de diferencias de MAX 9 y MAX8
![screenshot - 270117 - 10 51 47](https://cloud.githubusercontent.com/assets/6005738/22366744/a267bb8a-e47e-11e6-9b51-9af2c7db1a55.png). Sorprende el candado y que no concuerdan ficheros.

De Rober:

- Con el USB no consigo iniciar instalación en modo EFI. La instalación en
modo normal funciona. (Ezequiel: yo tampoco)

- Desde el DVD consigo instalar en modo EFI. Es un portátil con disco SSD
por lo que va bastante rápido, arranque en unos 7 segundos y apagado
en apenas 4. La MAX 8 recuerdo que me dio algún problemilla ya que no
conseguía crear correctamente las entradas EFI en la BIOS pero con la
MAX 9, todo OK 8-) ( Ezequiel: Yo no he consguido tostar el DVD)

Ah!!! y esto también se me ha reproducido desde el USB, simplemente con
iniciar desde el USB sin realizar ninguna operación, sólo iniciar y apagar, y al
apagar se quedó ya en espera. 

Adjunto aquí pantallazos de gparted que son sorprendentes:
![screenshot - 260117 - 13 03 35](https://cloud.githubusercontent.com/assets/6005738/22366850/081e9f84-e47f-11e6-88a4-2273a7a6ed13.png)
![screenshot - 260117 - 14 32 42](https://cloud.githubusercontent.com/assets/6005738/22366858/10a34434-e47f-11e6-9ac0-71e9b2a2646c.png)

Si recabo más información te la aporto

**Comment by mariodebian** [comment]
Yo he probado la ISO en VirtualBox (no tengo un PC donde instalarlo para probar)

 * Modo BIOS (arranca perfectamente, como siempre)
 * Modo UEFI (arranca bien, tuve algún problema con que pillase los archivos de arranque: startup.nsh pero debe ser un bug de virtualbox con los nombres de los archivos *.efi)

Dentro de esa máquina virtual he generado un pendrive de 64 bits y arranca en mi portátil tanto en modo BIOS como UEFI, no lo he instalado.

El archivo ISO no tiene particiones por lo que el USB no las tiene.
 * Prueba a generarlo con UNetbootin, el generador de discos de Ubuntu simplemente copia la ISO al USB.
 * Prueba a generar un USB de un Ubuntu 16.04 para ver si ocurre lo mismo.
