### ISSUE TITLE
MAX 9.5 beta1: Incluir gnome-schedule en el repo

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#853]
En Ubuntu 16.04 ha desaparecido gnome-schedule. Pero hay versión instalable en el github:

[Gnome-schedule](https://github.com/GNOME/gnome-schedule)

He probado el .deb propuesto aquí 

[Versión de 64 bits](https://bugs.launchpad.net/ubuntu/+source/gnome-schedule/+bug/1576060/comments/23)

Y funciona pero no añade a la entrada del menú 'gksu' porque funciona si es como root.

Sería conveniente incluir plantillas. Una debe llamarse **Apagado automático** con la orden **/sbin/poweroff**.

**Comment by mariodebian** [comment]
Subido version 2.3.0 y añadida plantilla por defecto "Apagar a las 18:00"

**Comment by maxezek** [comment]
Me devuelve el siguiente error:

**Comment by maxezek** [comment]
Nada. he purgado porque tenía una versión previa y funciona. Sorry.
