### ISSUE TITLE
MAX 9 final actualización: Cambiar denominación/menú de synapse y buscador de archivos mate

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#854]
Ahora mismo los usuarios están despistados. Sería conveniente que estas aplicaciones apareciesen en el menú principal justo debajo de **Lugares** y **Sistema** como:

**Buscador de archivos**         que sería mate-search-tool
**Buscador de aplicaciones**   que seria synapse

**Comment by mariodebian** [comment]
Hecho en ee03b96ddb7eb960ba9aeee3207e5963c9434858
