### ISSUE TITLE
MAX 9 final actualización: Cambiar el icono de openboard en el menú PDI

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#855]
Ahora está con el icono de onboard (accesibilidad)

El correcto es:

[Icono de OpenBoard](https://github.com/OpenBoard-org/OpenBoard/blob/master/resources/images/OpenBoard.png)

**Comment by mariodebian** [comment]
Actualizado de 1.3.4 a 1.3.6 y cambiado icono
