### ISSUE TITLE
MAX 9 final actualización: hacer que el viejo ardesia sea instalable

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#858]
Reportado por Javier Puche y confirmado por mi que era un rpograma que me molaba :-)

Ahora mismo salta un conflicto al intentar instalar **ardesia**. Salta esto:

_Preparando para desempaquetar .../ardesia_1.1-2.1_amd64.deb ...
Desempaquetando ardesia (1.1-2.1) ...
dpkg: error al procesar el archivo /var/cache/apt/archives/ardesia_1.1-2.1_amd64.deb (--unpack):
 **intentando sobreescribir `/usr/bin/ardesia', que está también en el paquete max-mate-menus 9.0.max21**
dpkg-deb: error: el subproceso copiado fue terminado por la señal (Tubería rota)
Procesando disparadores para menu (2.1.47ubuntu1) ...
Se encontraron errores al procesar:
 /var/cache/apt/archives/ardesia_1.1-2.1_amd64.deb
Procesando disparadores para max ...
E: Sub-process /usr/bin/dpkg returned an error code (1)_

Solo se instala  el selector de la posición de la barra de ardesia que era un pequeño script que hice en su tiempo con zenity y funcionaba.

No es importante pero el programa es tan sencillo que sorprende que no haya saltado ningún fork. Me gustaría poder ver que funciona.

**Comment by mariodebian** [comment]
Subido ardesia 1:1.1-2.1max1 coinstalable con max-mate-menus
