### ISSUE TITLE
MAX 9 final actualizacion: Volver a poner en repos pseint

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#860]
Ahora es un autoejecutable. Hay versión de 32 y 64 bits.

La fuente está aquí: 

[Forja de PseInt](http://pseint.sourceforge.net/index.php?page=descargas.php)

Interesa que esté por defecto para pseudocódigo la regla de lenguaje del módulo de FP IES Clara del Rey que es el de Amadeo Mora.

**Comment by mariodebian** [comment]
Parcheado, compilado (desde fuentes) y subido pseint 20170523-max1
