### ISSUE TITLE
MAX 9 final actualización: Al instalar aplicaciones muchas de ellas no aparecen en el menú

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#861]
He intentado buscar este problema en viejas issues de MAX 8. 

Al instalar no se refrescan los menús y hay que salir de la sesión y volver a entrar para que aparezcan en el menú.

**Comment by maxezek** [comment]
Me acabo de dar cuenta que lo he duplicado con el #865

**Comment by mariodebian** [comment]
Duplicado #865
