### ISSUE TITLE
MAX 9 final actualización: Eliminar el mensaje de las fuentes de mscorefonts

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#863]
Aparece continuamente. Y no está claro que es lo que pasa, si las tenemos instaladas realmente o no. Según las pruebas de José Miguel Sancho es que no y la forma de evitarlo ahora es:

_Casi me vale la solución Ezequiel ;) (te  has adelantado  a mi solución por poco)_

_La cuestión es que el paquete ttf-mscorefonts aparece instalado, aunque las fuentes no están_ _instaladas (se puede buscar la fuente arial en libreoffice y no está)_

_Lo que he hecho es :_

**sudo rm -rf /var/lib/update-notifier/package-data-downloads/partial/***

_y luego_

**sudo apt-get install --reinstall ttf-mscorefonts-installer**

_Y vemos como las fuentes se descargan y se decomprimene en el lugar adecuado_

_Si alguien quiere comprobarlo, yo miraría (aunque no me salga el aviso de marras):_

_1 ¿están las fuentes instaladas?_
_2 Probamos lo que comento anteriormente:_

sudo rm -rf /var/lib/update-notifier/package-data-downloads/partial/*
sudo apt-get install --reinstall ttf-mscorefonts-installer

_3 volvemos a comprobar si están las fuentes instaladas_

_Esto soluciona el problema de tener las fuentes instaladas, pero no el de que el paquete falle._

_Supongo que cuando se actualice el paquete a la versión 3.6 que ya está en debian desde hace tiempo se solucionará_

**Comment by maxezek** [comment]
Ayuda. Cuando se hace una actualización el error que da ese el siguiente:

> Configurando update-notifier-common (3.168.4) ...
> ttf-mscorefonts-installer: processing...
> ttf-mscorefonts-installer: downloading https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/andale32.exe
> Des:1 https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/andale32.exe [162 B]
> Descargados 198 kB en 6s (32,6 kB/s)                                           
> ttf-mscorefonts-installer: downloading https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe
> Des:1 https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe [162 B]
> Descargados 554 kB en 3s (152 kB/s)                                            
> ttf-mscorefonts-installer: downloading https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/arialb32.exe
> Err:1 https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/arialb32.exe
>   Protocol "http" not supported or disabled in libcurl
> E: Fallo al obtener https://netcologne.dl.sourceforge.net/project/corefonts/the%20fonts/final/arialb32.exe  Protocol "http" not supported or disabled in libcurl
> 
> E: Falló la descarga

**Comment by mariodebian** [comment]
Actualizado a msttcorefonts (3.6max1) de Debian
