### ISSUE TITLE
MAX 9 actualización: que TCOS monitor en profesor sea Control de aula  TCOS

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#864]
Los que están entrando de nuevas a MAX y son TIC acostumbrados a Güin2 se pierden un poco buscando un control de aula.

La idea es que en el menú y en el escritorio en vez del nombre TCOS monitor aparezca como:

**Control de aula TCOS**

o

**TCOS control de aula**

**Comment by mariodebian** [comment]
Hecho en tcosmonitor (0.2.51max3)
