### ISSUE TITLE
MAX 9.1? : Incluir DIA que se nos ha pasado

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#868]
Reportado por Javier Puche.

En todas las versiones de MAX llevamos el creador de diagramas **DIA**. Si sacamos una .iso con una versión mejorada de la MAX 9 hay que mirar que espacio disponible tenemos y volverla a incluir.

**Comment by jrodriguezpascua** [comment]
Totalmente de acuerdo. Dia es un programa muy utilizado, sobre todo en los ciclos de FP de informática, para los E/R de Base de Datos.
