### ISSUE TITLE
Cualquier MAX: JAVA en los navegadores modernos

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#870]
Todavía quedan aplicaciones web que usan JAVA. Pero los navegadores modernos han dejado de soportarla.

Solo una versión extendida de Firefox lo soporta: firefox-esr pero solo hasta el 2018.

Esto afecta a todo aquello que use JClic como InfoPitagoras.

Para obtener firefox-esr en Ubuntu 16.04 existe este ppa 

[Firefox-esr](https://launchpad.net/~jonathonf/+archive/ubuntu/firefox-esr)

No se si hay una solución viable. Quizás a partir de:

[Web start aplplications](https://blogs.oracle.com/java-platform-group/launching-web-start-applications)

**Comment by mariodebian** [comment]
Si ya es un lío mantener perfiles con 2 navegadores con 3 sería una locura.

**Flash y JAVA están muertos** y cuanto antes lo entendamos mejor, si se necesita siempre se puede instalar en una máquina virtual un Windows XP o MAX 6.5.
