### ISSUE TITLE
Incluir paquete de fuentes en max-desktop

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#872]
Deberíamos incluir los paquetes de fuentes:

- fonts-crosextra-caladea
- fonts-crosextra-carlito

Mejoran la experiencia de usuario cuando abres documentos hecho con fuentes Calibri y Cambria de paquetes ofimáticos propietarios.

Reportado por José Miguel Sancho.

**Comment by maxezek** [comment]
Se nos ha debido de pasar. Era el MAX 9 beta 1: Mejora de compatibilidad de LO con MS. Tipografías. #834 . LibreOffice lo hemos configurado, creo, para que sustituya automáticamente las fuentes callibri y calisto, pero al final se nos ha olvidado incluir de serie los paquetes :-(
