### ISSUE TITLE
MAX 9.5 beta 1: Paquetes de robótica. Incluir Snap4arduino

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#875]
Es una propuesta de Antonio. No se siserá posible pero propne lo siguiente:

Pues vaya. Blockly@arduino..  No lo he probado aún. Pero si pulsas en Configure blocks, sale de todo:

http://technologiescollege.github.io/Blockly-at-rduino/?toolbox=toolbox_arduino_all&url=./examples/./mbot/mbot-suiveur-ligne.xml#

Descargando y descomprimiendo no me salen los bloques al ejecutar el index, Seguro que hay que hacer algo para instalarlo. Pero en teoría se entiende con Arduino IDE creo

Recordando lista de curiosidades que voy encontrando... Si son paquetizables, extendemos posibiliades para cuando vuelvan a cortarnos internet en los centros.

* [ ] [Code Bug:](http://www.codebug.org.uk/create/codebug/new/)
* [ ] [Blockly@rduino:](http://technologiescollege.github.io/Blockly-at-rduino/)
* [ ] [Music Blocks:](https://walterbender.github.io/musicblocks/)
* [ ] [Microsoft Make Code:](https://makecode.com/)
* [ ] [Beetle Blocks: ](http://beetleblocks.com/run/)
* [ ] [Open Roberta:](https://lab.open-roberta.org/)  Está como ticket. #857
Por fin aparece una versión alternativa para s4a que va bastante regular. Snap!4arduino y que ya estan usando en MAX 9 algunos centros desde el .deb de su página oficial:
* [x] [Snap4arduino:](https://github.com/bromagosa/Snap4Arduino)  Su web con los .deb esta [aquí ](http://snap4arduino.rocks/)

Saludos.

**Comment by mariodebian** [comment]
* [x] snap4arduino
* [x] blocklyduino
* [ ] Code Bug => No se puede ejecutar offline, ¿empaqueto un lanzador a su web?
* [ ] Blockly@rduino => la versión [offline](https://github.com/technologiescollege/Blockly-rduino-communication) es sólo para windows 
* [x] Music Blocks => carga con Chromium en lugar de electron
* [ ] Microsoft Make Code => No se puede ejecutar offline, ¿empaqueto un lanzador a su web?
* [ ] Beetle Blocks => La [instalación offline](https://github.com/bromagosa/beetleCloud/blob/master/INSTALL.md) lleva muchas dependencias (PostgreSQL, LUA...), ¿empaqueto lanzador a su web?
* [ ] Open Roberta

**Comment by maxezek** [comment]
Pues pasamos del resto. Para robótica estamos bien cubiertos creo. Voya a ver si puedo usar nativefier y crear paquetes para las versiones de codebug, blokly@duino, Mocosoft make code y beetleblocks (si tiene versión online que no los se). Si lo consigo lo pongo en +Aplicaciones.
