### ISSUE TITLE
MAX 9 actualización: TCOS-standalone y vncserver

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#877]
No se si tiene algo que ver con el de Rober sobre vino #876

Desde el PC de profesor con tcosmonitor no funciona vnc por error de conexión al puerto 5900. 

Resulta que el stunnel.conf de tcos-standalone permite conexiones ahora por puerto **8998** en vez del **5900** que tradicionalmente usa el vncserver.

No se si era necesario porque tenemos vino instalado pero he instalado también tightvnceserver.

Y luego con el editror dconf he cambiado la clave **org.gnome.desktop.remote-access.altenative-port** a 8998 en el pc del profesor y en el de alumno.

Ahora si me conecto para ver el PC de alumno con tcosmonitos

**Comment by mariodebian** [comment]
TCOS usa los puertos 8998 y 8999 para su intercambio de datos con clients mediante XMLRPC (stunnel lo mismo pero en modo seguro), no tiene nada que ver con escritorio remoto VNC.
