### ISSUE TITLE
Nueva versión de LeoCad

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#879]
Reportado por Antonio Ruiz.

Tenemos la antigua. ¿Lo añadís al github?

https://github.com/leozide/leocad/releases

Por cierto. Ni idea de cómo como compilar en MAX esta nueva versión sin esperar a que la compiléis vosotros ¿Alguna orientación?

He conseguido ver cómo es gracias a Wine. También he probado Lego Designer con wine. Van.

Saludos.

**Comment by mariodebian** [comment]
Actualizado:
  * ldraw-parts 1601+ds-1
  * leocad 17.07-2
