### ISSUE TITLE
Problemas conexión VLC de MAX 9 con servidores multimedia DLNA

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#881]
Reportado por Manuel Galvez.

En el grupo se habló de NAS de synology, y me fascinó. Tengo funcionando un DS1515 con un RAID5 de 4 discos + 1 SSD de buffer, y estamos super contentos.

La cuestión es que entre otras cosas, lo utilizamos como servidor multimedia por DLNA y funciona de bien desde culalquier cliente, incluido el VLC. Con MAX75 y MAX8 con VLC se accede perfectamente al catálogo de vídeos y películas disponible, pero en MAX9 no funciona. He actualizado y reinstalado VLC en MAX9, pero nada.

**Comment by mariodebian** [comment]
Arreglado, subido nuevao paquete libupnp6_1.6.19+git20160116-1.2max1

Bug Ubuntu:
 * https://bugs.launchpad.net/ubuntu/+source/libupnp/+bug/1571199

Bug Debian:
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813249
