### ISSUE TITLE
scratch no reconoce los mp3 ni los jpg en 64 bits en MAX 9.0

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#882]
El problema vuelve a aparecer en MAX 9.0.

Reportado por Antonio.

Anterior ticket: https://github.com/max-linux/max-desktop/issues/750

Saludos.

**Comment by mariodebian** [comment]
Subido paquete de MAX 8.0 con soporte MP3 y JPEG
