### ISSUE TITLE
Las impresoras se desactivan.

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#883]
Reportado por Antonio.

A lo mejor influye el modelo de impresora. No sé...

Lo malo es que los que podemos llamar usuarios normales no saben activar la impresora. Ni tampoco van a ir a buscarlo. Como mucho, van a la cola de impresión y la borran. Pero la desactivación sigue y no se imprime.

Hace tiempo me daba la sensación de que se producían más errores y más cola de impresión bloqueada en MAX que en Windows en los equipos de la sala de profesores. Y esa impresión también la tenían los compañeros, me decían que vaya MAX y se iban a windows a probar imprimir.

Como  era sólo una impresión personal y no quería pensar que fuera así y seguramente alguien me diría que ya estaba con mi manía de resaltar los fallos de MAX sobre Windows, no quise decir nada.

Como no sabía que era por esto (seguramente), no lo solucionaba. Hasta que me he dado cuenta no hace demasiado.

Creo que al reiniciar se arregla a veces. Pero si tocaba desactivarse de nuevo, volvía a las mismas.

Hay que intentar que eso no se siga produciendo. Creo que habría que añadirlo como ticket, porque es algo que se produce. Cuando sabes la solución, bien. La solucionas rápido y notas menos ese efecto. Cuando no, si el equipo es dual, te vas a Windows e imprimes. Y si no es dual, te quedas despotricando de MAX porque no hay manera de imprimir al no saber la solución.

Por cierto. En el cole van a contratar una empresa diferente de fotocopiadoras, por el sistema de control de fotocopiadora y de impresión desde las aulas que está imponiéndose en muchos centros según me dicen. Entiendo que sabrán configurarlo para Windows, pero no sé para MAX, así que... volvemos al problema de las empresas y su formación linux. Así como al problema de impresión con contraseña que MAX normal no maneja muy bien y los centros quieren tenerlo.

Saludos.

David González Arroyo <> ha escrito:

A mí me ha pasado también, pero en contadísimas ocasiones. Lo bueno es que basta con hacer click derecho sobre el icono de la impresora y volverla a activar.

El dom 24 sep 2017 16:56:21 CEST

Me pasa con mucha frecuencia, aquí y en el colegio.

No imprime la impresora y es por esto. Se desactiva inesperadamente.

Saludos.

**Comment by mariodebian** [comment]
Más info:

*  https://superuser.com/questions/280396/how-to-resume-cups-printer-from-command-line
*  https://bugs.launchpad.net/ubuntu/+source/cupsys/+bug/41313

```diff
--- scheduler/printers.c.orig	2006-09-26 07:46:29.000000000 -0400
+++ scheduler/printers.c	2006-09-26 07:47:53.000000000 -0400
@@ -123,7 +123,7 @@
   cupsdSetString(&p->job_sheets[0], "none");
   cupsdSetString(&p->job_sheets[1], "none");
 
-  cupsdSetString(&p->error_policy, "stop-printer");
+  cupsdSetString(&p->error_policy, "retry-job");
   cupsdSetString(&p->op_policy, DefaultPolicy);
 
   p->op_policy_ptr = DefaultPolicyPtr;
```
