### ISSUE TITLE
Cambiar OpenShot por KDEnlive

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#884]
PArece que OpenShot no hay forma de hacerlo funcionar en condiciones, por lo que quizá deberíamos pasar a KDEnlive.

Antes de cerrar este ticket habría que valorar si hacemos el cambio. Consulto al grupo.

**Comment by jrodriguezpascua** [comment]
Volvemos a retomar el cambio de OpenShot que da muchos problemas, por KDEnlive, que parece que funciona mucho mejor.

Esto sería para la próxima versión, pero se podría estudiar el ejecutar un paquete de actualización no que quite OpenShot, pero sí que instale KDEnlive por defecto en las primeras actualizaciones de una MAX recien instalada.

**Comment by mariodebian** [comment]
Compilado y actualizado Openshot a 2.4.1
Compilado kdenlive 17.04.3
