### ISSUE TITLE
MAX 9.5: Actualizar Gcompris

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#886]
También ha mejorado en la 0.81

Fuente en  [https://github.com/gcompris](url)

Web [http://www.gcompris.net/index-es.html](url)

**Comment by jrodriguezpascua** [comment]
Cuidado, porque Gcompris cuando lo instalas de los repositorios no deja enlace en el menú de MAX. Habría que configurar también el lanzador.

**Comment by mariodebian** [comment]
Actualizado a 15.10, y si tiene grupo de menú en "Otras aplicaciones educativas", aunque hay que reiniciar el panel de mate para que lo recargue (eso es otro bug)

gcompris-qt es un "fork" más simple para que se pueda ejecutar en una RaspberryPi (por ejemplo), compilado (contra QT-5.5 en lugar de 5.6)

**Comment by maxezek** [comment]
Parece ser que hay nueva actualización tanto para 32 como 64 bits que interesa que se añada:

[GCompris](http://gcompris.net/downloads-es.html)

Justo abajo de la página está el enlace al código fuente

**Comment by maxezek** [comment]
Acabo de ver que si está la nueva versión pero que es gcompris-qt. 

Vuelvo a cerrarlo hasta que me indiquen si ese es el paquete ahora a incluir en la personalización de infantil y primaria.

**Comment by maxezek** [comment]
Finalmente hay que reabrir. Da el siguiente error cuando se ejecuta:

> $ gcompris-qt 
> exeCount set to:  3
> QQmlApplicationEngine failed to load component
> qrc:/gcompris/src/core/main.qml:21 module "QtQuick" version 2.6 is not installed
> 
> Error: Your root item has to be a Window.

En la pruebas de Antonio dice lo siguiente:

> No hay manera con la instalación mediante synaptic y apt. Da el mismo error.
> 
> Pero sí lo he podido ejecutar.
> 
> Me he descargado el archivo sh desde aquí.
> [https://gcompris.net/index-en.html](https://gcompris.net/index-en.html)
> 
> He ejecutado el archivo sh, pero sale un archivo de texto con la licencia y tienes que ir hasta el final.
> 
> Luego debes pulsar en Y para aceptar la licencia. Luego sigue y creo que hay que pulsar otra vez en Y.
> 
> Una vez descomprimido, se accede a /home/madrid/Descargas/gcompris-qt-0.81-Linux/bin
> 
> Se ejecuta gcompris-qt.sh
> 
> Y funciona.

**Comment by maxezek** [comment]
Finalmente reabro issue porque da error de ejecución nuestro paquete en repos:

> $ gcompris-qt 
> exeCount set to:  3
> QQmlApplicationEngine failed to load component
> qrc:/gcompris/src/core/main.qml:21 module "QtQuick" version 2.6 is not installed
> 
> Error: Your root item has to be a Window.

Antonio dice que al descargar de la página oficial si funciona:

No hay manera con la instalación mediante synaptic y apt. Da el mismo error.

Pero sí lo he podido ejecutar.

Me he descargado el archivo sh desde aquí.
https://gcompris.net/index-en.html

He ejecutado el archivo sh, pero sale un archivo de texto con la licencia y tienes que ir hasta el final.

Luego debes pulsar en Y para aceptar la licencia. Luego sigue y creo que hay que pulsar otra vez en Y.

Una vez descomprimido, se accede a /home/madrid/Descargas/gcompris-qt-0.81-Linux/bin

Se ejecuta gcompris-qt.sh

Y funciona

**Comment by maxezek** [comment]
> $ gcompris-qt > exeCount set to:  3> QQmlApplicationEngine failed to load component> qrc:/gcompris/src/core/main.qml:21 module "QtQuick" version 2.6 is not installed> > Error: Your root item has to be a Window.

**Comment by mariodebian** [comment]
La versión QTQuick 2.6 está en Ubuntu más modernos, después de mil pruebas parcheando las dependencias arranca pero no van los menús... (necesita una versión de QT más moderna)

![gcompis-qt](https://user-images.githubusercontent.com/522472/37620263-f742c71e-2bbb-11e8-84cc-7071d62bf399.png)


Plan B, usar el .sh de su web y generar 2 paquetes deb similares al anterior.

**Comment by mariodebian** [comment]
Subida y probada versión 0.90 (incluye un QT más nuevo)
