### ISSUE TITLE
MAX 9.5: Configuración de proxy de MAX

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#888]
Retocar el configurador para que en los centros con VLAN 100 con macrolan o fibra FTTH se ponga como DNS la IP del proxy 213.0.88.85.

**Comment by mariodebian** [comment]
MAX va por defecto con DHCP, no se puede forzar a usar un DNS, se usa los que provee el router que atiende la petición DHCP.

¿Por qué no modificáis los router para que den ese DNS?

**Comment by maxezek** [comment]
Luchas con MadridDigital (alias ICM) Es un problema propio de Madrid que no tiene sentido. Y efectivamente las veces que se consigue es cuando ellos ponen las DNS en el router como es debido.
Olvídalo. Yo mismo lo cierro.
