### ISSUE TITLE
MAX 9.5: Configuración de Firefox

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#889]
¡Ojo! Cuando llegue el momento hay que volver a comprobar si es necesario porque a lo mejor futuras versiones de Firefox lo tienen resuelto.

Existen problemas de certificados que afectan a páginas muy usadas. Se resuelve ahora en:

about:config > security.tls.version.min a 0

Encontrado por Roberto Mengibar. Le pongo la etiqueta de paquetes-max porque afecta a la configuración de alumno en homealumno.

**Comment by mariodebian** [comment]
Se ha configurado el perfil por defecto para usar 0.

No se si los perfiles creados antes de actualizar se pondrá en cero o habrá que borrarlos.
