### ISSUE TITLE
Max 9: Skype no funciona

### ISSUE THREAD

**Issue by dgonzalezarroyo** [max-linux/max-desktop#890]
Skype no funciona en MAX 9. Nos lo cuentan en los foros y lo he comprobado --> http://herramientas.educa.madrid.org/foros/viewtopic.php?f=2&t=3558

**Comment by mariodebian** [comment]
Creo que deberíamos borrar SKYPE de los repos de MAX.

La nueva versión sólo es de 64 bits: https://repo.skype.com/deb/pool/main/s/skypeforlinux/

Y no deja de ser un navegador chromium con vitaminas empotrado en una ventana con la versión web de skype.

**Comment by jrodriguezpascua** [comment]
Skype es una herramienta muy utilizada en todos los centros que tienen proyectos de Erasmus, es necesario tenerla. Si lo han quitado de 32 bits, será en esos equipos donde no debemos instalarlo, pero en la versión 64 bits, que es la más utilizada cada día, creo que es una herramienta indispensable.

**Comment by mariodebian** [comment]
Nuevo paquete max-skype, para 32 bits es un lanzador a la web de skype: https://web.skype.com/ para 64 bits es el reempaquetado de el repo de SKYPE oficial.
