### ISSUE TITLE
Autofirma ha dejado de funcionar

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#892]
REportado en la lista de MAX por Ezequiel.
Hola.

La versión 1.4 que tenemos en el repositorio falla. Si se intenta reinstalar dice que la suma hash difiere.

Solución he actualizado desde as descargas oficiales del ministerio la 1.5

http://firmaelectronica.gob.es/Home/Descargas.htm

Y todo funciona.

Saludos,

**Comment by mariodebian** [comment]
Duplicado #891 
Ya está subido.
