### ISSUE TITLE
MAX 9.5: Actualizar VirtualBox

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#894]
Ahora tenemos la 5.0.4.

Está bastante obsoleta. Incluir la nueva 5.2.2.

[Fuentes oficiales de virtualbox](https://www.virtualbox.org/browser/vbox/trunk)

**Comment by mariodebian** [comment]
La versión 5.2.x depende de QT >= 5.6 (la nueva barra de iconos la necesita)
Compilado y subido 5.1.30
