### ISSUE TITLE
El  problema de los repositorios... Sigue fallando

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#899]
Copio y pego el correo de Rober:

Hoy era requisito indispensable poder actualizar la MAX9 para
poder instalar un software en unos equipos de un centro que
utilizan MACROLAN.

No había manera que el "sudo apt update" se descargara los
índices sin que mostrara el dichoso error de "La suma hash difiere".

Finalmente encontré la siguiente solución en un foro que ha sido
mano de santo:

Crear el fichero "/etc/apt/apt.conf.d/99fixbadproxy"
con las siguientes líneas:

Acquire::http::Pipeline-Depth 0;
Acquire::http::No-Cache true;
Acquire::BrokenProxy    true;

¡¡¡Me ha actualizado a la primera!!! Para realizar pruebas podéis
ejecutar la siguiente orden para borrar las caches del "apt" y
y así se fuerza que se descargue de nuevo todos los índices:

sudo rm /var/lib/apt/lists/* /var/cache/apt/*
(Da error con un par de directorios que no puede borrar pero es normal)

Un saludo, Rober.

**Comment by maxezek** [comment]
No, se ha dado con la tecla. La solución de Rober es solo parcial.

Parece que hay fallos aleatorios que despistan mucho.

Javier Puche ha añadido esto:

_En mis últimas pruebas a parte de todos los borrados que aconseja Rober he utilizado solo un fichero en /etc/apt/apt.conf.d/ con estos contenidos:
Acquire::Retries "999";
Acquire::http::Timeout "999";
Acquire::ftp::Timeout "999";
Acquire::Queue-Mode "host";
Acquire::http::No-Cache true;
Acquire::http::Pipeline-Depth 0;
Acquire::BrokenProxy true;
Acquire::CompressionTypes::Order::=gz;

(probado con y sin comillas)_

Hay que seguir mirando. ¿Se puede disponer de un mirror alojado en un sitio distinto? ¿RedIris? Sería para dar una solución temporal y verificar sie le problema está en la comunicación con los servidores de EducaMadrid donde esté alojado nuestro repositorrio.

**Comment by mariodebian** [comment]
Como se ha demostrado que no es problema de MAX voy a dejar este issue cerrado
