### ISSUE TITLE
MAX 9.5 beta1: Incluir en repos Pilas Engine y Pilas Bloques

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#901]
Ya teníamos una vieja versión de Pilas Engine en repos de MAX 8, creo, sino está en +Aplicaciones. Hay que actualizarla y meterla en los MAX 9, 9.5, etc.

Se trata de dos IDE de aprendizaje de Python para niños. Engine con código y Bloques como Scratch.

[https://github.com/hugoruscitti/pilas](https://github.com/hugoruscitti/pilas)

[https://github.com/Program-AR/pilas-bloques](https://github.com/Program-AR/pilas-bloques)

**Comment by mariodebian** [comment]
Recompilados empaquetados y subidos:

* **python-pilas** (1.4.12) y python-box2d
* **pilas-engine-bloques** (1.1.2) y electron (1.7.10)
