### ISSUE TITLE
MAX 9.5 beta 1: Actualizar GeoGebra

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#904]
Aportado or Pablo J. Triviño. 

En el momento de abrir este issue, 11/01/2017, la situación es la siguiente: Ubuntu 16.04 mate 64 bit actualizada. No se ve la ventana 3D en @geogebra 5.0.414 ni 6.0414

Los nuevos paquetes de eogebra y geogebra-classic del repositorio
http://www.geogebra.net/linux/ stable main

Meter en repo cuando se solucione lo anterior de MATE que nos está afectando. Se publica el issue porque mi memoria es de pez y no quiero que se pierda.

**Comment by mariodebian** [comment]
Subido 5.0.414.0-586960
El bug del 3D me parece que es entre las libs mesa y jogl

**Comment by mariodebian** [comment]
Como solución temporal hasta que mesa, jogl y geogebra se pongan de acuerdo se puede forzar la versión anterior de mesa.

Crear el archivo /etc/apt/preferences.d/mesa con este contenido los últimos 3 son solo necesarios cuando el equipo es de 64 bits.

```
Package: libegl1-mesa
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libegl1-mesa-drivers
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgbm1
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgl1-mesa-dri
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgl1-mesa-glx
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libglapi-mesa
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgles1-mesa
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgles2-mesa
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libosmesa6
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libwayland-egl1-mesa
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libosmesa6
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libxatracker2
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: mesa-vdpau-drivers
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001


Package: libgl1-mesa-dri:i386
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libgl1-mesa-glx:i386
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001

Package: libglapi-mesa:i386
Pin: version 11.2.0-1ubuntu2.2
Pin-Priority: 1001
```
