### ISSUE TITLE
MAX 9.5: Error de Musescore. Sin sonido cuando se da al play

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#906]
Hay que fijarse en este comportamiento anómalo de musescore que ha corregido Roberto Mengibar. Copio y pego de la lista de correo:

Hola Igor.

Abre un terminal y ejecuta la siguiente orden para solucionarlo:

sudo sed -i "s/PASUSPENDER=/#PASUSPENDER=/" /usr/bin/mscore

Dicha orden anula la línea 33 del fichero "/usr/bin/mscore", que es:

    PASUSPENDER=$(which pasuspender)

Por lo que he visto el comando "pasuspender" hace que se suspenda
el sistema de sonido de "PulseAudio", es decir que se queda como
en MUTE y no se oye nada, ni siquiera los sonidos del sistema.

No entiendo muy bien por qué lo hace, creo que antes el "musescore"
utilizaba otro sistema de audio y anulaba el PulseAudio para que no
hubiera conflictos, pero ahora me da la impresión de que ya funciona
con el PulseAudio y hay que comentar esa línea para que no lo anule.

Si después de ejecutar esa orden sigues sin escuchar el audio comprueba
que el volumen no se te ha bajado al mínimo como me pasó a mi, al subirlo
ya escuche la musica. Suerte.

Un saludo, Rober.

**Comment by mariodebian** [comment]
Subido musescore 2.1.0
