### ISSUE TITLE
MAX 9.5 beta1: Cambios en menús

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#909]
Cambios menores pero útiles para neófitos:

 * [ ] En Sistema > Administración > **Red** Cambiar Red por "**Cambiar nombre al equipo**" Actualmente solo se usa para eso y crea confusión con _Conexiones de red_.

 * [ ] En Sistema > Administración > **Configurar entrada automática**  cambiar el favicon de EducaMadrid por este: /usr/share/icons/maxtoons/64x64/categories/application-comunity.png

![application-community](https://user-images.githubusercontent.com/6005738/38827864-8ce93a56-41b4-11e8-9b90-456cc7cec960.png)

 * [ ] Incluir entrada a **synapse** desde el menú principal. Si es posible debajo de Lugares y Sistema. El nombre debe ser "**Buscador de aplicaciones**" para que sea significativo porque synapse no dice nada a nadie.

 * [ ] En Accesorios > **Pluma Text Editor** que ponga "**Editor de textos Pluma**".

**Comment by maxezek** [comment]
Sigue faltando este punto:

 * [ ] En Accesorios > **Pluma Text Editor** que ponga "**Editor de textos Pluma**".

**Comment by mariodebian** [comment]
Pues está puesto en Español:

https://github.com/max-linux/max-desktop/blob/master/max-mate-menus/usr/share/mate/applications/pluma.desktop

**Comment by mariodebian** [comment]
Vale, había una metaetiqueta puñetera:
```
X-MATE-FullName=Pluma Text Editor
```
