### ISSUE TITLE
El tema "MaxTheme" provoca que no sean bien los checkbox

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-desktop#910]
Por defecto el tema de un usuario está en "Personalizado". Si seleccionas el tema "MaxTheme" las casillas de verificación o checkbox no se ven bien, o mejor dicho ni se ven. Si damos al botón de personalizar el tema y vamos a la ficha "Controles", se observa que para los controles está por defecto "MaxTheme", cambiando a "MaxColors" se soluciona. Este cambio se graba en la siguiente clave de dconf(dconf-editor): "org.mate.desktop.interface:gtk-theme"
He comprobado que por defecto cuando se crea un perfil, dicha clave tiene el valor de "MaxColors". Cuando se cambia el tema a "MaxTheme", dicha clave toma el valor de "MaxTheme". Editando ese valor y poniendo "MaxColors" también se soluciona el problema.

La cuestión sería corregir el problema que tenga el tema "MaxThema" para que esto no pase y debería ser el tema que quede por defecto, no el de "Personalizado".

Adjunto un par de imágenes para comparar lo que ocurre con las casillas de verificación, en la primera se ven bien y en la segunda mal:

![firefox_03](https://user-images.githubusercontent.com/6009465/39352327-b221d118-4a04-11e8-80ee-d5d62c7a820d.png)
![firefox_02](https://user-images.githubusercontent.com/6009465/39352333-b5a12028-4a04-11e8-8438-00216f16a752.png)

**Comment by mariodebian** [comment]
MaxTheme es para MAX 8.x (que usaba gnome-fallback con GTK3)
En MAX 9.x no se usa ni debería (MATE es GTK2), voy a quitarlo para no provocar despistes...
