### ISSUE TITLE
Cambios versión 9.0 => 9.5 en imágenes, logos

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#912]
Hay que cambiar versiones y logo de Consejería

* [x] Fondos de pantalla [repo](https://github.com/max-linux/max-desktop/tree/master/max-artwork/art/wallpapers)
* [x] GRUB [repo](https://github.com/max-linux/max-desktop/blob/master/max-artwork/art/grub/maxgrub.png)
* [x] Lightdm [repo](https://github.com/max-linux/max-desktop/blob/master/max-artwork/art/gdm/Max/maxgdm.png)
* [x] Cabecera instalador [repo](https://github.com/max-linux/max-desktop/blob/master/ubiquity-frontend-max/usr/share/ubiquity/pixmaps/max/logo.png)
* [x] Navegador página por defecto [repo](https://github.com/max-linux/max-desktop/blob/master/max-ubufox/content/startpage.html)

* [x] syslinux-theme-maxZZ
* [x] isolinux/gfxboot
* [x] ubiquity-frontend-max (repo and hostname)
* [x] max-live
* [x] plymouth-max (splash)

**Comment by maxezek** [comment]
![logo_dgbae_derecha](https://user-images.githubusercontent.com/6005738/40473992-175e5b20-5f3e-11e8-8ccf-ef9d998281ab.png)
Este es el logo que hay que sustituir al de infraestructuras.

**Comment by maxezek** [comment]
Seguramente en letra blanca mejor.

![logo_dgbae_derechablanco](https://user-images.githubusercontent.com/6005738/40474123-76993ee8-5f3e-11e8-8b53-bbd3a73df404.png)

**Comment by mariodebian** [comment]
Editables subidos a: https://github.com/max-linux/max-art-templates
