### ISSUE TITLE
MAX 9.5: No funciona el administrador de arranque

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#913]
No va /usr/sbin/startupmanager. 

Antes bastaba con elegir el kernel del listado. Ahora no lo hace. 

Aparece un mensaje cuando se hace en el terminal que no se sipuede dar la pista:

Se encontró una imagen linux: /boot/vmlinuz-4.4.0-124-generic
Se encontró una imagen initrd: /boot/initrd.img-4.4.0-124-generic
Aviso: No use el título antiguo «MaX-9.5 GNU/Linux, con Linux 4.4.0-124-generic» para GRUB_DEFAULT, use «Advanced options for MaX-9.5 GNU/Linux>MaX-9.5 GNU/Linux, con Linux 4.4.0-124-generic» (para versiones anteriores a 2.00) o «gnulinux-advanced-704bfc17-336b-45a2-ad24-eb42649a1be3>gnulinux-4.4.0-124-generic-advanced-704bfc17-336b-45a2-ad24-eb42649a1be3» (para 2.00 o posteriores)

**Comment by mariodebian** [comment]
Subido startupmanager 1.9.13-5max19
