### ISSUE TITLE
MAX 9.5. No funciona la configuracuión de interfaz de LigthDM

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#914]
No hace nada **Configuración de interfaz GTK+ de LightDM** del menú Administración.

Es decir, no hace nada:

`lightdm-gtk-greeter-settings-pkexec`

Si no tiene porque funcionar por alguna cuestión técnica entonces hay que eliminarlo del menuú.

**Comment by mariodebian** [comment]
Usamos unity-greeter, por lo que no son necesarios los paquetes y lightdm no lo ejecuta.
Quitado de dependencias...
