### ISSUE TITLE
MAX 10 (o 9.5 si llega a tiempo): Incluir de serie eXeLearning 2.2

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#918]
La acaban de publicar.

Si se puede meter en la iso de la 9.5 que no se si estás ya compilando... genial. Si no pues al repo.

Te añado el fichero fuente: 

[Nueva fuente de eXeLearning](http://descargas.educalab.es/cedec/exe_learning/2.2/intef-exe-2.2-source.tgz)

[Página general de las descargas de eXe](http://exelearning.net/#download)

Logicamente, deben ir con los estilos de MAX y EducaMadrid que ya teniamos incluidos.

**Comment by jrodriguezpascua** [comment]
Eres el hombre bala Ezequiel. ;-)

**Comment by mariodebian** [comment]
Subido
