### ISSUE TITLE
MAX 10 prealfa. Errores encontrados con Ubuntu MATE y max-desktop

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#921]
### Cosas que no van bien:

* [ ] Al hacer dconf reset -f / la ventana de entrada de unity-greeter no es la de MAX

* [ ] otros...

### Actualizaciones:

* [x] Pasar GIMP a 2.10.

* [ ] otros...

**Comment by mariodebian** [comment]
Ahora ya no se usa unity-greeter sino slick-greeter, algún paquete depende todavía de lightdm-gtk-greeter y no hace que se pille el nuevo por defecto.

**Comment by mariodebian** [comment]
Gimp 2.10 subido, se ve raro (tema oscuro e iconos monocolor) se puede intentar dejar como estaba.
