### ISSUE TITLE
MAX10 Qucs

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#924]
Abre, pero falla al tratar de simular los circuitos (dice algo así como "simulation crashed!"). He probado con el de continua (que es el más habitual).

**Comment by mariodebian** [comment]
Arreglado en qucs (0.0.19-0max2)

**Comment by mariodebian** [comment]
Ref: https://github.com/Qucs/qucs/pull/712/files

**Comment by mariodebian** [comment]
Subido qucs 0.0.19.git20180725 (snapshot de GIT, esta a punto la versión 0.0.20)

**Comment by mariodebian** [comment]
> @dgonzalezarroyo
> Hola Mario
>
> He seguido probando QUCS. Las simulaciones en continua, alterna, transitorios y en parámetros funcionan bien. Pero la simulación digital da problemas. He utilizado este archivo para probarla --> http://cloud.educa.madrid.org/index.php/s/bEfKfA3O844QnJG Aparece al simular un error de "segmentation fault".

**Comment by DaniMAdridlinuX** [comment]
Funciona perfectamente en MAX 11.5.2
