### ISSUE TITLE
MAX10 Empaquetar shotcut

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#925]
https://github.com/mltframework/shotcut/releases

**Comment by mariodebian** [comment]
Subido 18.07

**Comment by dgonzalezarroyo** [comment]
Parece ser que el ejecutable de shotcut está en /usr/lib/shotcut/shotcut ,que no está en $PATH, y por eso no lo encuentra. J. M. Sancho propone que el instalador del paquete cree un enlace simbólico en /usr/bin a /usr/lib/shotcut/shotcut y modificar el lanzador del menú.
