### ISSUE TITLE
MAX 10 prealfa:  bloqueo de instalación de programas

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#927]
Esto me ocurría en MAX 9 con cierta frecuencia pero ahora es siempre en MAX 10. Cuando intento hacer un apt upgrade o instalar algo nada más entrar en sesión me dice que otra aplicación está bloqueando la instalación.

Lo resuelvo con sudo rm /var/lib/dpkg/lock/

**Comment by mariodebian** [comment]
No es un bug, es una feature.

Ubuntu 16.04 y 18.04 incluyen el paquete "unattended-upgrades" que al arrancar actualizan el sistema.

Durante ese tiempo las operaciones manuales de apt/dpkg/synaptic no se pueden ejecutar por que el sistema lo tiene bloqueado.

He pensado si no instalar ese paquete (o desactivarlo) pero la verdad es que el equipo se actualice sólo es un punto a favor en muchos casos.

**Comment by maxezek** [comment]
Me lo imaginaba... debía haber buscado en la red antes.

Si, es mejor dejarlo pero debería saltar alguna notificación indicando la circunstancia o algo así. A un TIC poco técnico (lo habitual) que tienen poco tiempo esto es una de esas cosas que te pueden sacar de quicio. Habría que ver si alguien ya ha pensado en esto y si no intentar poner alguna mención cuando se abra max-mate-welcome.

**Comment by mariodebian** [comment]
He hecho una pequeña aplicación que saca un icono en la bandeja del sistema cuando unattended-upgrades se está ejecutando, voy a ponerlo para que se instale y lance por defecto.

**Comment by maxezek** [comment]
Genial!!! :-) 
Yo estoy ya en modo vacaciones y lejos de cualquier pc pero si necesitas algo intento echarte una mano. 1 de septiembre ya aquí a tope.

**Comment by mariodebian** [comment]
He probado el nuevo icono y excepto su aspecto gráfico (que podría ser otro icono) creo que cumple su función, cierro issue.
