### ISSUE TITLE
MAX 10 prealfa: Openroberta no se instala

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#928]
Necesita que tengamos estas dependencias:

libusb-0.1-4 gcc-avr binutils-avr gdb-avr avr-libc avrdude nbc gcc-arm-none-eabi srecord libssl-dev 

Y una dependencia que según la web se instala con pip 

uflash
o
python-uflash

[OpenRoberta en github](https://github.com/OpenRoberta/robertalab)

**Comment by mariodebian** [comment]
Subido python-uflask, el resto de dependencias ya estaban.
