### ISSUE TITLE
MAX prealfa: Actualizar OBS y añadir plugin linux-browser

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#930]
Actualmente está para Linux la versión 22.0.2 

[OBS en GitHub](https://github.com/obsproject/obs-studio)

Linux-browser es un plugin necesario para usar la web en el mismo streaming.

[Página de descarga del plugin](https://obsproject.com/forum/resources/linux-browser.509/)

[El fuente en github](https://github.com/bazukas/obs-linuxbrowser/releases)

**Comment by mariodebian** [comment]
Subido obs-studio 22.0.2
Probablemente habrá que poner como paquete recomendado ￼max-obs-linuxbrowser para que se instalen los dos.

**Comment by DaniMAdridlinuX** [comment]
Desde MAX 11 ya se incluye este plugin en OBS
