### ISSUE TITLE
MAX 10 PREALFA: La versión de openboard se cierra al guardar en su formato

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#932]
La versión de nuestro repo resulta que se cierra cuando das a guardar en el formato nativo de openboard .ubz (un .zip realmente).

Sin embargo la misma versión de la web de openboard funciona sin problemas.

[Github de OpenBoard](https://github.com/OpenBoard-org/OpenBoard)

**Comment by mariodebian** [comment]
No hay versión en su web para Ubuntu 18.04, ¿con cual lo estas comparando?

**Comment by maxezek** [comment]
Me descargue la versión equivalente de la web:

[openboard para 16.04](https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.4.1/openboard_ubuntu_16.04_1.4.1_amd64.deb)

Si se fuerza a instalar está versión en vez de la del repo de MAX resulta que está no se cierra al exportar a formato ubz nativo de OpenBoard (que no es más que un .zip)

Eso es lo raro porque la versión se supone que es la misma.

**Comment by mariodebian** [comment]
Arreglado y subida version 1:1.4.1-0max3

Bug aquí: https://github.com/OpenBoard-org/OpenBoard/issues/170
