### ISSUE TITLE
MAX 10 prealfa: Duplicado de welcome-mate y max-mate-welcome

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#933]
En mi MAX 10 en vbox ocurre. Aparecen duplicados las ventanas de bienvenida.

También aparecen duplicados en el menú administración las bienvenidas y un menu duplicado boutique.

Tengo una MAX 10 prealfa real. Veré si le ocurre también pero lo añado por si las moscas.

**Comment by mariodebian** [comment]
Tienes instalado un MATE y luego has añadido el repo de MAX, es normal que ese "Frankestein" tenga cosas como esta o peores !!!

**Comment by maxezek** [comment]
jajajaja

Tienes razón. Estamos de suerte con que salgan solo este tipo de problemas. No le hagas caso hasta la iso.
