### ISSUE TITLE
 MAX10:  Scratch 3.0,  relacionado con MAX10 Scratch2 #922 y Snap Noenresumen

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#935]
Este es un issue de nivel de urgencia **mínimo**.

Tenemos mala suerte. Vamos a estar a caballo con la salida de Scratch 3 que está ahora en beta pero funcional. La versión beta está en:

[https://github.com/LLK/scratch-gui](https://github.com/LLK/scratch-gui)

Échale un ojo por encima a ver si es fácil llevar está versión en MAX 10 y luego actualizar cuando salga la definitiva.

También tiene relación con Snap y snap4arduino que pusé para la boutique de max-mate-welcome en

[https://github.com/max-linux/max-mate-welcome/issues/2](https://github.com/max-linux/max-mate-welcome/issues/2)

A mi Snap me sirve igual o mejor que Scratch pero los compañeros de Primaria se quejan de falta de las galerias de objetos e imágenes que tiene Scratch. Se supone que son compatibles. 

La pregunta es: ¿se puede hacer que Snap tenga la misma galería que Scratch y Scratch2?

**Comment by DaniMAdridlinuX** [comment]
Desde MAX 11 incluimos Scratux y funciona perfectamente además de ser offline
