### ISSUE TITLE
MAX 10: Iconos desaparecidos en menú o para cambiar

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#942]
En menú Pizarra digital

* [x] Mypaint

En menú Herramientas del sistema

* [x] max-configurador-java

En menú Sistema

* [ ] bienvenida  (max-welcome) poner el icono max-inside.png

**Comment by mariodebian** [comment]
OpenBoard rebuild with desktop launcher

**Comment by mariodebian** [comment]
MyPaint arreglado: https://github.com/mypaint/mypaint/issues/918
