### ISSUE TITLE
MAX 10:  Falta opensankore/openboard en menú pizarra digital

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#943]
No tiene mucho sentido el menú si no va uno de los dos.

Parece que por falta de interactividad se prefiere recuperar opensankore aunque este descontinuado.

**Comment by maxezek** [comment]
Dos problemas. Uno por culpa mía.

El fichero .desktop en exec= tiene openboard en vez de  **OpenBoard** y por tanto al hacer clic en el menú no se abre.

Lo segundo y donde no te he dicho nada, creo, es en la recuperación de open-sankore.  Se ha debatido en el correo y en el wekan. A openboard resulta que le falta interactividad así que como herramienta de pizarra digital se prefiere el antiguo sankore aunque tenía problemas de estabilidad.

La idea es OpenBoard en repos y recuperar opensankore por defecto. Lo tenemos en repos así que es simplemente intercambiar OpenBoard por sankore en el menú de pizarra digital

Sorry

**Comment by mariodebian** [comment]
El nuevo empaquetador de OpenBoard para Debian no ha añadido lanzador, lo he añadido yo reempaquetandolo y se me han traspapelado mayúsculas y minúsculas... subiendo nueva versión.

En cuanto a sankore, he cerrado este issue porque he puesto Sankore por defecto y OpenBoard en repos, no se te ha aplicado en tu MAX porque es dependencia de uno u otro (ver commit 7ed5f11) , no se fuerza a desinstalar, **en la próxima ISO vendrá sólo SANKORE**.

**Comment by maxezek** [comment]
Ok Mario. Muchas gracias :-)
