### ISSUE TITLE
MAX10 (inf-prim). Programas que instalar

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#945]
Plopp
Blinken
frozen bubble
ri-li
Fuentes tipográficas (se llamaban ttf-linex pero no las encuentro en synaptic)

Ktouch no aparece en el menú de lengua

Falla Marble (paquete roto)

No se si estaba por defecto klavaro o arasuite (esta última pesará mucho).

Marble me da problemas.

gcompris
childsplay
omnitux
pysicache
pysiogame
tuxtype
tuxmath
tux paint
ktuberling
pinta
kgeography
ktouch
khangman (este creo que ya estaba instalado)

**Comment by Marito17** [comment]
https://aur.archlinux.org/packages/ttf-linex-fonts/
https://www.opendyslexic.org/

**Comment by mariodebian** [comment]
Las fuentes de linex están el paquete fonts-linex (casi todos los paquetes de fuentes se han renombrado de ttf-XXXX a fonts-XXXX)

El metapaquete de infantil y primaria depende de fonts-linex.

El resto de programas que no están es porque no compilan
