### ISSUE TITLE
MAX10: Usuario sin contraseña

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#946]
Al aparecer la ventana de selección de usuario no aparece el campo para meter la contraseña. Quizá es porque lo he hecho en máquina virtual.

**Comment by mariodebian** [comment]
¿donde?

**Comment by Marito17** [comment]
En la pantalla de selección de usuarios (Alumno o Madrid). Pero si nadie más dice nada, debe de ser un comportamiento de la máquina virtual en mi equipo.
