### ISSUE TITLE
MAX10 (inf-prim) Crea barra de la personalización

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#947]
Con el siguiente orden:
Gcompris
Childsplay
Omnitux
Pysycache
EduActiv8 (antigo Pysiogame)
Khangman
Tuxtype
Tuxmath
Tuxpaint
Ktuberling (señor patata)
Pinta
Scratch

**Comment by mariodebian** [comment]
No se por qué se ha abierto este issue.

Instando el paquete max-infantil y reiniciando (o cerrando sesión) sale el fondo de infantil y el panel con esos iconos y en ese orden:

![max-infantil](https://user-images.githubusercontent.com/522472/47608946-6ad17080-da36-11e8-8dec-eae362efb71e.png)
