### ISSUE TITLE
MAX10 (inf-prim): Gcompris pide actualizar al empezar

### ISSUE THREAD

**Issue by Marito17** [max-linux/max-desktop#948]
En versiones anteriores gcompris al iniciar revisaba todos los programas. En esta versión aparece una pantalla que pregunta sobre hacerlo. Es dar a aceptar, pero el usuario alumno no va a guardarlo y va a despistar a los alumnos. Si se puede quitar ese paso y que lo haga automático mejor. Me lo apunto para buscar en las configuraciones como hacerlo.

**Comment by mariodebian** [comment]
Descargado voces en español y configuración inicial de 0.91 en paquete
max-mate-settings-infantil 10.0.max7
