### ISSUE TITLE
MAX 10: Problemas y ajustes relacionados con GIMP 10

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#953]
Son varias cosas:

* [ ] No se si es por la MV pero el caso es que no puedo editar, pintar u otras acciones con GIMP. Salen las herramientas en gris como si fuese de "solo lectura" la imagen a tratar.

* [x] El aspecto que sea lo más parecido al antiguo 2.8

* [ ] Incluir de serie el plugin [gimp-gap](https://github.com/GNOME/gimp-gap)

**Comment by mariodebian** [comment]
El tema de iconos no se aplica la primera vez que se abre GIMP, hay que abrirlo 2 veces para que se carguen bien.

Igual recompilo gimp para que lleve este tema por defecto.
