### ISSUE TITLE
MAX 10: Aplicaciones que deberían ir de serie

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#954]
Esto es si hay sitio en la iso. Si no nada:

* [x] [Arduino IDE](https://github.com/arduino/Arduino)

* [x] [Bootrepair](https://launchpad.net/~yannubuntu/+archive/ubuntu/boot-repair) Lo uso tan frecuentemente que estaría guay que estuviese en la live.

* [x] [Blender](http://download.blender.org/source/blender-2.79b.tar.gz)

* [x] Y actualizar [bluegriffon](http://bluegriffon.org/freshmeat/3.0.1/bluegriffon-3.0.1.Ubuntu16.04-x86_64.tar.bz2)

**Comment by dgonzalezarroyo** [comment]
¿Y openscad?

**Comment by maxezek** [comment]
Pues ahí lo suyo sería matar dos pájaros de un tiro: FreeCad 0.17 lleva incorporado OpenScad. Lo malo es que FreeCad es bastante pesado unos 200 MB.

* [ ]  [OpenScad](https://launchpad.net/~openscad/+archive/ubuntu/releases/+packages)

**Comment by mariodebian** [comment]
Hecho
Sube 1010 MB con todas las dependencias

**Comment by maxezek** [comment]
Muchas gracias Mario. Si luego resulta que el DVD no da de si damos marcha atrás aquí con FreeCAD en primer lugar que es el más pesado. Y así hasta que la .iso tenga el tamaño de DVD. Cruzo los dedos para que quepa todo.

**Comment by mariodebian** [comment]
Acabo de cerrar beta2 y se está construyendo, esta tarde haré alguna prueba y mañana la publico si todo va bien.

**Comment by maxezek** [comment]
Muuuchas gracias again. Y me he confundido porque he dicho FreeCAD y es Blender. Si entra bien en la beta2 me vas a dar una alegría.

**Comment by mariodebian** [comment]
Bueno, se ha generado:
4,7 GB => 4723M => 4835880K=> 4951941120

Me da que sobran esos 23 MB y puede que algo más.

Falta meter la doc actualizada y pequeños cambios, habría que bajar unos 100 MB para no ir tan justos.

**Comment by mariodebian** [comment]
20 paquetes que más ocupan (tamaño en KB):

* 132042  libreoffice-core
* 134161  max-manuales
* 134299  libgl1-mesa-dri
* 137703  freecad
* 138655  fritzing-parts
* 144298  openclipart-png
* 147486  libgl1-mesa-dri
* 149389  libvtk6.3
* 149849  intef-exe
* 161309  thunderbird
* 167044  linux-modules-extra-4.15.0-38-generic
* 169503  openclipart-svg
* 174294  firefox
* 179059  openjdk-11-jre-headless
* 200183  chromium-browser
* 210875  oracle-java8-bin
* 213625  stellarium-data
* 226237  skypeforlinux
* 266695  arduino-core
* 271097  linux-firmware

**Comment by maxezek** [comment]
Y falta lo realcionado con max-mate-welcome...

Mi voto sería conservar blender y suprimir Skypeforlinux. Y si aún así estamos muy justos, eliminar FreeCAD. Y ambos a la boutique.

**Comment by mariodebian** [comment]
Igual hago una beta2 de nuevo con esos cambios ;)

**Comment by maxezek** [comment]
Ok, me apena lo de FreeCAD pero está en una evolución constante y la versionitis nos puede matar.
Sorry por provocar un "enlatado" iso estresante
