### ISSUE TITLE
Error soporte de idiomas incompleto

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#956]
Cuando instalas MAX 10.0 alfa en un Pentium D, además de ser un milagro ;-) si cuando lo arrancas no has configurado la red (tenemos las ips fijas y no por DHCP) nada más arrancar da el siguiente error. "Soporte de diomas incompleto".

Adjunto imagen.

![error_soporte idiomas incompleto](https://user-images.githubusercontent.com/15038302/47658196-da5c7280-db92-11e8-9528-7c4267b4031a.png)

**Comment by mariodebian** [comment]
Arreglado en 8254a6d751e058024137e7f5a97407522eaa1e40
Faltaba gnome-user-docs-es
