### ISSUE TITLE
MAX 10... no es un issue es una duda sobre LXQt

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#965]
En las isos beta de MAX aparcecen programas y referencias a LXQt. Incluso el selector de escritorio permite cambiar de MATE a LXQt que este último te solicita elegir un gestor de ventanas.

¿Es normal?

**Comment by mariodebian** [comment]
Hay algún paquete intentando instalar otros escritorios, intento evitarlo metiendolos en lista negra [*]
En cada ISO se añaden nuevos.

[*] https://github.com/max-linux/max-desktop/blob/master/max-genlive/usr/share/max-genlive/pkgs/max.blacklist
