### ISSUE TITLE
MAX 10: Aparece Screenshot en menú gráficos y es innecesario

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#967]
Quitar del menú gráficos **Screenshot**

**Comment by mariodebian** [comment]
En mi MAX no:

![graficos](https://user-images.githubusercontent.com/522472/48334723-ea2c8a00-e65b-11e8-866f-02ddb549065b.png)

**Comment by maxezek** [comment]
El mío es en virtualbox. La última que me he instaldo era versión TCOS a lo mejor de ahí viene la diferencia.

He instalado con las opciones del instalador normal, con Infantil y primaria y TCOS. Pero solo me fijeé en está última.

Tengo que intentar isntalar con LVM y cifrado. Pero voy de cul... y contra el viento.

**Comment by mariodebian** [comment]
De la lista ha salido quién ese ese "screenshot" => /usr/share/applications/lximage-qt-screenshot.desktop

En la beta3 no debería salir ya que estan bloqueados los paquetes LxQT.
