### ISSUE TITLE
CANDIDATOS a desinstalarse (por tamaño)

### ISSUE THREAD

**Issue by mariodebian** [max-linux/max-desktop#969]
Creo que la última ISO andaba por 4.8 GB, hay que aligerar...

# Probables
* [ ] adobe reader (arrastra muchas dependencias de 32 bits) (197 MB)
* [ ] bluegriffon (134 MB)
* [ ] K3b (tenemos brasero) (22 MB)
* [ ] stellarium (242 MB)
* [ ] fritzing (159 MB)
* [ ] librecad (115 MB)
* [ ] scribus (60 MB)
* [x] snapd (58 MB)
* [ ] ibus (44 MB)
* [x] xine-ui (arrastrado por dvdstyler) (10 MB)
* [x] josm (editor mapas openstreetmap) (30 MB)

# Necesarios
* [ ] blender (212 MB)
* [x] freecad (477 MB)
* [ ] arduino (273 MB)
* [ ] chromium (tenemos firefox por defecto) (225 MB)

# DVD <sup><sub>(paquetes para infantil sobre todo) (633 MB total)</sub></sup>
* [ ] tuxpaint (164 MB)
* [ ] omnitux (133 MB)

---
... seguir editando ...

**Comment by maxezek** [comment]
Hola Mario.

Si hay que ganar espacio... con todo el dolor de mi corazón quitamos **FreeCAD** pero entonces metemos **OpensCAD**.

Pero entonces hay que cambiar el issue 6 de [max-mate-welcome](https://github.com/max-linux/max-mate-welcome/issues/6)  

Uno por otro.

Y luego **josm** que creo que apenas se usa (aunque es una intuición)
