### ISSUE TITLE
La página de inicio de Firefox viene por defecto en inglés.

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#977]
En MAte-Wellcome he pulsado sobre el icono de MAX en la parte inferior, y abre bien el enlace, pero he visto que también se abre la pestaña de bienvenida de Firefox, y se muestra en inglés.
Carga esta página: https://www.mozilla.org/en-US/privacy/firefox/

**Comment by mariodebian** [comment]
Firefox abre en español (el interfaz) por lo tanto **no hay bug**

La primera vez que se ejecuta firefox se abre una pestaña con las condiciones de uso de Firefox  (que está en inglés) y que está fuera de todo nuestro control.
