### ISSUE TITLE
En Mate-Wellcome, error en el enlace al foro de MAX

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#978]
En Mate-Wellcome, pestaña de "participa" te lleva a una sección con varios enlaces.
El del foro de MAX no funciona. Lleva a:
http://www.http.com//foros.educa.madrid.org/viewforum.php?f=20
Cuando debería llevar a:
http://foros.educa.madrid.org/viewforum.php?f=20

**Comment by mariodebian** [comment]
Arreglado en https://github.com/max-linux/max-mate-welcome/issues/8
