### ISSUE TITLE
MAX 10 Final: TCOS como control de aula.

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#979]
De momento, he probado desde una MAX 9.5 con TCOS monitor a conectarme a una máquina real con MAX 10 con TCOSstandalone activado.

Aunque se ve la máquina no se conecta a ella por VNC.

Esto es importante porque empezará a haber un parque mixto de MAX 10 (solo 64 bits) con PC más viejos y las instalaciones de max-profesor y max-alumno deberían de funcionar.

**Comment by DaniMAdridlinuX** [comment]
Las incidencias que impliquen a MAX 9.5 podemos ir cerrándolas ya que los centros deben empezar a pasarse a la 11 o a la 10 en su defecto.
