### ISSUE TITLE
MAX10: MrPDI y drivers de Teamboard

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#985]
* [ ] **MrPDI**
La actual versión de MrPDI no va en MAX10. Al intentar instalar devuelve:
Cuando se intenta instalar MrPDI no puede instalar mrpdi-gui:

_Depende: libgtkmm-3.0-1  but it is not installable_
 _Depende: libconfig++9  but it is not installable_

Y si se usa mrpdi-cli:

_madrid@A27-PC00:~$ mrpdi-cli_
_Instrucción ilegal_

Sin embargo he encontrado la versión de LinKat 18 que si que van:

[Ficheros extres de linkat 18 ](ftp://download-linkat.xtec.cat/distribution/linkat-edu-18.04/extres/)

[Y las fuentes van en .deb aquí](ftp://download-linkat.xtec.cat/distribution/linkat-edu-18.04/dev-extres/)

* [ ] **Teamboard**

Está vieja roquera ya descatalogada y con el fabricante desaparecido va con MrPDI de Linkat pero se calibra bastante mal.

He probado con los [drivers Teamboard](http://cloud.educa.madrid.org/index.php/s/u8hTagUKErlEp3H) que tenemos desde la MAX 7 y que han funcionado con MAX 8 y MAX 9 (en MAX 9 luego se calibra no con el software de Temboard sino con xinput-calibrator) y nada.

El calibrador de su software devuelve está respuesta:

_madrid@A27-PC00:~$ /opt/tbupddlx/upddcalib_
_/opt/tbupddlx/tbcalib: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory_

**Comment by DaniMAdridlinuX** [comment]
Las PDI desaparecen de los centros y se instalan panelas táctiles que funcionan perfectamente con MAX
