### ISSUE TITLE
Error al actualizar flashplugin-installer

### ISSUE THREAD

**Issue by jrodriguezpascua** [max-linux/max-desktop#989]
Reportado por Roberto Mengibar.

Al actualizar MAX10 me aparece el mensaje indicando
que no se ha podido instalar el "flashplugin-installer"(adjunto
captura de pantalla). He probado a reinstalar el paquete
manualmente:

sudo apt install --reinstall flashplugin-installer

No da ningún error, a ver si así deja de aparecer el mensaje.

Un saludo, Rober.

**Comment by mariodebian** [comment]
Lo mismo que el #769:

El fin de vida de FLASH es Diciembre de 2020: https://www.adobe.com/es/products/flashplayer/end-of-life.html

No va a haber soporte, no se va a poder descargar y los navegadores no lo van a ejecutar.

Creo que es mejor olvidarse de flash.
