### ISSUE TITLE
MAX 10.5: Actualizar eXeLearning

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#994]
Tenemos una 2.2 y ya está la 2.3.1. Y si cuando llegue el momento hay otra siempre ir a la última estable.

Las fuentes [estan aquí.](http://descargas.pntic.mec.es/cedec/exe_learning/2.3.1/intef-exe-2.3.1-source.tgz)

**Comment by DaniMAdridlinuX** [comment]
Ya tenemos la 2.6 en MAX11
