### ISSUE TITLE
MAX 10.5: Considerar cambiar shutter por flameshot o ksnip

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#995]
Shutter ha parado su desarrollo. Como alternativa tenemos **flameshot** que además es bastante estética.

[Los fuentes están aquí](https://github.com/lupoDharkael/flameshot)

Así que  en la 10.5 sacarlo de serie. Está en repos de Ubuntu 18.04. Sería bueno meterlo en repos de MAX 9.5 si es posible

**Comment by jrodriguezpascua** [comment]
A mi Shutter me encanta, pero no he probado flameshot. Lo probaré a ver. Si han parado el desarrollo, quizá habría que plantearse el cambio, sí.

**Comment by DaniMAdridlinuX** [comment]
Como Shutter se ha actualizado, va de serie en MAX11 y funciona bien continuamos con él y no instalamos ni ksnip ni Flameshot
